/* RAPP skill/agent mirroring — the same export, in the browser.
 *
 * scripts/export_agent.py derives an agent.py from a skill.md at build time.
 * This file does the identical derivation client-side, on the fly, from the
 * skill.md the page already fetched.
 *
 * That redundancy is the point. A claim that two formats are projections of one
 * contract is just a claim until something re-derives one from the other and
 * the result matches byte for byte. A gate compares this output against the
 * committed Python export, so if the two implementations ever disagree, the
 * mirroring is broken and the build says so instead of the page quietly
 * shipping a different file than the repository holds.
 *
 * Keep in lockstep with scripts/export_agent.py. Both are gated.
 */
(function (global) {
  "use strict";

  var MANIFEST_SCHEMA = "rapp-agent/1.0";

  function splitFrontmatter(text) {
    if (text.indexOf("---") !== 0) return { meta: {}, body: text };
    var end = text.indexOf("\n---", 3);
    if (end === -1) return { meta: {}, body: text };
    var meta = {};
    text.slice(3, end).split("\n").forEach(function (line) {
      line = line.trim();
      if (!line || line.indexOf(":") === -1 || line.charAt(0) === "#") return;
      var i = line.indexOf(":");
      var k = line.slice(0, i).trim();
      var v = line.slice(i + 1).trim();
      if (v.charAt(0) === "[" && v.charAt(v.length - 1) === "]") {
        meta[k] = v.slice(1, -1).split(",").map(function (x) {
          return x.trim().replace(/^['"]|['"]$/g, "");
        }).filter(Boolean);
      } else {
        meta[k] = v.replace(/^['"]|['"]$/g, "");
      }
    });
    return { meta: meta, body: text.slice(end + 4).replace(/^\n+/, "") };
  }

  function className(slug) {
    var parts = slug.split(/[^A-Za-z0-9]+/).filter(Boolean);
    var name = parts.map(function (p) {
      return p.charAt(0).toUpperCase() + p.slice(1);
    }).join("");
    if (!name || /^[0-9]/.test(name)) name = "Skill" + name;
    return name + "Agent";
  }

  /* Python's json.dumps(..., indent=4, ensure_ascii=False) and
   * JSON.stringify(..., null, 4) agree for the types a manifest carries:
   * strings, arrays and objects, in insertion order. */
  function pyLiteral(value) {
    return JSON.stringify(value, null, 4);
  }

  function j(value) {
    return JSON.stringify(value);
  }

  function exportAgent(skillText) {
    var split = splitFrontmatter(skillText);
    var meta = split.meta, body = split.body;

    var ref = meta.name || "@aggregated/skill";
    var slug = ref.split("/").pop();
    var display = meta.display_name || slug;
    var description = meta.description || "";
    var licenseId = meta.source_license || "";
    var sourceUrl = meta.source_url || "";
    var convertedFrom = meta.converted_from || "an upstream project";
    var author = meta.author || convertedFrom;

    var tags = meta.tags || [];
    if (typeof tags === "string") tags = [tags];

    var agentDescription =
      "Returns the verified RAPP procedure for: " + description + " " +
      "Call this to obtain the full step-by-step contract (inputs, outputs, " +
      "verification) and then carry out those steps.";

    var manifest = {
      schema: MANIFEST_SCHEMA,
      name: ref,
      version: meta.version || "1.0.0",
      display_name: display,
      description: agentDescription,
      author: author,
      tags: tags.slice(0, 8),
      category: meta.category || "aggregated",
      quality_tier: "aggregated",
      requires_env: meta.requires_env || [],
      dependencies: ["@rapp/basic-agent"],
      mirrors: slug + ".md",
      source_url: sourceUrl,
      source_license: licenseId,
      converted_from: convertedFrom
    };

    // Escape backslashes FIRST, exactly as the Python exporter does — doing it
    // after would double the backslashes the quote-escaping introduces.
    var safeBody = body.replace(/\s+$/, "")
      .split("\\").join("\\\\")
      .split('"""').join('\\"\\"\\"');

    return '"""\n' +
display + " — RAPP agent, mirrored from " + slug + ".md\n\
\n\
This file is GENERATED from its skill.md by scripts/export_agent.py and is one\n\
half of a matched pair. The manifest below and the procedure embedded further\n\
down are identical to the ones in the .md; the only difference is the runtime:\n\
a model reads the .md, a brainstem registers this .py and calls it as a tool.\n\
\n\
Do not edit this file. Edit " + slug + ".md and re-run the exporter — the gate\n\
re-derives this file and fails if the two have drifted apart.\n\
\n\
Redistributed from " + convertedFrom + " under " + (licenseId || "its upstream licence") + "\n\
with attribution. Original author: " + author + ".\n\
Origin: " + sourceUrl + '\n\
"""\n\
\n\
# ===============================================================\n\
# RAPP AGENT MANIFEST - Do not remove. Used by registry builder.\n\
# ===============================================================\n\
__manifest__ = ' + pyLiteral(manifest) + "\n\
# ===============================================================\n\
\n\
try:  # cloud layout (agents package)\n\
    from agents.basic_agent import BasicAgent\n\
except ImportError:  # local brainstem / standalone layout\n\
    import os\n\
    import sys\n\
\n\
    sys.path.insert(0, os.path.join(\n\
        os.path.dirname(os.path.abspath(__file__)), \"..\", \"..\",\n\
        \"agents\", \"@aibast-agents-library\", \"templates\"))\n\
    from basic_agent import BasicAgent\n\
\n\
\n\
# The skill body, embedded verbatim. This is what makes the export single-file:\n\
# the procedure travels with the agent rather than being fetched at call time.\n\
SKILL_PROCEDURE = \"\"\"" + safeBody + "\n\
\"\"\"\n\
\n\
SKILL_REF = " + j(ref) + "\n\
SKILL_LICENSE = " + j(licenseId) + "\n\
SKILL_SOURCE = " + j(sourceUrl) + "\n\
\n\
\n\
class " + className(slug) + "(BasicAgent):\n\
    \"\"\"Delivers a verified RAPP procedure as a callable tool.\n\
\n\
    Inputs — none required. `context` optionally narrows the returned\n\
        procedure to a stated situation; it is echoed back, never invented.\n\
    Output — the full skill procedure as text: inputs, outputs, and the\n\
        verification step the caller must perform before reporting success.\n\
    Verification — the caller confirms the artifact named by the procedure\n\
        exists and matches what was asked. This agent returns instructions; it\n\
        does not perform the work described in them, and it never reports\n\
        success on the caller's behalf.\n\
    Configuration — none. The procedure is embedded in this file.\n\
    \"\"\"\n\
\n\
    def __init__(self):\n\
        self.name = " + j(display) + "\n\
        self.metadata = {\n\
            \"name\": self.name,\n\
            \"description\": __manifest__[\"description\"],\n\
            \"parameters\": {\n\
                \"type\": \"object\",\n\
                \"properties\": {\n\
                    \"context\": {\n\
                        \"type\": \"string\",\n\
                        \"description\": (\n\
                            \"Optional. The specific situation the procedure is \"\n\
                            \"being applied to, echoed back with the steps — for \"\n\
                            \"example 'a 40-slide deck for an external customer'.\"\n\
                        ),\n\
                    }\n\
                },\n\
                \"required\": [],\n\
            },\n\
        }\n\
        super().__init__(name=self.name, metadata=self.metadata)\n\
\n\
    def perform(self, **kwargs):\n\
        context = (kwargs.get(\"context\") or \"\").strip()\n\
        header = [\n\
            f\"# {self.name} — RAPP procedure\",\n\
            \"\",\n\
            f\"Source: {SKILL_REF} · redistributed under {SKILL_LICENSE} \"\n\
            f\"with attribution ({SKILL_SOURCE}).\",\n\
        ]\n\
        if context:\n\
            header += [\"\", f\"**Applied to:** {context}\"]\n\
        header += [\n\
            \"\",\n\
            \"Follow the steps below exactly. Where a step names an input you \"\n\
            \"do not have, say so and stop rather than guessing, and complete \"\n\
            \"the verification step before reporting success.\",\n\
            \"\",\n\
            \"---\",\n\
            \"\",\n\
        ]\n\
        return \"\\n\".join(header) + SKILL_PROCEDURE\n";
  }

  global.RAPPMirror = { exportAgent: exportAgent, splitFrontmatter: splitFrontmatter };
})(window);
