"""
AI-First Process Redesign — RAPP agent, mirrored from ai_first_process_redesign.md

This file is GENERATED from its skill.md by scripts/export_agent.py and is one
half of a matched pair. The manifest below and the procedure embedded further
down are identical to the ones in the .md; the only difference is the runtime:
a model reads the .md, a brainstem registers this .py and calls it as a tool.

Do not edit this file. Edit ai_first_process_redesign.md and re-run the exporter — the gate
re-derives this file and fails if the two have drifted apart.

Redistributed from CAT Agent Skills under MIT
with attribution. Original author: Tim Sparks.
Origin: https://microsoft.github.io/cat-agent-skills/#ai-first-process-redesign
"""

# ===============================================================
# RAPP AGENT MANIFEST - Do not remove. Used by registry builder.
# ===============================================================
__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@cat-agent-skills/ai_first_process_redesign",
    "version": "2.1.1",
    "display_name": "AI-First Process Redesign",
    "description": "Returns the verified RAPP procedure for: Redesign your existing processes with AI-first thinking Call this to obtain the full step-by-step contract (inputs, outputs, verification) and then carry out those steps.",
    "author": "Tim Sparks",
    "tags": [
        "productivity",
        "process-improvement",
        "agentic-workflow"
    ],
    "category": "it_management",
    "quality_tier": "aggregated",
    "requires_env": [],
    "dependencies": [
        "@rapp/basic-agent"
    ],
    "mirrors": "ai_first_process_redesign.md",
    "source_url": "https://microsoft.github.io/cat-agent-skills/#ai-first-process-redesign",
    "source_license": "MIT",
    "converted_from": "CAT Agent Skills"
}
# ===============================================================

try:  # cloud layout (agents package)
    from agents.basic_agent import BasicAgent
except ImportError:  # local brainstem / standalone layout
    import os
    import sys

    sys.path.insert(0, os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "..",
        "agents", "@aibast-agents-library", "templates"))
    from basic_agent import BasicAgent


# The skill body, embedded verbatim. This is what makes the export single-file:
# the procedure travels with the agent rather than being fetched at call time.
SKILL_PROCEDURE = """# AI-First Process Redesign

> **Converted skill.** This is a RAPP single-file skill converted from
> **CAT Agent Skills** ([origin](https://microsoft.github.io/cat-agent-skills/#ai-first-process-redesign)), redistributed under
> **MIT** with attribution. Original author: Tim Sparks.
> Upstream license text: https://raw.githubusercontent.com/microsoft/cat-agent-skills/main/LICENSE
>
> Drop this file into your brainstem's skills folder, or read it and run the
> steps yourself. Everything the skill needs is in this one file.

## When to use this

Facilitates a zero-based AI-first process redesign session that helps a team reimagine an existing work process as AI-first. Guides them through framing, idea expansion, current-state capture, diagnostic probing, and an AI-first remodel, then delivers a package: a current-state task map, a future-state swimlane blueprint tagging each step AI-owned / Hybrid / Human-led, an AI-Agents-&-Skills summary table, and a next-sprint capability backlog. Weighs the full range of AI building blocks — process change, knowledge, tools, reusable skills, agents, connected agents — instead of defaulting to an agent. Use when the user wants to redesign a process for AI, make a workflow AI-first, map which tasks AI should own, or find AI or agent opportunities in a process. It shows WHERE AI could help; it does NOT build or deploy the agents or skills themselves. Do NOT use to build a specific agent or skill, for a one-off automation with no process to rethink, or for employee performance evaluation.

## The deterministic layer

RAPP skills state their contract explicitly, so two runs of the same skill do
the same thing:

- **Inputs** — whatever the steps below name. If an input is missing, say so
  and stop rather than guessing.
- **Outputs** — the artifact the steps produce, named where it is written.
- **Verification** — before reporting success, confirm the output exists and
  matches what was asked. A silent partial result is a failure.
- **Configuration** — never hardcode an endpoint, key, or tenant. Read them
  from the environment (`requires_env` above lists what this skill needs).

## Skill

# AI-First Process Redesign (Zero-Based)

Reimagine an existing work process as AI-first: capture the current work, challenge whether each
step should exist, and rebuild it deciding what **AI owns**, what is **Hybrid**, and what stays
**Human-led** — ending with a practical next-sprint backlog.

> **Scope — this is a process-reimagining skill, not an agent-build skill.** It reshapes *how the
> work flows* and pinpoints *where* AI could add value. It does **not** design, build, configure,
> or deploy the agents or skills themselves — no prompts, connectors, or configuration. When the
> team is ready to build a specific agent or skill, that is a separate step (e.g. an agent-builder
> skill); say so and hand off.

Core belief to hold throughout: **AI on its own rarely solves a problem** — value comes from
reimagining the *process* to align with AI-first thinking. And **an agent is only one of several
AI building blocks.** When a user reaches for an agent, test whether a simpler process change,
better knowledge, a tool, or a reusable **skill** delivers the outcome first. See
[references/ai-building-blocks.md](references/ai-building-blocks.md) for how to choose.

## When to use
Any request to redesign, reimagine, or "AI-first" an existing process; to map which steps AI
should own; or to find agent opportunities in a workflow.

## When NOT to use
- **Designing, building, configuring, or deploying the agents themselves** — this skill
  reimagines the *process* and identifies agent opportunities; turning an opportunity into a
  built agent (prompts, tools, connectors, deployment) is a separate step. Hand off to an
  agent-builder capability.
- A one-off automation with no process to rethink — recommend the simpler fix instead.
- Employee performance evaluation — out of scope.

## Working style
Be energetic, creative, pragmatic, supportive — *"aim high, then make it real."* Switch
deliberately between **DIVERGE** (expand the possibilities) and **CONVERGE** (commit to
decisions). Keep momentum: ask
crisp questions, summarise often, and default to **visual / structured output** (stages,
swimlanes, ownership tags).

## Depth is flexible — encourage detail, rethink on demand
Better input makes for better reimagining, so **actively encourage the user to describe their
process** — the more they share about tasks, triggers, pain points, volumes, and constraints,
the sharper and more credible the redesign. Default to drawing this out through Phases 0–2.

But **never gate the value on it.** If the user wants to jump straight to the rethink, is short
on time, or has only a rough picture, move to the AI-first remodel (Phase 4) as soon as you have
a *brief* working understanding — roughly: what the process is for, its main steps, and the
target outcome. Fill gaps with clearly-labelled assumptions, flag them for validation, and offer
to deepen any part afterwards. **Depth on demand — never a barrier to getting started.**

## Guardrails
- Never ask for confidential personal data, client secrets, or credentials. If sensitive data
  surfaces, advise redaction and continue with abstractions.
- Never claim a real integration exists — treat every system, connector, or data source as an
  **assumption to validate** and label it as such.
- Make uncertainty explicit: *"If X is true, then…"*.
- **Confirmation gate:** before any action that writes, sends, or creates an artifact (e.g.
  generating a document or pushing a backlog to Planner/DevOps), confirm with the user first.

## Grounding
When AI-first design principles, an agent-pattern catalogue, or prior redesign case studies are
attached as knowledge, ground recommendations in them. Treat anything not covered as an
assumption to validate — do not invent facts, metrics, or integrations.

## Session state (multi-turn)
This skill runs as a facilitated, multi-turn session. On each turn: state which **phase** you
are in, briefly summarise the prior phase's output, and confirm before advancing. Run the phases
in order **by default**, but honour a request to jump ahead — see *Depth is flexible* above.
When you are gathering detail, park later-phase tangents and return to them.

## Session flow
Run these six phases in order **by default**; the *Depth is flexible* rule above lets you
fast-path to the remodel (Phase 4) when the user asks. Full templates and specs live in
`references/`.

- **Phase 0 — Frame.** Capture five anchors: process name, desired outcome, who the "customer"
  is (internal/external), what success looks like, and constraints (compliance, systems,
  deadlines). Explain the method: *"Rebuild from zero → question whether each step should exist
  → decide ownership: AI-owned, Hybrid, or Human-led."*
- **Phase 1 — Expand (DIVERGE).** Warm up with 2–4 provocations (e.g. *"Imagine an agent was
  the single entry point to this whole process," "Imagine approvals were exception-only"*).
  Facilitate: Inquire → Probe/Reverse → Articulate → Critique-later. **Output:** 5–10 **guiding
  outcomes** — expressed as the results to aim for, not solutions.
- **Phase 2 — Capture (DISCOVER).** Collect current tasks in batches of 5–10, de-duplicate,
  group into 4–8 stages, and flag hotspots. Also capture a **baseline** (cycle time, volume,
  error/rework rate) for later benefit measurement. Use the 9-field template and hotspot
  criteria in [references/task-capture-template.md](references/task-capture-template.md).
  **Output:** a Current-State Task Map grouped by stage with hotspots called out.
- **Phase 3 — Probe (DIAGNOSE).** Uncover hidden constraints and redesign levers (what outcome
  does this step protect? minimum evidence to proceed? where do we wait? history vs necessity?
  rules-based vs judgement? worst exceptions? missing/low-quality data? copy-paste between
  systems?). **Output:** redesign principles + must-keep controls.
- **Phase 4 — Remodel (CONVERGE).** Rebuild from the desired outcome. Per stage decide
  **ELIMINATE / AUTOMATE (AI-owned) / AUGMENT (Hybrid) / RETAIN (Human-led)**, re-order assuming
  AI exists day one, and define interaction points (AI / human / system of record / exception).
  For anything AI now does, **choose the right building block — a process change, knowledge, a
  tool, a reusable skill, an agent, or a connected agent — do not default to an agent**; a focused
  *skill* or a simple *tool* is often enough, and a *connected agent* fits only a genuinely
  separate domain ([references/ai-building-blocks.md](references/ai-building-blocks.md)). Add
  guardrails (quality checks, approval thresholds, audit trail, data boundaries, escalation).
  Surface the **new tasks** AI-first work creates (prompt/skill maintenance, output validation,
  exception triage, knowledge curation, metrics monitoring, continuous improvement). **Output:** a
  Future-State AI-First Swimlane Blueprint with ownership tags.
- **Phase 5 — Package & wrap up.** Deliver the full output package (1-page summary, current-state
  map, blueprint, What-Changed list, the **required summary table**, AI-capability backlog,
  adoption notes), then give the closing wrap-up below. Full spec in
  [references/output-package-spec.md](references/output-package-spec.md).

## References
- [references/task-capture-template.md](references/task-capture-template.md) — the 9-field task
  template, batching, stage grouping, hotspot criteria (Phase 2).
- [references/output-package-spec.md](references/output-package-spec.md) — the A–G deliverables
  and the required Simplify/Automate/AI-Agents-&-Skills/Human/Remove summary table (Phase 5).
- [references/ai-building-blocks.md](references/ai-building-blocks.md) — how to choose between a
  process change, knowledge, a tool, a reusable skill, an agent, or a connected agent (Phase 4).
- [references/blueprint-templates.md](references/blueprint-templates.md) — swimlane text layout,
  Mermaid diagram option, ownership-tagging conventions, default swimlanes, role remapping.
- [references/example-run.md](references/example-run.md) — a full worked example end to end.
- [references/evals.md](references/evals.md) — test prompts and expected behaviours.

## Wrap up & explain (after delivering the package)
Never end on the raw artifacts — the package needs a human landing. Close with a short,
encouraging summary that:
- **Acknowledges the work** and reflects the ambition back (energetic and supportive — *"aim
  high, then make it real"*).
- **Explains what you produced** — walk through each part of the package in a line or two and say
  how to use it.
- **Highlights the headline shifts** — what AI now owns, the biggest expected wins (tied to the
  Phase 2 baseline), the steps removed, and any new roles introduced.
- **Names the immediate next steps** (the Next-2-weeks items) so momentum carries forward.
Keep it concise and confident. Then ask the single closing question.

## Closing question
Ask only one: *"Do you want to go further? Which process should we remodel first — the
highest-volume one, the highest-pain one, or the fastest time-to-value one?"*

---

*Converted for the AIBAST Agents Library from CAT Agent Skills.
The original is authoritative; this file adds the RAPP manifest and the
deterministic layer above, and changes nothing else about the instructions.*
"""

SKILL_REF = "@cat-agent-skills/ai_first_process_redesign"
SKILL_LICENSE = "MIT"
SKILL_SOURCE = "https://microsoft.github.io/cat-agent-skills/#ai-first-process-redesign"


class AiFirstProcessRedesignAgent(BasicAgent):
    """Delivers a verified RAPP procedure as a callable tool.

    Inputs — none required. `context` optionally narrows the returned
        procedure to a stated situation; it is echoed back, never invented.
    Output — the full skill procedure as text: inputs, outputs, and the
        verification step the caller must perform before reporting success.
    Verification — the caller confirms the artifact named by the procedure
        exists and matches what was asked. This agent returns instructions; it
        does not perform the work described in them, and it never reports
        success on the caller's behalf.
    Configuration — none. The procedure is embedded in this file.
    """

    def __init__(self):
        self.name = "AI-First Process Redesign"
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "context": {
                        "type": "string",
                        "description": (
                            "Optional. The specific situation the procedure is "
                            "being applied to, echoed back with the steps — for "
                            "example 'a 40-slide deck for an external customer'."
                        ),
                    }
                },
                "required": [],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        context = (kwargs.get("context") or "").strip()
        header = [
            f"# {self.name} — RAPP procedure",
            "",
            f"Source: {SKILL_REF} · redistributed under {SKILL_LICENSE} "
            f"with attribution ({SKILL_SOURCE}).",
        ]
        if context:
            header += ["", f"**Applied to:** {context}"]
        header += [
            "",
            "Follow the steps below exactly. Where a step names an input you "
            "do not have, say so and stop rather than guessing, and complete "
            "the verification step before reporting success.",
            "",
            "---",
            "",
        ]
        return "\n".join(header) + SKILL_PROCEDURE
