"""
Campaign Deck Builder — RAPP agent, mirrored from campaign_deck_builder.md

This file is GENERATED from its skill.md by scripts/export_agent.py and is one
half of a matched pair. The manifest below and the procedure embedded further
down are identical to the ones in the .md; the only difference is the runtime:
a model reads the .md, a brainstem registers this .py and calls it as a tool.

Do not edit this file. Edit campaign_deck_builder.md and re-run the exporter — the gate
re-derives this file and fails if the two have drifted apart.

Redistributed from CAT Agent Skills under MIT
with attribution. Original author: Adi Leibowitz.
Origin: https://microsoft.github.io/cat-agent-skills/#campaign-deck-builder
"""

# ===============================================================
# RAPP AGENT MANIFEST - Do not remove. Used by registry builder.
# ===============================================================
__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@cat-agent-skills/campaign_deck_builder",
    "version": "1.0.0",
    "display_name": "Campaign Deck Builder",
    "description": "Returns the verified RAPP procedure for: Turn a short interview into a charming, vibrant 3-slide marketing-campaign deck by filling a bundled PowerPoint template. Call this to obtain the full step-by-step contract (inputs, outputs, verification) and then carry out those steps.",
    "author": "Adi Leibowitz",
    "tags": [
        "marketing",
        "presentations",
        "powerpoint",
        "automation",
        "scripts"
    ],
    "category": "general",
    "quality_tier": "aggregated",
    "requires_env": [],
    "dependencies": [
        "@rapp/basic-agent"
    ],
    "mirrors": "campaign_deck_builder.md",
    "source_url": "https://microsoft.github.io/cat-agent-skills/#campaign-deck-builder",
    "source_license": "MIT",
    "converted_from": "CAT Agent Skills"
}
# ===============================================================

try:  # cloud layout (agents package)
    from agents.basic_agent import BasicAgent
except ImportError:  # local brainstem / standalone layout
    import os
    import sys

    sys.path.insert(0, os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "..",
        "agents", "@aibast-agents-library", "templates"))
    from basic_agent import BasicAgent


# The skill body, embedded verbatim. This is what makes the export single-file:
# the procedure travels with the agent rather than being fetched at call time.
SKILL_PROCEDURE = """# Campaign Deck Builder

> **Converted skill.** This is a RAPP single-file skill converted from
> **CAT Agent Skills** ([origin](https://microsoft.github.io/cat-agent-skills/#campaign-deck-builder)), redistributed under
> **MIT** with attribution. Original author: Adi Leibowitz.
> Upstream license text: https://raw.githubusercontent.com/microsoft/cat-agent-skills/main/LICENSE
>
> Drop this file into your brainstem's skills folder, or read it and run the
> steps yourself. Everything the skill needs is in this one file.

## When to use this

Use this skill whenever the user wants to create a marketing-campaign presentation, pitch deck, or launch deck for a brand. Ask the campaign questions, then run the bundled script to fill the template into a finished .pptx.

## The deterministic layer

RAPP skills state their contract explicitly, so two runs of the same skill do
the same thing:

- **Inputs** — whatever the steps below name. If an input is missing, say so
  and stop rather than guessing.
- **Outputs** — the artifact the steps produce, named where it is written.
- **Verification** — before reporting success, confirm the output exists and
  matches what was asked. A silent partial result is a failure.
- **Configuration** — never hardcode an endpoint, key, or tenant. Read them
  from the environment (`requires_env` above lists what this skill needs).

## Skill

Turn a short interview into a charming, vibrant, highly visual **3-slide
new-marketing-campaign deck** by filling a bundled PowerPoint template with a
bundled Python script.

## Step 1 — Interview the user
Ask for these (accept short answers; anything they skip gets a tasteful
default). Ask them in a single, friendly batch:

1. **Brand name**
2. **Campaign name** (the headline of the launch)
3. **Tagline** — one line that makes people lean in
4. **Target audience** — who it's for
5. **The big idea** — the single concept the campaign turns on (one sentence)
6. **Three key messages / benefits** (exactly three)
7. **Channels / activation** — where it runs (e.g. TikTok, out-of-home, retail)
8. **Call to action** — the ask
9. **Closing line** — the sign-off
10. **Brand accent color** (optional, `#RRGGBB`) — themes the whole deck

## Step 2 — Write the answers file
Save the answers as JSON. All keys are optional; `messages` is a list of three.

```json
{
  "brand_name": "Vela",
  "campaign_name": "Taste the Quiet",
  "tagline": "Botanical sparkling water for your loudest days.",
  "audience": "calm-seeking millennials",
  "big_idea": "A moment of quiet in every can.",
  "messages": ["Zero sugar, all serenity", "Adaptogens that work", "Guilt-free fizz"],
  "channels": "TikTok  ·  Out-of-home  ·  Sampling",
  "cta": "Pop the quiet.",
  "closing": "Vela — find your fizz.",
  "accent_hex": "#00A6A6"
}
```

See `assets/answers.example.json` for a complete example.

## Step 3 — Build the deck
Run the bundled script to produce the finished presentation:

```bash
python scripts/build_campaign.py answers.json campaign-deck.pptx
```

It fills `assets/campaign-template.pptx` — replacing every `{{PLACEHOLDER}}`
while preserving the design, rendering the three key messages as visual cards,
and recoloring the deck to the brand accent color when one is given. Missing
answers fall back to sensible defaults, so it always produces a complete
3-slide deck. Hand the resulting `campaign-deck.pptx` back to the user.

## Bundled files
The attached `.zip` includes:
- `scripts/build_campaign.py` — fills the template from a JSON answers file.
  Run it as `python scripts/build_campaign.py <answers.json> [output.pptx]`.
- `assets/campaign-template.pptx` — the 3-slide, highly visual template with
  `{{PLACEHOLDER}}` tokens.
- `assets/answers.example.json` — a complete sample brand you can copy and edit.
- `references/design-notes.md` — the slide/placeholder map and theming notes.

Requires `python-pptx` (`pip install python-pptx`).

## Tone
Bold, upbeat, and brand-forward. The deck should feel like a launch, not a memo.
Keep copy punchy — headlines over paragraphs.

---

*Converted for the AIBAST Agents Library from CAT Agent Skills.
The original is authoritative; this file adds the RAPP manifest and the
deterministic layer above, and changes nothing else about the instructions.*
"""

SKILL_REF = "@cat-agent-skills/campaign_deck_builder"
SKILL_LICENSE = "MIT"
SKILL_SOURCE = "https://microsoft.github.io/cat-agent-skills/#campaign-deck-builder"


class CampaignDeckBuilderAgent(BasicAgent):
    """Delivers a verified RAPP procedure as a callable tool.

    Inputs — none required. `context` optionally narrows the returned
        procedure to a stated situation; it is echoed back, never invented.
    Output — the full skill procedure as text: inputs, outputs, and the
        verification step the caller must perform before reporting success.
    Verification — the caller confirms the artifact named by the procedure
        exists and matches what was asked. This agent returns instructions; it
        does not perform the work described in them, and it never reports
        success on the caller's behalf.
    Configuration — none. The procedure is embedded in this file.
    """

    def __init__(self):
        self.name = "Campaign Deck Builder"
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "context": {
                        "type": "string",
                        "description": (
                            "Optional. The specific situation the procedure is "
                            "being applied to, echoed back with the steps — for "
                            "example 'a 40-slide deck for an external customer'."
                        ),
                    }
                },
                "required": [],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        context = (kwargs.get("context") or "").strip()
        header = [
            f"# {self.name} — RAPP procedure",
            "",
            f"Source: {SKILL_REF} · redistributed under {SKILL_LICENSE} "
            f"with attribution ({SKILL_SOURCE}).",
        ]
        if context:
            header += ["", f"**Applied to:** {context}"]
        header += [
            "",
            "Follow the steps below exactly. Where a step names an input you "
            "do not have, say so and stop rather than guessing, and complete "
            "the verification step before reporting success.",
            "",
            "---",
            "",
        ]
        return "\n".join(header) + SKILL_PROCEDURE
