"""
Commenting Content — RAPP agent, mirrored from commenting_content.md

This file is GENERATED from its skill.md by scripts/export_agent.py and is one
half of a matched pair. The manifest below and the procedure embedded further
down are identical to the ones in the .md; the only difference is the runtime:
a model reads the .md, a brainstem registers this .py and calls it as a tool.

Do not edit this file. Edit commenting_content.md and re-run the exporter — the gate
re-derives this file and fails if the two have drifted apart.

Redistributed from CAT Agent Skills under MIT
with attribution. Original author: AndrewHessMSFT.
Origin: https://microsoft.github.io/cat-agent-skills/#commenting-content
"""

# ===============================================================
# RAPP AGENT MANIFEST - Do not remove. Used by registry builder.
# ===============================================================
__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@cat-agent-skills/commenting_content",
    "version": "1.0.0",
    "display_name": "Commenting Content",
    "description": "Returns the verified RAPP procedure for: Comments Word or PowerPoint files with Comments. Call this to obtain the full step-by-step contract (inputs, outputs, verification) and then carry out those steps.",
    "author": "AndrewHessMSFT",
    "tags": [
        "documents",
        "productivity"
    ],
    "category": "general",
    "quality_tier": "aggregated",
    "requires_env": [],
    "dependencies": [
        "@rapp/basic-agent"
    ],
    "mirrors": "commenting_content.md",
    "source_url": "https://microsoft.github.io/cat-agent-skills/#commenting-content",
    "source_license": "MIT",
    "converted_from": "CAT Agent Skills"
}
# ===============================================================

try:  # cloud layout (agents package)
    from agents.basic_agent import BasicAgent
except ImportError:  # local brainstem / standalone layout
    import os
    import sys

    sys.path.insert(0, os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "..",
        "agents", "@aibast-agents-library", "templates"))
    from basic_agent import BasicAgent


# The skill body, embedded verbatim. This is what makes the export single-file:
# the procedure travels with the agent rather than being fetched at call time.
SKILL_PROCEDURE = """# Commenting Content

> **Converted skill.** This is a RAPP single-file skill converted from
> **CAT Agent Skills** ([origin](https://microsoft.github.io/cat-agent-skills/#commenting-content)), redistributed under
> **MIT** with attribution. Original author: AndrewHessMSFT.
> Upstream license text: https://raw.githubusercontent.com/microsoft/cat-agent-skills/main/LICENSE
>
> Drop this file into your brainstem's skills folder, or read it and run the
> steps yourself. Everything the skill needs is in this one file.

## When to use this

Analyzes a .docx or .pptx file, researches the topic using internal documents, emails, Microsoft Teams messages, and web sources, then adds native comments throughout the file authored by \\"Copilot Studio AI\\" — without modifying the original content.

## The deterministic layer

RAPP skills state their contract explicitly, so two runs of the same skill do
the same thing:

- **Inputs** — whatever the steps below name. If an input is missing, say so
  and stop rather than guessing.
- **Outputs** — the artifact the steps produce, named where it is written.
- **Verification** — before reporting success, confirm the output exists and
  matches what was asked. A silent partial result is a failure.
- **Configuration** — never hardcode an endpoint, key, or tenant. Read them
  from the environment (`requires_env` above lists what this skill needs).

## Skill

# Comment Content

When this skill is activated:

1. Check the file extension of the attached document.
   - If `.docx` → follow the instructions in `REFERENCE-DOCX.md`
   - If `.pptx` → follow the instructions in `REFERENCE-PPTX.md`
   - If any other format → ask the user to convert to `.docx` or `.pptx` first.
2. Execute the full commenting workflow defined in the appropriate reference file.
3. Return the updated file with native comments embedded and a short chat summary of findings.

## Guidelines

- Never modify the original document content — add comments only.
- Set the comment author to `Copilot Studio AI` on every comment added.
- Research using any available sources: internal documents, emails, Microsoft Teams messages, approved knowledge sources, and web research tools.
- Only comment where it genuinely helps — do not comment on every sentence.
- The chat summary must include: comment count, main research findings, and top 1–3 priority issues for the author to review.

## Reference Files

- [`REFERENCE-DOCX.md`](./REFERENCE-DOCX.md) — Word document commenting instructions
- [`REFERENCE-PPTX.md`](./REFERENCE-PPTX.md) — PowerPoint presentation commenting instructions

## Examples

**Example 1: Word document**
- User request: "Add research comments to this report." (attaches report.docx)
- Expected behavior: Detect .docx, follow REFERENCE-DOCX.md, return commented .docx with summary.

**Example 2: PowerPoint presentation**
- User request: "Review this deck and add comments." (attaches deck.pptx)
- Expected behavior: Detect .pptx, follow REFERENCE-PPTX.md, return commented .pptx with summary.

## Notes

- If multiple files are attached, process them one at a time and produce a separate summary for each.
- If the file type is ambiguous, ask the user to confirm before proceeding.

---

*Converted for the AIBAST Agents Library from CAT Agent Skills.
The original is authoritative; this file adds the RAPP manifest and the
deterministic layer above, and changes nothing else about the instructions.*
"""

SKILL_REF = "@cat-agent-skills/commenting_content"
SKILL_LICENSE = "MIT"
SKILL_SOURCE = "https://microsoft.github.io/cat-agent-skills/#commenting-content"


class CommentingContentAgent(BasicAgent):
    """Delivers a verified RAPP procedure as a callable tool.

    Inputs — none required. `context` optionally narrows the returned
        procedure to a stated situation; it is echoed back, never invented.
    Output — the full skill procedure as text: inputs, outputs, and the
        verification step the caller must perform before reporting success.
    Verification — the caller confirms the artifact named by the procedure
        exists and matches what was asked. This agent returns instructions; it
        does not perform the work described in them, and it never reports
        success on the caller's behalf.
    Configuration — none. The procedure is embedded in this file.
    """

    def __init__(self):
        self.name = "Commenting Content"
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "context": {
                        "type": "string",
                        "description": (
                            "Optional. The specific situation the procedure is "
                            "being applied to, echoed back with the steps — for "
                            "example 'a 40-slide deck for an external customer'."
                        ),
                    }
                },
                "required": [],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        context = (kwargs.get("context") or "").strip()
        header = [
            f"# {self.name} — RAPP procedure",
            "",
            f"Source: {SKILL_REF} · redistributed under {SKILL_LICENSE} "
            f"with attribution ({SKILL_SOURCE}).",
        ]
        if context:
            header += ["", f"**Applied to:** {context}"]
        header += [
            "",
            "Follow the steps below exactly. Where a step names an input you "
            "do not have, say so and stop rather than guessing, and complete "
            "the verification step before reporting success.",
            "",
            "---",
            "",
        ]
        return "\n".join(header) + SKILL_PROCEDURE
