"""
Copilot Studio Topic Blueprint — RAPP agent, mirrored from copilot_studio_topic_blueprint.md

This file is GENERATED from its skill.md by scripts/export_agent.py and is one
half of a matched pair. The manifest below and the procedure embedded further
down are identical to the ones in the .md; the only difference is the runtime:
a model reads the .md, a brainstem registers this .py and calls it as a tool.

Do not edit this file. Edit copilot_studio_topic_blueprint.md and re-run the exporter — the gate
re-derives this file and fails if the two have drifted apart.

Redistributed from CAT Agent Skills under MIT
with attribution. Original author: Elliot Margot.
Origin: https://microsoft.github.io/cat-agent-skills/#copilot-studio-topic-blueprint
"""

# ===============================================================
# RAPP AGENT MANIFEST - Do not remove. Used by registry builder.
# ===============================================================
__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@cat-agent-skills/copilot_studio_topic_blueprint",
    "version": "1.0.0",
    "display_name": "Copilot Studio Topic Blueprint",
    "description": "Returns the verified RAPP procedure for: Turn a one-line use case into a build-ready Microsoft Copilot Studio agent blueprint: recommended agent type and orchestration, topics, tools, knowledge, variables, a welcome Adaptive Card, security and Copilot Credits notes, and a first test plan. Call this to obtain the full step-by-step contract (inputs, outputs, verification) and then carry out those steps.",
    "author": "Elliot Margot",
    "tags": [
        "agent",
        "blueprint",
        "topics",
        "design",
        "power-platform",
        "orchestration",
        "adaptive-card"
    ],
    "category": "general",
    "quality_tier": "aggregated",
    "requires_env": [],
    "dependencies": [
        "@rapp/basic-agent"
    ],
    "mirrors": "copilot_studio_topic_blueprint.md",
    "source_url": "https://microsoft.github.io/cat-agent-skills/#copilot-studio-topic-blueprint",
    "source_license": "MIT",
    "converted_from": "CAT Agent Skills"
}
# ===============================================================

try:  # cloud layout (agents package)
    from agents.basic_agent import BasicAgent
except ImportError:  # local brainstem / standalone layout
    import os
    import sys

    sys.path.insert(0, os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "..",
        "agents", "@aibast-agents-library", "templates"))
    from basic_agent import BasicAgent


# The skill body, embedded verbatim. This is what makes the export single-file:
# the procedure travels with the agent rather than being fetched at call time.
SKILL_PROCEDURE = """# Copilot Studio Topic Blueprint

> **Converted skill.** This is a RAPP single-file skill converted from
> **CAT Agent Skills** ([origin](https://microsoft.github.io/cat-agent-skills/#copilot-studio-topic-blueprint)), redistributed under
> **MIT** with attribution. Original author: Elliot Margot.
> Upstream license text: https://raw.githubusercontent.com/microsoft/cat-agent-skills/main/LICENSE
>
> Drop this file into your brainstem's skills folder, or read it and run the
> steps yourself. Everything the skill needs is in this one file.

## When to use this

Use this skill whenever the user describes a Copilot Studio agent in a sentence or two and wants a build-ready blueprint, or asks how to design, scope, or structure an agent (its type, topics, tools, knowledge, or welcome experience). Trigger on requests like \\"design a Copilot Studio agent that…\\", \\"turn this use case into an agent\\", \\"how should I structure this agent\\", or a pasted one-line use case. Do NOT trigger for testing an existing agent (that is the test-planner skill) or for generic Power Platform flows unrelated to an agent.

## The deterministic layer

RAPP skills state their contract explicitly, so two runs of the same skill do
the same thing:

- **Inputs** — whatever the steps below name. If an input is missing, say so
  and stop rather than guessing.
- **Outputs** — the artifact the steps produce, named where it is written.
- **Verification** — before reporting success, confirm the output exists and
  matches what was asked. A silent partial result is a failure.
- **Configuration** — never hardcode an endpoint, key, or tenant. Read them
  from the environment (`requires_env` above lists what this skill needs).

## Skill

Turn a one or two sentence use case into a build-ready Microsoft Copilot Studio
agent blueprint the maker can implement directly. You design and specify; you do
not build in the maker's tenant.

## Instructions

1. **Capture the use case.** If the user gave a one-line description, use it. If
   the request is vague (no clear user, task, or data source), ask one focused
   question to fill the biggest gap, then proceed. Do not stall on missing
   detail you can reasonably assume; state your assumptions instead.

2. **Produce the blueprint in exactly these eight sections, in order:**

   1. **Recommendation.** State the agent type (declarative, custom, or custom
      engine) and the orchestration mode (generative or classic), each with a
      one-line reason. Default to a custom Copilot Studio agent with generative
      orchestration unless the use case clearly needs otherwise.
   2. **Topics.** List 3 to 7 topics. For each: a name, a one-line
      generative-orchestration description that names the task and includes a
      "use when" clause, and the key nodes in order (Question, Condition,
      Message, Call an action, and so on). Note any input the topic must collect.
   3. **Tools and actions.** List the tools, connectors, or Power Automate flows
      the agent needs. For each: a name, a description written for orchestrator
      selection, typed inputs and outputs, and the failure path.
   4. **Knowledge.** List the knowledge sources to attach and the scope of each.
      Note when knowledge should answer versus when a topic or tool should.
   5. **Variables.** List the global variables the agent needs, with type and
      purpose.
   6. **Welcome experience.** Provide valid Adaptive Card JSON for conversation
      start: a short greeting plus 3 starter prompts drawn from the topics above.
   7. **Security and cost.** State the authentication mode (None, Microsoft
      Entra, or generic OAuth 2.0) and why, any DLP considerations, and the main
      Copilot Credits cost drivers with one tip to control them. Use Copilot
      Credits terminology, not "messages".
   8. **First test plan.** Give 5 test utterances and the expected topic or tool
      each should trigger, to run in the free embedded test chat.

3. **Keep it build-ready.** Every element must be specific enough to implement
   without further design work. Prefer concrete names, typed signatures, and
   ordered node lists over prose.

## Guardrails

- Do not invent product features, menu paths, connector names, or limits. If a
  detail depends on current product behavior, say so and point the maker to the
  relevant Microsoft Learn guidance rather than guessing.
- Do not fabricate the maker's data sources, systems, or volumes. Use only what
  the use case states, and mark anything you assumed.
- Return the Adaptive Card as valid JSON that a maker can paste as-is.
- Do not use the em dash character. Use a hyphen or rewrite.

## Tone

Specific, concise, and build-ready. Address the maker directly. Explain a choice
in one line, then move on. No filler, no restating the use case back at length.

---

*Converted for the AIBAST Agents Library from CAT Agent Skills.
The original is authoritative; this file adds the RAPP manifest and the
deterministic layer above, and changes nothing else about the instructions.*
"""

SKILL_REF = "@cat-agent-skills/copilot_studio_topic_blueprint"
SKILL_LICENSE = "MIT"
SKILL_SOURCE = "https://microsoft.github.io/cat-agent-skills/#copilot-studio-topic-blueprint"


class CopilotStudioTopicBlueprintAgent(BasicAgent):
    """Delivers a verified RAPP procedure as a callable tool.

    Inputs — none required. `context` optionally narrows the returned
        procedure to a stated situation; it is echoed back, never invented.
    Output — the full skill procedure as text: inputs, outputs, and the
        verification step the caller must perform before reporting success.
    Verification — the caller confirms the artifact named by the procedure
        exists and matches what was asked. This agent returns instructions; it
        does not perform the work described in them, and it never reports
        success on the caller's behalf.
    Configuration — none. The procedure is embedded in this file.
    """

    def __init__(self):
        self.name = "Copilot Studio Topic Blueprint"
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "context": {
                        "type": "string",
                        "description": (
                            "Optional. The specific situation the procedure is "
                            "being applied to, echoed back with the steps — for "
                            "example 'a 40-slide deck for an external customer'."
                        ),
                    }
                },
                "required": [],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        context = (kwargs.get("context") or "").strip()
        header = [
            f"# {self.name} — RAPP procedure",
            "",
            f"Source: {SKILL_REF} · redistributed under {SKILL_LICENSE} "
            f"with attribution ({SKILL_SOURCE}).",
        ]
        if context:
            header += ["", f"**Applied to:** {context}"]
        header += [
            "",
            "Follow the steps below exactly. Where a step names an input you "
            "do not have, say so and stop rather than guessing, and complete "
            "the verification step before reporting success.",
            "",
            "---",
            "",
        ]
        return "\n".join(header) + SKILL_PROCEDURE
