"""
Copilot & Agents News Scout — RAPP agent, mirrored from copilot_agents_news_scout.md

This file is GENERATED from its skill.md by scripts/export_agent.py and is one
half of a matched pair. The manifest below and the procedure embedded further
down are identical to the ones in the .md; the only difference is the runtime:
a model reads the .md, a brainstem registers this .py and calls it as a tool.

Do not edit this file. Edit copilot_agents_news_scout.md and re-run the exporter — the gate
re-derives this file and fails if the two have drifted apart.

Redistributed from CAT Agent Skills under MIT
with attribution. Original author: Elliot Margot.
Origin: https://microsoft.github.io/cat-agent-skills/#copilot-agents-news-scout
"""

# ===============================================================
# RAPP AGENT MANIFEST - Do not remove. Used by registry builder.
# ===============================================================
__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@cat-agent-skills/copilot_agents_news_scout",
    "version": "1.0.0",
    "display_name": "Copilot & Agents News Scout",
    "description": "Returns the verified RAPP procedure for: A Monday-morning Scout automation that scans authoritative Microsoft sources for the past week's Copilot, Copilot Studio, and agent news and posts a concise, linked digest to Teams. Call this to obtain the full step-by-step contract (inputs, outputs, verification) and then carry out those steps.",
    "author": "Elliot Margot",
    "tags": [
        "news",
        "copilot",
        "agent",
        "digest",
        "automation",
        "weekly",
        "teams"
    ],
    "category": "it_management",
    "quality_tier": "aggregated",
    "requires_env": [],
    "dependencies": [
        "@rapp/basic-agent"
    ],
    "mirrors": "copilot_agents_news_scout.md",
    "source_url": "https://microsoft.github.io/cat-agent-skills/#copilot-agents-news-scout",
    "source_license": "MIT",
    "converted_from": "CAT Agent Skills"
}
# ===============================================================

try:  # cloud layout (agents package)
    from agents.basic_agent import BasicAgent
except ImportError:  # local brainstem / standalone layout
    import os
    import sys

    sys.path.insert(0, os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "..",
        "agents", "@aibast-agents-library", "templates"))
    from basic_agent import BasicAgent


# The skill body, embedded verbatim. This is what makes the export single-file:
# the procedure travels with the agent rather than being fetched at call time.
SKILL_PROCEDURE = """# Copilot & Agents News Scout

> **Converted skill.** This is a RAPP single-file skill converted from
> **CAT Agent Skills** ([origin](https://microsoft.github.io/cat-agent-skills/#copilot-agents-news-scout)), redistributed under
> **MIT** with attribution. Original author: Elliot Margot.
> Upstream license text: https://raw.githubusercontent.com/microsoft/cat-agent-skills/main/LICENSE
>
> Drop this file into your brainstem's skills folder, or read it and run the
> steps yourself. Everything the skill needs is in this one file.

## When to use this

A Monday-morning Scout automation that scans authoritative Microsoft sources for the past week's Copilot, Copilot Studio, and agent news and posts a concise, linked digest to Teams.

## The deterministic layer

RAPP skills state their contract explicitly, so two runs of the same skill do
the same thing:

- **Inputs** — whatever the steps below name. If an input is missing, say so
  and stop rather than guessing.
- **Outputs** — the artifact the steps produce, named where it is written.
- **Verification** — before reporting success, confirm the output exists and
  matches what was asked. A silent partial result is a failure.
- **Configuration** — never hardcode an endpoint, key, or tenant. Read them
  from the environment (`requires_env` above lists what this skill needs).

## Skill

A Monday-morning Scout automation that scans authoritative Microsoft sources for the past week's Copilot, Copilot Studio, and agent news and posts a concise, linked digest to Teams.

> **Scout automation.** This is a Microsoft **Scout** automation (a `.json` of a schedule plus ordered prompt steps). It runs on Scout only.

## Trigger

Runs on a **schedule** — every Monday at 8:00 AM.

## Steps

### 1. Gather the week's updates

```text
Search authoritative Microsoft sources published or updated in the last 7 days for news about Microsoft 365 Copilot, Copilot Studio, Copilot agents, and Microsoft Scout. Prioritize: the Microsoft 365 and Copilot blogs (microsoft.com/blog), Microsoft Learn 'what's new' and release pages, the Message Center and Microsoft 365 roadmap, and the Power Platform / Copilot Studio release plans. For each item, capture the title, the canonical URL, the publish or update date, and a one-sentence summary in your own words. Collect everything relevant now; do not filter yet.
```

### 2. Filter to what matters

```text
From the items gathered, keep only material changes a Copilot Studio maker or M365 admin would act on: general availability, public preview, deprecations and breaking changes, pricing or Copilot Credits changes, new connectors or capabilities, and roadmap dates. Drop marketing recaps, opinion pieces, and anything older than 7 days. Deduplicate items that cover the same announcement, keeping the most authoritative source. If nothing material shipped this week, note that plainly rather than padding the list.
```

### 3. Write and post the Teams digest

```text
Write a concise digest titled 'Copilot & Agents - week of <date>'. Group items under headings: Microsoft 365 Copilot, Copilot Studio, Agents & Scout, and Governance & Admin (omit any empty group). For each item give the title as a link, the date, and a one-line 'why it matters'. Keep the whole digest scannable in under two minutes. Post it to Teams. Do not invent items, dates, or links; include only what the previous step verified. Do not use the em dash character.
```

## Import into Scout

1. Download the automation (the `.json` on this page).
2. In **Scout › Automations**, choose **Import** and select the file (or paste its contents). Review the schedule and steps, then enable it.

You can also point Scout's **Import from GitHub** at a repository directory of automation `.json` files (a `skills/` subfolder is installed automatically). This automation's file is `submissions/copilot-agents-news-scout/` in this repo.

> Review the steps before enabling — automations act on your behalf on a schedule.

---

*Converted for the AIBAST Agents Library from CAT Agent Skills.
The original is authoritative; this file adds the RAPP manifest and the
deterministic layer above, and changes nothing else about the instructions.*
"""

SKILL_REF = "@cat-agent-skills/copilot_agents_news_scout"
SKILL_LICENSE = "MIT"
SKILL_SOURCE = "https://microsoft.github.io/cat-agent-skills/#copilot-agents-news-scout"


class CopilotAgentsNewsScoutAgent(BasicAgent):
    """Delivers a verified RAPP procedure as a callable tool.

    Inputs — none required. `context` optionally narrows the returned
        procedure to a stated situation; it is echoed back, never invented.
    Output — the full skill procedure as text: inputs, outputs, and the
        verification step the caller must perform before reporting success.
    Verification — the caller confirms the artifact named by the procedure
        exists and matches what was asked. This agent returns instructions; it
        does not perform the work described in them, and it never reports
        success on the caller's behalf.
    Configuration — none. The procedure is embedded in this file.
    """

    def __init__(self):
        self.name = "Copilot & Agents News Scout"
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "context": {
                        "type": "string",
                        "description": (
                            "Optional. The specific situation the procedure is "
                            "being applied to, echoed back with the steps — for "
                            "example 'a 40-slide deck for an external customer'."
                        ),
                    }
                },
                "required": [],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        context = (kwargs.get("context") or "").strip()
        header = [
            f"# {self.name} — RAPP procedure",
            "",
            f"Source: {SKILL_REF} · redistributed under {SKILL_LICENSE} "
            f"with attribution ({SKILL_SOURCE}).",
        ]
        if context:
            header += ["", f"**Applied to:** {context}"]
        header += [
            "",
            "Follow the steps below exactly. Where a step names an input you "
            "do not have, say so and stop rather than guessing, and complete "
            "the verification step before reporting success.",
            "",
            "---",
            "",
        ]
        return "\n".join(header) + SKILL_PROCEDURE
