"""
Iterative File Editing — RAPP agent, mirrored from iterative_file_editing.md

This file is GENERATED from its skill.md by scripts/export_agent.py and is one
half of a matched pair. The manifest below and the procedure embedded further
down are identical to the ones in the .md; the only difference is the runtime:
a model reads the .md, a brainstem registers this .py and calls it as a tool.

Do not edit this file. Edit iterative_file_editing.md and re-run the exporter — the gate
re-derives this file and fails if the two have drifted apart.

Redistributed from CAT Agent Skills under MIT
with attribution. Original author: Adi Leibowitz.
Origin: https://microsoft.github.io/cat-agent-skills/#iterative-file-editing
"""

# ===============================================================
# RAPP AGENT MANIFEST - Do not remove. Used by registry builder.
# ===============================================================
__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@cat-agent-skills/iterative_file_editing",
    "version": "1.0.0",
    "display_name": "Iterative File Editing",
    "description": "Returns the verified RAPP procedure for: In Copilot Studio, re-sending an edited file under the same name fails to deliver it \\u2014 the change is made but never reaches the user. This skill gives each iteration a new version-numbered filename (report_v1.docx, report_v2.docx\\u2026) so every update actually lands in the chat as its own attachment. Call this to obtain the full step-by-step contract (inputs, outputs, verification) and then carry out those steps.",
    "author": "Adi Leibowitz",
    "tags": [
        "files",
        "iteration",
        "workflow",
        "collaboration",
        "productivity"
    ],
    "category": "general",
    "quality_tier": "aggregated",
    "requires_env": [],
    "dependencies": [
        "@rapp/basic-agent"
    ],
    "mirrors": "iterative_file_editing.md",
    "source_url": "https://microsoft.github.io/cat-agent-skills/#iterative-file-editing",
    "source_license": "MIT",
    "converted_from": "CAT Agent Skills"
}
# ===============================================================

try:  # cloud layout (agents package)
    from agents.basic_agent import BasicAgent
except ImportError:  # local brainstem / standalone layout
    import os
    import sys

    sys.path.insert(0, os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "..",
        "agents", "@aibast-agents-library", "templates"))
    from basic_agent import BasicAgent


# The skill body, embedded verbatim. This is what makes the export single-file:
# the procedure travels with the agent rather than being fetched at call time.
SKILL_PROCEDURE = """# Iterative File Editing

> **Converted skill.** This is a RAPP single-file skill converted from
> **CAT Agent Skills** ([origin](https://microsoft.github.io/cat-agent-skills/#iterative-file-editing)), redistributed under
> **MIT** with attribution. Original author: Adi Leibowitz.
> Upstream license text: https://raw.githubusercontent.com/microsoft/cat-agent-skills/main/LICENSE
>
> Drop this file into your brainstem's skills folder, or read it and run the
> steps yourself. Everything the skill needs is in this one file.

## When to use this

Use this skill whenever you create or edit ANY file for the user in the Copilot Studio container — a document, spreadsheet, slide deck, code file, data export, anything. It keeps your work-in-progress durable and shows the user an updated version after every change, so the two of you refine the same file together across turns — the user sees real progress each round, earlier work is never lost, and neither of you has to start over. Apply it from the very first file you make.

## The deterministic layer

RAPP skills state their contract explicitly, so two runs of the same skill do
the same thing:

- **Inputs** — whatever the steps below name. If an input is missing, say so
  and stop rather than guessing.
- **Outputs** — the artifact the steps produce, named where it is written.
- **Verification** — before reporting success, confirm the output exists and
  matches what was asked. A silent partial result is a failure.
- **Configuration** — never hardcode an endpoint, key, or tenant. Read them
  from the environment (`requires_env` above lists what this skill needs).

## Skill

When you send the user an updated version of a file you've **already** sent them,
give it a new filename with an incremented version number — `report_v2.docx`,
`report_v3.docx`, and so on. If you reuse the filename the user has already
received, the delivery event won't fire and they'll never get the update, even
though the file changed. A filename they haven't seen before is what triggers the
send.

So annotate each iteration with the next version number, and the user receives
every version as its own attachment.

## Example
```
report_v1.docx   first version sent to the user
report_v2.docx   the same file after "make the timeline more detailed"
report_v3.docx   after "also add a budget table"
```

---

*Converted for the AIBAST Agents Library from CAT Agent Skills.
The original is authoritative; this file adds the RAPP manifest and the
deterministic layer above, and changes nothing else about the instructions.*
"""

SKILL_REF = "@cat-agent-skills/iterative_file_editing"
SKILL_LICENSE = "MIT"
SKILL_SOURCE = "https://microsoft.github.io/cat-agent-skills/#iterative-file-editing"


class IterativeFileEditingAgent(BasicAgent):
    """Delivers a verified RAPP procedure as a callable tool.

    Inputs — none required. `context` optionally narrows the returned
        procedure to a stated situation; it is echoed back, never invented.
    Output — the full skill procedure as text: inputs, outputs, and the
        verification step the caller must perform before reporting success.
    Verification — the caller confirms the artifact named by the procedure
        exists and matches what was asked. This agent returns instructions; it
        does not perform the work described in them, and it never reports
        success on the caller's behalf.
    Configuration — none. The procedure is embedded in this file.
    """

    def __init__(self):
        self.name = "Iterative File Editing"
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "context": {
                        "type": "string",
                        "description": (
                            "Optional. The specific situation the procedure is "
                            "being applied to, echoed back with the steps — for "
                            "example 'a 40-slide deck for an external customer'."
                        ),
                    }
                },
                "required": [],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        context = (kwargs.get("context") or "").strip()
        header = [
            f"# {self.name} — RAPP procedure",
            "",
            f"Source: {SKILL_REF} · redistributed under {SKILL_LICENSE} "
            f"with attribution ({SKILL_SOURCE}).",
        ]
        if context:
            header += ["", f"**Applied to:** {context}"]
        header += [
            "",
            "Follow the steps below exactly. Where a step names an input you "
            "do not have, say so and stop rather than guessing, and complete "
            "the verification step before reporting success.",
            "",
            "---",
            "",
        ]
        return "\n".join(header) + SKILL_PROCEDURE
