"""
Dataverse Table Lookup — RAPP agent, mirrored from lookup_dataverse_table.md

This file is GENERATED from its skill.md by scripts/export_agent.py and is one
half of a matched pair. The manifest below and the procedure embedded further
down are identical to the ones in the .md; the only difference is the runtime:
a model reads the .md, a brainstem registers this .py and calls it as a tool.

Do not edit this file. Edit lookup_dataverse_table.md and re-run the exporter — the gate
re-derives this file and fails if the two have drifted apart.

Redistributed from CAT Agent Skills under MIT
with attribution. Original author: Chris Garty.
Origin: https://microsoft.github.io/cat-agent-skills/#lookup-dataverse-table
"""

# ===============================================================
# RAPP AGENT MANIFEST - Do not remove. Used by registry builder.
# ===============================================================
__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@cat-agent-skills/lookup_dataverse_table",
    "version": "1.0.0",
    "display_name": "Dataverse Table Lookup",
    "description": "Returns the verified RAPP procedure for: Search any Microsoft Dataverse table, browse matching records, and drill into full record details \\u2014 sourced live via the Dataverse MCP Server. Call this to obtain the full step-by-step contract (inputs, outputs, verification) and then carry out those steps.",
    "author": "Chris Garty",
    "tags": [
        "dataverse",
        "mcp",
        "data-lookup",
        "power-platform",
        "crm"
    ],
    "category": "general",
    "quality_tier": "aggregated",
    "requires_env": [],
    "dependencies": [
        "@rapp/basic-agent"
    ],
    "mirrors": "lookup_dataverse_table.md",
    "source_url": "https://microsoft.github.io/cat-agent-skills/#lookup-dataverse-table",
    "source_license": "MIT",
    "converted_from": "CAT Agent Skills"
}
# ===============================================================

try:  # cloud layout (agents package)
    from agents.basic_agent import BasicAgent
except ImportError:  # local brainstem / standalone layout
    import os
    import sys

    sys.path.insert(0, os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "..",
        "agents", "@aibast-agents-library", "templates"))
    from basic_agent import BasicAgent


# The skill body, embedded verbatim. This is what makes the export single-file:
# the procedure travels with the agent rather than being fetched at call time.
SKILL_PROCEDURE = """# Dataverse Table Lookup

> **Converted skill.** This is a RAPP single-file skill converted from
> **CAT Agent Skills** ([origin](https://microsoft.github.io/cat-agent-skills/#lookup-dataverse-table)), redistributed under
> **MIT** with attribution. Original author: Chris Garty.
> Upstream license text: https://raw.githubusercontent.com/microsoft/cat-agent-skills/main/LICENSE
>
> Drop this file into your brainstem's skills folder, or read it and run the
> steps yourself. Everything the skill needs is in this one file.

## When to use this

Use this skill whenever the user wants to search, browse, or look up records in a Microsoft Dataverse table — for example \\"look up accounts\\", \\"find opportunities for Contoso\\", \\"show me contact details\\", or \\"search cases by status\\". Always prefer this skill (which queries Dataverse live via the Dataverse MCP Server) BEFORE answering any question about Dataverse records.

## The deterministic layer

RAPP skills state their contract explicitly, so two runs of the same skill do
the same thing:

- **Inputs** — whatever the steps below name. If an input is missing, say so
  and stop rather than guessing.
- **Outputs** — the artifact the steps produce, named where it is written.
- **Verification** — before reporting success, confirm the output exists and
  matches what was asked. A silent partial result is a failure.
- **Configuration** — never hardcode an endpoint, key, or tenant. Read them
  from the environment (`requires_env` above lists what this skill needs).

## Skill

Help the user search any Microsoft Dataverse table, browse matching records, and
view full record details — all sourced live from Dataverse via the Dataverse MCP
Server tool.

## Data source (critical)

- Always source data **dynamically** from Microsoft Dataverse using the Dataverse
  MCP Server tool.
- **NEVER** fabricate, invent, hardcode, guess, or reuse records from examples or
  prior general knowledge. Every record and every field value you show must come
  from a live query via the tool.
- If the tool returns no results or fails, say so plainly and ask the user to try
  again or refine their search. Do not make up data.

## Workflow

### Step 1 — Identify the table

- If the user names a table (e.g. "accounts", "opportunities", "contacts"), use
  that table.
- If the user is ambiguous, ask: *"Which table would you like to search? For
  example: contacts, accounts, opportunities, leads, etc."*
- Use `describe('tables/')` to resolve the table's logical name if needed.

### Step 2 — Discover the schema

Before querying, call `describe('tables/{tablename}')` to retrieve:

- The table's **primary name field** (used for display).
- The table's **primary key field** (used internally for record lookup).
- Available columns and their logical names and types.

Note the **primary key field name** (e.g. `accountid`) so you can request its
value when querying. The primary key GUID **values** returned by later queries
stay **internal** — never display them to the user.

### Step 3 — Find records

1. Query the table using `read_query`, always retrieving at least:
   - The **primary name field**
   - A **key identifier field** (e.g. email, account number, status)
   - The **primary key** (for internal use only)
2. Apply any search filters the user provides (name, keyword, status, date range,
   related record, etc.).
3. Return **at most 15 rows**. If more than 15 records match, show the first 15
   and prompt the user to narrow the search.
4. If a field has no value, show `(none)`.

Present results as a numbered markdown list, or a table with a leading number
column so the user can select by number:

| # | Record Name | Key Identifier |
|---|-------------|----------------|
| 1 | Example Corp | account@example.com |
| 2 | Another Record | 555-0100 |

### Step 4 — Select a record

When the user selects a record (by number, name, or identifier):

1. Re-query the Dataverse table using the internally stored primary key GUID.
2. Display the most useful ~20 fields for that record, presented as a readable
   labeled list or table.
3. Omit empty/null fields unless the user requests the full record.
4. Never reveal GUIDs or internal identifiers.

Example detail view:

| Field | Value |
|-------|-------|
| **Name** | Example Corp |
| **Email** | account@example.com |
| **Phone** | 555-0100 |
| **City** | Seattle |
| **State** | WA |

## Remembering preferred fields

- If the user requests a different set of fields (add, remove, or replace),
  **remember those preferences** using memory tools.
- Default to the user's preferred field set on all subsequent detail lookups — in
  this and future conversations — until the user changes it again.

## Supported tables

The skill works with **any** Dataverse table. Common examples:

| Table display name | Logical name |
|--------------------|--------------|
| Contacts | contact |
| Accounts | account |
| Opportunities | opportunity |
| Leads | lead |
| Cases | incident |
| Products | product |
| Orders | salesorder |
| Invoices | invoice |
| Activities | activitypointer |
| Users | systemuser |

Use `describe('tables/')` to discover all available tables in the environment.

## Guardrails

- Present matching records as a numbered markdown list, or a table with a leading
  number column (# / Record Name / Key Identifier).
- Do **not** expose raw GUIDs, internal IDs, query syntax, or raw tool payloads
  to the user.
- Do **not** emit adaptive card or suggested-action code blocks.
- When a search yields no results, say so clearly and suggest alternative search
  terms.
- When a table is not found, suggest similar table names or ask the user to
  clarify.
- When more than 15 records match, always prompt the user to refine the search
  rather than paginating silently.

## Tone

Be concise and helpful. Explain uncertainty rather than hiding it, and never
present fabricated data as if it came from Dataverse.

---

*Converted for the AIBAST Agents Library from CAT Agent Skills.
The original is authoritative; this file adds the RAPP manifest and the
deterministic layer above, and changes nothing else about the instructions.*
"""

SKILL_REF = "@cat-agent-skills/lookup_dataverse_table"
SKILL_LICENSE = "MIT"
SKILL_SOURCE = "https://microsoft.github.io/cat-agent-skills/#lookup-dataverse-table"


class LookupDataverseTableAgent(BasicAgent):
    """Delivers a verified RAPP procedure as a callable tool.

    Inputs — none required. `context` optionally narrows the returned
        procedure to a stated situation; it is echoed back, never invented.
    Output — the full skill procedure as text: inputs, outputs, and the
        verification step the caller must perform before reporting success.
    Verification — the caller confirms the artifact named by the procedure
        exists and matches what was asked. This agent returns instructions; it
        does not perform the work described in them, and it never reports
        success on the caller's behalf.
    Configuration — none. The procedure is embedded in this file.
    """

    def __init__(self):
        self.name = "Dataverse Table Lookup"
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "context": {
                        "type": "string",
                        "description": (
                            "Optional. The specific situation the procedure is "
                            "being applied to, echoed back with the steps — for "
                            "example 'a 40-slide deck for an external customer'."
                        ),
                    }
                },
                "required": [],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        context = (kwargs.get("context") or "").strip()
        header = [
            f"# {self.name} — RAPP procedure",
            "",
            f"Source: {SKILL_REF} · redistributed under {SKILL_LICENSE} "
            f"with attribution ({SKILL_SOURCE}).",
        ]
        if context:
            header += ["", f"**Applied to:** {context}"]
        header += [
            "",
            "Follow the steps below exactly. Where a step names an input you "
            "do not have, say so and stop rather than guessing, and complete "
            "the verification step before reporting success.",
            "",
            "---",
            "",
        ]
        return "\n".join(header) + SKILL_PROCEDURE
