"""
Meeting Analyzer — RAPP agent, mirrored from meeting_analyzer.md

This file is GENERATED from its skill.md by scripts/export_agent.py and is one
half of a matched pair. The manifest below and the procedure embedded further
down are identical to the ones in the .md; the only difference is the runtime:
a model reads the .md, a brainstem registers this .py and calls it as a tool.

Do not edit this file. Edit meeting_analyzer.md and re-run the exporter — the gate
re-derives this file and fails if the two have drifted apart.

Redistributed from CAT Agent Skills under MIT
with attribution. Original author: Michael Ferro Pereira.
Origin: https://microsoft.github.io/cat-agent-skills/#meeting-analyzer
"""

# ===============================================================
# RAPP AGENT MANIFEST - Do not remove. Used by registry builder.
# ===============================================================
__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@cat-agent-skills/meeting_analyzer",
    "version": "1.0.0",
    "display_name": "Meeting Analyzer",
    "description": "Returns the verified RAPP procedure for: Analyzes meeting content pasted as text or provided as audio/video transcripts. Delivers a structured intelligence report: explicit decisions and action items, participant persona profiles, and \\u2014 most importantly \\u2014 hidden insights: unspoken tensions, implicit risks, unresolved topics, and signals that were not made explicit during the meeting but are critical to the context. Call this to obtain the full step-by-step contract (inputs, outputs, verification) and then carry out those steps.",
    "author": "Michael Ferro Pereira",
    "tags": [
        "meetings",
        "analysis",
        "insights",
        "personas",
        "transcription",
        "productivity",
        "communication"
    ],
    "category": "it_management",
    "quality_tier": "aggregated",
    "requires_env": [],
    "dependencies": [
        "@rapp/basic-agent"
    ],
    "mirrors": "meeting_analyzer.md",
    "source_url": "https://microsoft.github.io/cat-agent-skills/#meeting-analyzer",
    "source_license": "MIT",
    "converted_from": "CAT Agent Skills"
}
# ===============================================================

try:  # cloud layout (agents package)
    from agents.basic_agent import BasicAgent
except ImportError:  # local brainstem / standalone layout
    import os
    import sys

    sys.path.insert(0, os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "..",
        "agents", "@aibast-agents-library", "templates"))
    from basic_agent import BasicAgent


# The skill body, embedded verbatim. This is what makes the export single-file:
# the procedure travels with the agent rather than being fetched at call time.
SKILL_PROCEDURE = """# Meeting Analyzer

> **Converted skill.** This is a RAPP single-file skill converted from
> **CAT Agent Skills** ([origin](https://microsoft.github.io/cat-agent-skills/#meeting-analyzer)), redistributed under
> **MIT** with attribution. Original author: Michael Ferro Pereira.
> Upstream license text: https://raw.githubusercontent.com/microsoft/cat-agent-skills/main/LICENSE
>
> Drop this file into your brainstem's skills folder, or read it and run the
> steps yourself. Everything the skill needs is in this one file.

## When to use this

Analyzes meetings from pasted text, transcripts, or audio/video recordings and turns them into a structured intelligence report. Use this skill whenever the user shares meeting content in any form — a raw transcript, meeting notes, a Teams/Zoom recap, an audio or video file, or simply pastes a block of dialogue — and wants to understand what happened, who the participants are, what was decided, or \\"what really went on\\" in the meeting. Trigger it even when the user does not say \\"analyze\\": phrases like \\"summarize this meeting\\", \\"what did we agree on\\", \\"read this transcript\\", \\"insights from this call\\", or \\"what am I missing from this conversation\\" all indicate this skill. It surfaces explicit outcomes (decisions, action items, deadlines), builds persona profiles of the participants, and uncovers hidden insights: unspoken tensions, implicit risks, avoided topics, and signals that were never made explicit but matter deeply to the context.\\n

## The deterministic layer

RAPP skills state their contract explicitly, so two runs of the same skill do
the same thing:

- **Inputs** — whatever the steps below name. If an input is missing, say so
  and stop rather than guessing.
- **Outputs** — the artifact the steps produce, named where it is written.
- **Verification** — before reporting success, confirm the output exists and
  matches what was asked. A silent partial result is a failure.
- **Configuration** — never hardcode an endpoint, key, or tenant. Read them
  from the environment (`requires_env` above lists what this skill needs).

## Skill

# Meeting Analyzer

Act as a meeting-intelligence analyst. Produce evidence-grounded analysis, not a summary:
surface what was decided, who the participants are behaviorally, and what was meant but
not said.

Write the entire analysis in the language of the requesting user, regardless of the
meeting's language. Keep direct quotes in their original language; add a translation when
useful.

## Step 1 — Ingest

- Pasted text, transcript, or notes: use directly.
- Audio or video: transcribe first with an available speech-to-text tool. If none is
  available, state that and ask the user to paste the transcript or captions. Do not
  infer content you cannot hear.
- Assess source quality (verbatim vs. paraphrased, speakers labeled or not, gaps) and
  state it in the report. Scale the confidence of interpretive claims to source quality.
- Ask at most one clarifying question, and only if the analysis cannot proceed without
  it; otherwise analyze and note assumptions.

## Step 2 — Extract the explicit layer

Capture, with attribution:

1. Purpose of the meeting and whether it was achieved.
2. Decisions: who made each, and firmness (committed / leaning / discussed only). Do not
   upgrade a discussion into a decision.
3. Action items: task, owner, deadline. Record missing owners/dates explicitly — they are
   findings.
4. Key facts, figures, and constraints.
5. Questions raised but not answered.

## Step 3 — Build persona profiles

Read `reference/persona-framework.md`, then profile each identifiable participant:
apparent role and stake, communication style, positions and influence, and closest
behavioral archetype. Ground every claim in something the person said or did. With
unlabeled speakers, infer distinct voices only when the text clearly supports it, and
mark the profile as inferred.

## Step 4 — Uncover the hidden layer

Read `reference/hidden-insights-guide.md`, then check every category: the unsaid, tension
and subtext, fragile agreements, misalignments, power dynamics, unnamed risks.

For each insight provide: evidence (quote or moment), interpretation, and confidence
(high / medium / low). Never present interpretation as fact. Cut insights that a neutral
reader would not see in the evidence or that would change no action.

## Step 5 — Deliver the report

Use the structure in `asset/report-template.md`. Keep the section order; scale depth to
the material. End with 3–7 prioritized recommended next actions tied to specific
findings, especially the hidden ones.

## Quality bar

- Every claim traces to evidence in the source material.
- Hidden insights are clearly separated from explicit facts and carry confidence levels.
- No invented names, dates, or commitments — gaps are reported as gaps.

---

*Converted for the AIBAST Agents Library from CAT Agent Skills.
The original is authoritative; this file adds the RAPP manifest and the
deterministic layer above, and changes nothing else about the instructions.*
"""

SKILL_REF = "@cat-agent-skills/meeting_analyzer"
SKILL_LICENSE = "MIT"
SKILL_SOURCE = "https://microsoft.github.io/cat-agent-skills/#meeting-analyzer"


class MeetingAnalyzerAgent(BasicAgent):
    """Delivers a verified RAPP procedure as a callable tool.

    Inputs — none required. `context` optionally narrows the returned
        procedure to a stated situation; it is echoed back, never invented.
    Output — the full skill procedure as text: inputs, outputs, and the
        verification step the caller must perform before reporting success.
    Verification — the caller confirms the artifact named by the procedure
        exists and matches what was asked. This agent returns instructions; it
        does not perform the work described in them, and it never reports
        success on the caller's behalf.
    Configuration — none. The procedure is embedded in this file.
    """

    def __init__(self):
        self.name = "Meeting Analyzer"
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "context": {
                        "type": "string",
                        "description": (
                            "Optional. The specific situation the procedure is "
                            "being applied to, echoed back with the steps — for "
                            "example 'a 40-slide deck for an external customer'."
                        ),
                    }
                },
                "required": [],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        context = (kwargs.get("context") or "").strip()
        header = [
            f"# {self.name} — RAPP procedure",
            "",
            f"Source: {SKILL_REF} · redistributed under {SKILL_LICENSE} "
            f"with attribution ({SKILL_SOURCE}).",
        ]
        if context:
            header += ["", f"**Applied to:** {context}"]
        header += [
            "",
            "Follow the steps below exactly. Where a step names an input you "
            "do not have, say so and stop rather than guessing, and complete "
            "the verification step before reporting success.",
            "",
            "---",
            "",
        ]
        return "\n".join(header) + SKILL_PROCEDURE
