"""
Pattern Radar — RAPP agent, mirrored from pattern_radar.md

This file is GENERATED from its skill.md by scripts/export_agent.py and is one
half of a matched pair. The manifest below and the procedure embedded further
down are identical to the ones in the .md; the only difference is the runtime:
a model reads the .md, a brainstem registers this .py and calls it as a tool.

Do not edit this file. Edit pattern_radar.md and re-run the exporter — the gate
re-derives this file and fails if the two have drifted apart.

Redistributed from CAT Agent Skills under MIT
with attribution. Original author: Srinivas Varukala.
Origin: https://microsoft.github.io/cat-agent-skills/#pattern-radar
"""

# ===============================================================
# RAPP AGENT MANIFEST - Do not remove. Used by registry builder.
# ===============================================================
__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@cat-agent-skills/pattern_radar",
    "version": "1.0.0",
    "display_name": "Pattern Radar",
    "description": "Returns the verified RAPP procedure for: Scans your recent Microsoft 365 signals to surface recurring patterns worth productizing \\u2014 things you keep explaining (blog candidates) or multi-step tasks you keep doing by hand (automation candidates). Call this to obtain the full step-by-step contract (inputs, outputs, verification) and then carry out those steps.",
    "author": "Srinivas Varukala",
    "tags": [
        "productivity",
        "automation",
        "content",
        "email",
        "teams",
        "insights"
    ],
    "category": "it_management",
    "quality_tier": "aggregated",
    "requires_env": [],
    "dependencies": [
        "@rapp/basic-agent"
    ],
    "mirrors": "pattern_radar.md",
    "source_url": "https://microsoft.github.io/cat-agent-skills/#pattern-radar",
    "source_license": "MIT",
    "converted_from": "CAT Agent Skills"
}
# ===============================================================

try:  # cloud layout (agents package)
    from agents.basic_agent import BasicAgent
except ImportError:  # local brainstem / standalone layout
    import os
    import sys

    sys.path.insert(0, os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "..",
        "agents", "@aibast-agents-library", "templates"))
    from basic_agent import BasicAgent


# The skill body, embedded verbatim. This is what makes the export single-file:
# the procedure travels with the agent rather than being fetched at call time.
SKILL_PROCEDURE = """# Pattern Radar

> **Converted skill.** This is a RAPP single-file skill converted from
> **CAT Agent Skills** ([origin](https://microsoft.github.io/cat-agent-skills/#pattern-radar)), redistributed under
> **MIT** with attribution. Original author: Srinivas Varukala.
> Upstream license text: https://raw.githubusercontent.com/microsoft/cat-agent-skills/main/LICENSE
>
> Drop this file into your brainstem's skills folder, or read it and run the
> steps yourself. Everything the skill needs is in this one file.

## When to use this

Scan the user's recent Microsoft 365 signals (emails, active chats/channels, calendar subjects) to surface recurring patterns worth productizing — either as a blog post (the user explains the same thing repeatedly) or as an automation (the user does the same multi-step task repeatedly). Use when the user asks \\"what should I write about?\\", \\"what could I automate?\\", \\"find patterns in my work\\", or invokes \\"/pattern-radar\\".

## The deterministic layer

RAPP skills state their contract explicitly, so two runs of the same skill do
the same thing:

- **Inputs** — whatever the steps below name. If an input is missing, say so
  and stop rather than guessing.
- **Outputs** — the artifact the steps produce, named where it is written.
- **Verification** — before reporting success, confirm the output exists and
  matches what was asked. A silent partial result is a failure.
- **Configuration** — never hardcode an endpoint, key, or tenant. Read them
  from the environment (`requires_env` above lists what this skill needs).

## Skill

# Pattern Radar

Find recurring patterns in the user's recent work signals that could be turned
into leverage — a **blog post** (the user keeps explaining the same thing) or an
**automation** (the user keeps doing the same manual, multi-step task). Give
blog and automation candidates equal weight; bias toward automation candidates,
since offloading repetitive work is usually the bigger win.

Default lookback window: **the last 7 days** from the current date/time. Treat
the provided current datetime as authoritative — never reason from training-data
dates.

> **Tool names.** This skill refers to Microsoft 365 tools as `m365_*`. If your
> host exposes them under different names, map them to the equivalent capability.

## Inputs — collect breadth, not depth

1. **Email** — list Inbox and Sent from the last 7 days (subjects + first-line
   previews only; do not open bodies). **Pay special attention to Sent items**:
   they reveal the user's own repeated outbound actions (forwards, intros, status
   pings, FYIs, "looping in X" handoffs, RSVPs, reschedules).
2. **Active chats** — list recent chats; for each chat the user has posted in
   over the last ~30 days, fetch the last 7 days of messages. Strip @-mention
   noise.
3. **Active channels** — for channels the user has posted in over the last ~30
   days, fetch the last 7 days of messages. Skip silent channels.
4. **Calendar** — list events from the last 7 days (**subjects only** — no
   bodies, no attendee lists). Look for repeated reschedules, repeated tentative
   responses, recurring conflict patterns, and meeting-prep cadences.

## Clustering — what counts as a pattern

A signal qualifies only if it appears **≥3 times across ≥2 distinct people /
chats / customers / threads / events** in the window. Be ruthless — one-offs are
noise.

**Blog cluster types**

- **Repeated explanation** — the user answers the same question or explains the
  same concept to 3+ different people. → blog candidate.
- **Recurring FAQ** — the same question shows up in 3+ chats/channels from
  different askers. → blog / FAQ candidate.

**Automation cluster types (cast a wide net)**

- **Repeated multi-step manual task** — the same sequence of clicks / drafts /
  file moves / API calls, repeatedly. → automation candidate.
- **Repeated handoff / triage** — forwarding, "looping in", or intro'ing the
  same kinds of items to the same people 3+ times. → auto-route by rule or
  classifier.
- **Repeated status pings / FYIs** — the same kind of update to the same audience
  on a cadence. → scheduled digest.
- **Repeated meeting reschedules** for the same root cause. → auto-propose
  alternates.
- **Repeated RSVPs / tentative responses** to recurring meetings with consistent
  reasoning. → auto-respond by rule.
- **Repeated meeting prep** — gathering the same context before recurring
  meetings. → pre-meeting brief.
- **Repeated doc/wiki updates** — manually appending the same kind of content on
  a cadence. → scheduled ingest.
- **Repeated approvals / sign-offs** of the same class of request. → rule-based
  pre-screen.
- **Repeated file/data shuttling** — move/rename/reformat between systems. →
  pipeline.
- **Repeated drafting** — near-identical emails/messages (welcome notes,
  onboarding intros, availability, "I have a conflict" replies, follow-ups). →
  template + auto-fill.

**Anti-patterns — do NOT surface**

- Normal recurring meeting cadence (standups, weekly syncs) UNLESS there's
  repetitive *manual* work around them that could be automated.
- Anything needing the body of an excluded/private email to reason about.
- Automations the user already runs.

## Output

List **0–3 candidates max**. If signal is thin (< 3 reinforcing data points
across all clusters), output: `✅ No new patterns this run.`

Prefer a **mix** — include at least one automation candidate when one qualifies,
even if a blog candidate is stronger.

Per candidate (≤3 lines each):

```
💡 **<theme in 5–8 words>**
   _evidence:_ <1–2 anonymized signals, e.g. "forwarded 4 customer asks to the
   same engineer this week" or "explained X to 4 different people in chats">
   **<blog|automation>** · <1-line rationale. For automation, name the trigger
   and the action, e.g. "trigger: incoming request → action: auto-route + draft
   reply".>
```

## Privacy & guardrails

- **Read-only.** Never send any email, chat, channel reply, or Teams message from
  this skill. Producing the report is the only output.
- **Anonymize.** Never include customer/team names, attendee names, meeting
  times/locations, file paths, or full subjects containing customer identifiers.
  Say "3 different customers", not the actual names.
- **Respect exclusions.** Never open or paraphrase content the user has marked as
  private or excluded (e.g. performance-review or confidential emails).
- When in doubt that a candidate is a real pattern vs. coincidence, drop it —
  silence is safer than noise.

---

*Converted for the AIBAST Agents Library from CAT Agent Skills.
The original is authoritative; this file adds the RAPP manifest and the
deterministic layer above, and changes nothing else about the instructions.*
"""

SKILL_REF = "@cat-agent-skills/pattern_radar"
SKILL_LICENSE = "MIT"
SKILL_SOURCE = "https://microsoft.github.io/cat-agent-skills/#pattern-radar"


class PatternRadarAgent(BasicAgent):
    """Delivers a verified RAPP procedure as a callable tool.

    Inputs — none required. `context` optionally narrows the returned
        procedure to a stated situation; it is echoed back, never invented.
    Output — the full skill procedure as text: inputs, outputs, and the
        verification step the caller must perform before reporting success.
    Verification — the caller confirms the artifact named by the procedure
        exists and matches what was asked. This agent returns instructions; it
        does not perform the work described in them, and it never reports
        success on the caller's behalf.
    Configuration — none. The procedure is embedded in this file.
    """

    def __init__(self):
        self.name = "Pattern Radar"
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "context": {
                        "type": "string",
                        "description": (
                            "Optional. The specific situation the procedure is "
                            "being applied to, echoed back with the steps — for "
                            "example 'a 40-slide deck for an external customer'."
                        ),
                    }
                },
                "required": [],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        context = (kwargs.get("context") or "").strip()
        header = [
            f"# {self.name} — RAPP procedure",
            "",
            f"Source: {SKILL_REF} · redistributed under {SKILL_LICENSE} "
            f"with attribution ({SKILL_SOURCE}).",
        ]
        if context:
            header += ["", f"**Applied to:** {context}"]
        header += [
            "",
            "Follow the steps below exactly. Where a step names an input you "
            "do not have, say so and stop rather than guessing, and complete "
            "the verification step before reporting success.",
            "",
            "---",
            "",
        ]
        return "\n".join(header) + SKILL_PROCEDURE
