"""
Process & SOP Architect — RAPP agent, mirrored from process_sop_architect.md

This file is GENERATED from its skill.md by scripts/export_agent.py and is one
half of a matched pair. The manifest below and the procedure embedded further
down are identical to the ones in the .md; the only difference is the runtime:
a model reads the .md, a brainstem registers this .py and calls it as a tool.

Do not edit this file. Edit process_sop_architect.md and re-run the exporter — the gate
re-derives this file and fails if the two have drifted apart.

Redistributed from CAT Agent Skills under MIT
with attribution. Original author: Parag Dessai.
Origin: https://microsoft.github.io/cat-agent-skills/#process-sop-architect
"""

# ===============================================================
# RAPP AGENT MANIFEST - Do not remove. Used by registry builder.
# ===============================================================
__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@cat-agent-skills/process_sop_architect",
    "version": "1.1.0",
    "display_name": "Process & SOP Architect",
    "description": "Returns the verified RAPP procedure for: Turn process notes and transcripts into an editable SOP, process map, RACI, control register, improvement backlog, and polished PowerPoint briefing. Call this to obtain the full step-by-step contract (inputs, outputs, verification) and then carry out those steps.",
    "author": "Parag Dessai",
    "tags": [
        "process-improvement",
        "sop",
        "operations",
        "powerpoint",
        "productivity"
    ],
    "category": "general",
    "quality_tier": "aggregated",
    "requires_env": [],
    "dependencies": [
        "@rapp/basic-agent"
    ],
    "mirrors": "process_sop_architect.md",
    "source_url": "https://microsoft.github.io/cat-agent-skills/#process-sop-architect",
    "source_license": "MIT",
    "converted_from": "CAT Agent Skills"
}
# ===============================================================

try:  # cloud layout (agents package)
    from agents.basic_agent import BasicAgent
except ImportError:  # local brainstem / standalone layout
    import os
    import sys

    sys.path.insert(0, os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "..",
        "agents", "@aibast-agents-library", "templates"))
    from basic_agent import BasicAgent


# The skill body, embedded verbatim. This is what makes the export single-file:
# the procedure travels with the agent rather than being fetched at call time.
SKILL_PROCEDURE = """# Process & SOP Architect

> **Converted skill.** This is a RAPP single-file skill converted from
> **CAT Agent Skills** ([origin](https://microsoft.github.io/cat-agent-skills/#process-sop-architect)), redistributed under
> **MIT** with attribution. Original author: Parag Dessai.
> Upstream license text: https://raw.githubusercontent.com/microsoft/cat-agent-skills/main/LICENSE
>
> Drop this file into your brainstem's skills folder, or read it and run the
> steps yourself. Everything the skill needs is in this one file.

## When to use this

Use this skill whenever the user asks to document, map, standardize, redesign, or improve a business process from notes, transcripts, interviews, or requirements, especially when they need an editable SOP, process map, RACI, controls, improvement backlog, or polished PowerPoint briefing.

## The deterministic layer

RAPP skills state their contract explicitly, so two runs of the same skill do
the same thing:

- **Inputs** — whatever the steps below name. If an input is missing, say so
  and stop rather than guessing.
- **Outputs** — the artifact the steps produce, named where it is written.
- **Verification** — before reporting success, confirm the output exists and
  matches what was asked. A silent partial result is a failure.
- **Configuration** — never hardcode an endpoint, key, or tenant. Read them
  from the environment (`requires_env` above lists what this skill needs).

## Skill

# Process & SOP Architect

## When to activate this skill
Activate when the user asks to document, map, redesign, standardize, or improve a business process. Typical triggers include: "turn these notes into an SOP", "map our onboarding process", "create a RACI", "document the current state", "identify process gaps", or "create a future-state workflow".

Do NOT activate when:
- The user wants a software architecture diagram rather than a business process.
- The request is only to summarize a meeting without building an operating procedure.
- The user has not supplied enough information to identify the process scope and actors.

## How this skill runs
1. Review the user's source material and build a process specification using `references/process_spec_schema.md`.
2. Ask targeted questions for missing trigger, scope, roles, decisions, exceptions, controls, or outputs. Ask one question at a time.
3. From the skill's root directory (the folder that contains `scripts/` and `references/`), save the specification as `process_spec.json`, and run the commands below from that same directory so the `scripts/` paths resolve. Use this directory rather than `/tmp`, which is not reliably writable in the sandbox.
4. Validate it:
   ```bash
   python scripts/validate_process_spec.py --input process_spec.json
   ```
5. Generate the process pack, including the polished executive PowerPoint briefing:
   ```bash
   python scripts/generate_process_pack.py \\
      --input process_spec.json \\
      --output-dir process_pack
   ```
6. Return the generated SOP, process map, RACI workbook, improvement backlog, executive summary, and PowerPoint briefing.

## Requirements
- `python-docx` (Word SOP)
- `openpyxl` (Excel RACI and control register)
- `python-pptx` (PowerPoint executive briefing)

These packages are present in the Copilot Studio sandbox — no `pip install` is required. The generators import them at startup and fail fast with a clear error if a dependency is missing, so a partial pack is never reported as complete.

## Required outputs
- Editable Word SOP
- SVG process flow that can be opened in a browser or inserted into Office
- Excel RACI and control register
- CSV improvement backlog
- Markdown executive summary and unresolved-question log
- Editable PowerPoint executive briefing with title slide, snapshot, process flow, role handoffs, controls, risks, roadmap, chart, and next steps

## Workflow the agent must follow
1. Establish whether the user wants current state, future state, or both.
2. Define the process boundary: trigger, start, end, inputs, outputs, and exclusions.
3. Identify roles, systems, decisions, handoffs, exceptions, controls, and evidence.
4. Separate observed facts from assumptions and recommendations.
5. Build a complete process specification.
6. Run validation and resolve errors before generation.
7. Review generated deliverables for traceability and usability.
8. Ensure the PowerPoint uses assertion-style slide titles, separates facts from recommendations, and does not introduce unsupported claims.

## Quality rules
- Use verb-object wording for process steps, such as `Validate request` or `Approve payment`.
- Every step must have an owner.
- Every decision must define both yes and no paths.
- Every control must identify purpose, owner, frequency, and evidence.
- Do not invent policy, legal, regulatory, service-level, or approval requirements.
- Label missing information as `TBD` and include it in the unresolved-question log.
- Distinguish current-state problems from future-state recommendations.
- Do not automate a process merely because automation is possible.
- The presentation must summarize the SOP; it must not replace the SOP or invent new process facts.
- PowerPoint slides should be leadership-ready, concise, and editable.

## Activation examples
- "Create an SOP from this onboarding workshop transcript."
- "Map the complaint-management process and identify control gaps."
- "Turn these process notes into a RACI and future-state improvement plan."
- "Document our invoice exception process for training and audit."

## Run example
```bash
python scripts/validate_process_spec.py --input assets/example_process_spec.json
python scripts/generate_process_pack.py \\
  --input assets/example_process_spec.json \\
  --output-dir vendor_onboarding_pack

# Generate only the PowerPoint briefing
python scripts/generate_presentation.py \\
  --input assets/example_process_spec.json \\
  --output-dir vendor_onboarding_pack
```

---

*Converted for the AIBAST Agents Library from CAT Agent Skills.
The original is authoritative; this file adds the RAPP manifest and the
deterministic layer above, and changes nothing else about the instructions.*
"""

SKILL_REF = "@cat-agent-skills/process_sop_architect"
SKILL_LICENSE = "MIT"
SKILL_SOURCE = "https://microsoft.github.io/cat-agent-skills/#process-sop-architect"


class ProcessSopArchitectAgent(BasicAgent):
    """Delivers a verified RAPP procedure as a callable tool.

    Inputs — none required. `context` optionally narrows the returned
        procedure to a stated situation; it is echoed back, never invented.
    Output — the full skill procedure as text: inputs, outputs, and the
        verification step the caller must perform before reporting success.
    Verification — the caller confirms the artifact named by the procedure
        exists and matches what was asked. This agent returns instructions; it
        does not perform the work described in them, and it never reports
        success on the caller's behalf.
    Configuration — none. The procedure is embedded in this file.
    """

    def __init__(self):
        self.name = "Process & SOP Architect"
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "context": {
                        "type": "string",
                        "description": (
                            "Optional. The specific situation the procedure is "
                            "being applied to, echoed back with the steps — for "
                            "example 'a 40-slide deck for an external customer'."
                        ),
                    }
                },
                "required": [],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        context = (kwargs.get("context") or "").strip()
        header = [
            f"# {self.name} — RAPP procedure",
            "",
            f"Source: {SKILL_REF} · redistributed under {SKILL_LICENSE} "
            f"with attribution ({SKILL_SOURCE}).",
        ]
        if context:
            header += ["", f"**Applied to:** {context}"]
        header += [
            "",
            "Follow the steps below exactly. Where a step names an input you "
            "do not have, say so and stop rather than guessing, and complete "
            "the verification step before reporting success.",
            "",
            "---",
            "",
        ]
        return "\n".join(header) + SKILL_PROCEDURE
