"""
Skill Authoring Coach — RAPP agent, mirrored from skill_authoring_coach.md

This file is GENERATED from its skill.md by scripts/export_agent.py and is one
half of a matched pair. The manifest below and the procedure embedded further
down are identical to the ones in the .md; the only difference is the runtime:
a model reads the .md, a brainstem registers this .py and calls it as a tool.

Do not edit this file. Edit skill_authoring_coach.md and re-run the exporter — the gate
re-derives this file and fails if the two have drifted apart.

Redistributed from CAT Agent Skills under MIT
with attribution. Original author: Simon Owen.
Origin: https://microsoft.github.io/cat-agent-skills/#skill-authoring-coach
"""

# ===============================================================
# RAPP AGENT MANIFEST - Do not remove. Used by registry builder.
# ===============================================================
__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@cat-agent-skills/skill_authoring_coach",
    "version": "0.1.0",
    "display_name": "Skill Authoring Coach",
    "description": "Returns the verified RAPP procedure for: Help makers design concise, reusable Agent Skills with clear triggers, instructions, resources, and packaging. Call this to obtain the full step-by-step contract (inputs, outputs, verification) and then carry out those steps.",
    "author": "Simon Owen",
    "tags": [
        "skills",
        "authoring",
        "documentation",
        "productivity",
        "agent"
    ],
    "category": "general",
    "quality_tier": "aggregated",
    "requires_env": [],
    "dependencies": [
        "@rapp/basic-agent"
    ],
    "mirrors": "skill_authoring_coach.md",
    "source_url": "https://microsoft.github.io/cat-agent-skills/#skill-authoring-coach",
    "source_license": "MIT",
    "converted_from": "CAT Agent Skills"
}
# ===============================================================

try:  # cloud layout (agents package)
    from agents.basic_agent import BasicAgent
except ImportError:  # local brainstem / standalone layout
    import os
    import sys

    sys.path.insert(0, os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "..",
        "agents", "@aibast-agents-library", "templates"))
    from basic_agent import BasicAgent


# The skill body, embedded verbatim. This is what makes the export single-file:
# the procedure travels with the agent rather than being fetched at call time.
SKILL_PROCEDURE = """# Skill Authoring Coach

> **Converted skill.** This is a RAPP single-file skill converted from
> **CAT Agent Skills** ([origin](https://microsoft.github.io/cat-agent-skills/#skill-authoring-coach)), redistributed under
> **MIT** with attribution. Original author: Simon Owen.
> Upstream license text: https://raw.githubusercontent.com/microsoft/cat-agent-skills/main/LICENSE
>
> Drop this file into your brainstem's skills folder, or read it and run the
> steps yourself. Everything the skill needs is in this one file.

## When to use this

Use this skill when the user asks to create, improve, review, package, genericise, or submit an Agent Skill, SKILL.md file, skill metadata, or reusable agent instruction bundle.

## The deterministic layer

RAPP skills state their contract explicitly, so two runs of the same skill do
the same thing:

- **Inputs** — whatever the steps below name. If an input is missing, say so
  and stop rather than guessing.
- **Outputs** — the artifact the steps produce, named where it is written.
- **Verification** — before reporting success, confirm the output exists and
  matches what was asked. A silent partial result is a failure.
- **Configuration** — never hardcode an endpoint, key, or tenant. Read them
  from the environment (`requires_env` above lists what this skill needs).

## Skill

# Skill Authoring Coach

Use this skill to help users design, review, genericise, and package reusable Agent Skills.

## Purpose

A good skill is not a long prompt dump. It is a focused, reusable capability with:

- A clear trigger description.
- Practical step-by-step instructions.
- Guardrails and edge cases.
- Optional references, assets, or scripts.
- A compact structure that an agent can load when needed.

## Skill vs reference vs template

Use these distinctions:

- **Skill** - Teaches the agent how to perform a repeatable task or workflow.
- **Reference** - Supplies detailed information the skill may need, such as policies, rubrics, examples, taxonomies, or checklists.
- **Template** - Supplies a reusable output shape or file structure.
- **Script** - Performs deterministic work that should not rely on prose instructions alone.

If the user tries to put everything into `SKILL.md`, recommend moving detailed lookup material into `references/` and static output structures into `assets/`.

## Recommended skill shape

```text
<skill-folder>/
├── SKILL.md
├── references/      optional
├── assets/          optional
└── scripts/         optional
```

The `SKILL.md` should contain:

1. Frontmatter with `name` and `description`.
2. A short explanation of when to use the skill.
3. Inputs to look for.
4. Workflow steps.
5. Output formats.
6. Guardrails and quality checks.

## Workflow

1. Identify the workflow the user wants to package.
2. Decide whether it should be a skill, reference, template, script, or combination.
3. Write or improve the skill trigger description.
4. Keep instructions concise and operational.
5. Move long examples and detailed reference material out of `SKILL.md` where appropriate.
6. Check for sensitive, organisation-specific, or non-reusable content.
7. Produce a candidate folder structure and files.

## Review rubric

Score candidate skills from 0 to 5 on:

1. **Trigger clarity** - Will the agent know when to use it?
2. **Task focus** - Is it one coherent capability?
3. **Instruction quality** - Are the steps clear and repeatable?
4. **Portability** - Can others use it without private assumptions?
5. **Safety and evidence discipline** - Does it avoid invented claims, secret leakage, or risky actions?
6. **Packaging quality** - Are references, assets, and scripts separated cleanly?

## Output format for review

```markdown
## Skill review

Overall recommendation: [Submit / Revise / Keep private]

| Dimension | Score /5 | Notes |
|---|---:|---|

## Required changes

1. [Change]
2. [Change]
3. [Change]

## Suggested folder structure

```text
[folder tree]
```
```


## References

This skill includes supporting reference material. Read the relevant reference file when the task needs additional structure, rubric detail, examples, or checklist support.

- `references/skill-design-checklist.md` - use this when additional structure, examples, or checks are useful for the task.

## Quality checklist

Before responding, check:

- The proposed skill has a clear reusable job.
- The trigger description is precise.
- Organisation-specific material is removed or parameterised.
- Long reference content is not overloaded into the main skill file.
- The result is practical for a maker to copy into a skills repository.

---

*Converted for the AIBAST Agents Library from CAT Agent Skills.
The original is authoritative; this file adds the RAPP manifest and the
deterministic layer above, and changes nothing else about the instructions.*
"""

SKILL_REF = "@cat-agent-skills/skill_authoring_coach"
SKILL_LICENSE = "MIT"
SKILL_SOURCE = "https://microsoft.github.io/cat-agent-skills/#skill-authoring-coach"


class SkillAuthoringCoachAgent(BasicAgent):
    """Delivers a verified RAPP procedure as a callable tool.

    Inputs — none required. `context` optionally narrows the returned
        procedure to a stated situation; it is echoed back, never invented.
    Output — the full skill procedure as text: inputs, outputs, and the
        verification step the caller must perform before reporting success.
    Verification — the caller confirms the artifact named by the procedure
        exists and matches what was asked. This agent returns instructions; it
        does not perform the work described in them, and it never reports
        success on the caller's behalf.
    Configuration — none. The procedure is embedded in this file.
    """

    def __init__(self):
        self.name = "Skill Authoring Coach"
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "context": {
                        "type": "string",
                        "description": (
                            "Optional. The specific situation the procedure is "
                            "being applied to, echoed back with the steps — for "
                            "example 'a 40-slide deck for an external customer'."
                        ),
                    }
                },
                "required": [],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        context = (kwargs.get("context") or "").strip()
        header = [
            f"# {self.name} — RAPP procedure",
            "",
            f"Source: {SKILL_REF} · redistributed under {SKILL_LICENSE} "
            f"with attribution ({SKILL_SOURCE}).",
        ]
        if context:
            header += ["", f"**Applied to:** {context}"]
        header += [
            "",
            "Follow the steps below exactly. Where a step names an input you "
            "do not have, say so and stop rather than guessing, and complete "
            "the verification step before reporting success.",
            "",
            "---",
            "",
        ]
        return "\n".join(header) + SKILL_PROCEDURE
