"""
Vendor Contract Risk Review — RAPP agent, mirrored from vendor_contract_risk_review.md

This file is GENERATED from its skill.md by scripts/export_agent.py and is one
half of a matched pair. The manifest below and the procedure embedded further
down are identical to the ones in the .md; the only difference is the runtime:
a model reads the .md, a brainstem registers this .py and calls it as a tool.

Do not edit this file. Edit vendor_contract_risk_review.md and re-run the exporter — the gate
re-derives this file and fails if the two have drifted apart.

Redistributed from CAT Agent Skills under MIT
with attribution. Original author: Tim Karlsson.
Origin: https://microsoft.github.io/cat-agent-skills/#vendor-contract-risk-review
"""

# ===============================================================
# RAPP AGENT MANIFEST - Do not remove. Used by registry builder.
# ===============================================================
__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@cat-agent-skills/vendor_contract_risk_review",
    "version": "1.0.0",
    "display_name": "Vendor Contract Risk Review",
    "description": "Returns the verified RAPP procedure for: First-pass review of a vendor contract or SOW for the clauses that commonly cause problems (auto-renewal, liability caps, termination, IP ownership), flagged by risk level to prepare for legal review, not replace it. Call this to obtain the full step-by-step contract (inputs, outputs, verification) and then carry out those steps.",
    "author": "Tim Karlsson",
    "tags": [
        "contracts",
        "legal",
        "procurement",
        "risk",
        "vendor-management",
        "review"
    ],
    "category": "it_management",
    "quality_tier": "aggregated",
    "requires_env": [],
    "dependencies": [
        "@rapp/basic-agent"
    ],
    "mirrors": "vendor_contract_risk_review.md",
    "source_url": "https://microsoft.github.io/cat-agent-skills/#vendor-contract-risk-review",
    "source_license": "MIT",
    "converted_from": "CAT Agent Skills"
}
# ===============================================================

try:  # cloud layout (agents package)
    from agents.basic_agent import BasicAgent
except ImportError:  # local brainstem / standalone layout
    import os
    import sys

    sys.path.insert(0, os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "..", "..",
        "agents", "@aibast-agents-library", "templates"))
    from basic_agent import BasicAgent


# The skill body, embedded verbatim. This is what makes the export single-file:
# the procedure travels with the agent rather than being fetched at call time.
SKILL_PROCEDURE = """# Vendor Contract Risk Review

> **Converted skill.** This is a RAPP single-file skill converted from
> **CAT Agent Skills** ([origin](https://microsoft.github.io/cat-agent-skills/#vendor-contract-risk-review)), redistributed under
> **MIT** with attribution. Original author: Tim Karlsson.
> Upstream license text: https://raw.githubusercontent.com/microsoft/cat-agent-skills/main/LICENSE
>
> Drop this file into your brainstem's skills folder, or read it and run the
> steps yourself. Everything the skill needs is in this one file.

## When to use this

Use this skill whenever a user shares a vendor contract, SOW, or supplier agreement draft and wants a first-pass risk review before it goes to legal, before recommending any change to contract terms.

## The deterministic layer

RAPP skills state their contract explicitly, so two runs of the same skill do
the same thing:

- **Inputs** — whatever the steps below name. If an input is missing, say so
  and stop rather than guessing.
- **Outputs** — the artifact the steps produce, named where it is written.
- **Verification** — before reporting success, confirm the output exists and
  matches what was asked. A silent partial result is a failure.
- **Configuration** — never hardcode an endpoint, key, or tenant. Read them
  from the environment (`requires_env` above lists what this skill needs).

## Skill

Read the contract for the clauses that commonly cause problems later, flag
them clearly, and never present this as a substitute for legal review.

## Instructions

1. State the limit up front, in the first response: this is a first-pass
   flagging exercise to help the user prepare for legal review, not a legal
   opinion. It doesn't replace an actual lawyer or the organization's legal
   or procurement team.

2. Get the contract text (uploaded document or pasted text). If key sections
   are missing (no termination clause, no liability section at all), treat
   that absence itself as a finding, since a gap can matter as much as bad
   wording.

3. Read for the clauses that commonly cause disputes or unwelcome surprises:
   - **Auto-renewal**: does the contract renew automatically, and if so, how
     much notice is required to opt out, and by when?
   - **Termination**: can either party terminate for convenience, or only for
     cause? What notice period applies? Is there an early-termination fee?
   - **Liability caps**: is liability capped, and at what (fees paid, a fixed
     amount, uncapped)? Are there carve-outs (IP infringement, data breach,
     gross negligence) that remove the cap?
   - **Indemnification**: who indemnifies whom, and for what? Is it mutual or
     one-sided?
   - **Data and IP**: who owns data generated during the engagement? What
     happens to it on termination? Who owns work product or deliverables?
   - **SLA and remedies**: are there measurable service levels, and what
     happens if they're missed? Credits, termination right, or nothing
     stated?
   - **Pricing and escalation**: is pricing fixed for the term, or can it
     change? If it can escalate, is there a cap on the increase?
   - **Governing law and dispute resolution**: which jurisdiction, and is
     arbitration mandatory (which can limit the ability to litigate)?
   - **Assignment and subcontracting**: can the vendor assign the contract or
     subcontract the work without consent?

4. Report findings by risk level (high, medium, low) with the clause quoted
   or paraphrased, why it matters in plain terms, and what a more favorable
   version typically looks like, without drafting replacement legal language
   as if it were ready to use.

5. Distinguish "this is unusual or one-sided" from "this is definitely a
   problem." Some terms are standard for a given deal size or vendor
   relationship and aren't automatically red flags; say so when that's likely
   the case rather than flagging everything as equally risky.

6. Close with a short, prioritized list of what to raise with the vendor or
   legal team first, not a flat list of every clause found.

## Guardrails

- Never present findings as legal advice or a legal opinion. Every response
  should make clear this is preparation for a human legal or procurement
  review, not a substitute for it.
- Never draft final contract language for the user to send back to a vendor
  as if it were legally sound. Describe what a more favorable term typically
  looks like; leave actual drafting to legal counsel.
- Don't flag standard, unremarkable terms as high risk just to appear
  thorough. Over-flagging buries the findings that actually matter.
- If the contract involves a regulated area (data privacy, healthcare,
  financial services, government), say plainly that specialized legal review
  is needed beyond this general pass.

## Tone

Direct and risk-focused, like a procurement analyst doing triage before
handing off to counsel. Plain language over legal jargon wherever possible.

---

*Converted for the AIBAST Agents Library from CAT Agent Skills.
The original is authoritative; this file adds the RAPP manifest and the
deterministic layer above, and changes nothing else about the instructions.*
"""

SKILL_REF = "@cat-agent-skills/vendor_contract_risk_review"
SKILL_LICENSE = "MIT"
SKILL_SOURCE = "https://microsoft.github.io/cat-agent-skills/#vendor-contract-risk-review"


class VendorContractRiskReviewAgent(BasicAgent):
    """Delivers a verified RAPP procedure as a callable tool.

    Inputs — none required. `context` optionally narrows the returned
        procedure to a stated situation; it is echoed back, never invented.
    Output — the full skill procedure as text: inputs, outputs, and the
        verification step the caller must perform before reporting success.
    Verification — the caller confirms the artifact named by the procedure
        exists and matches what was asked. This agent returns instructions; it
        does not perform the work described in them, and it never reports
        success on the caller's behalf.
    Configuration — none. The procedure is embedded in this file.
    """

    def __init__(self):
        self.name = "Vendor Contract Risk Review"
        self.metadata = {
            "name": self.name,
            "description": __manifest__["description"],
            "parameters": {
                "type": "object",
                "properties": {
                    "context": {
                        "type": "string",
                        "description": (
                            "Optional. The specific situation the procedure is "
                            "being applied to, echoed back with the steps — for "
                            "example 'a 40-slide deck for an external customer'."
                        ),
                    }
                },
                "required": [],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        context = (kwargs.get("context") or "").strip()
        header = [
            f"# {self.name} — RAPP procedure",
            "",
            f"Source: {SKILL_REF} · redistributed under {SKILL_LICENSE} "
            f"with attribution ({SKILL_SOURCE}).",
        ]
        if context:
            header += ["", f"**Applied to:** {context}"]
        header += [
            "",
            "Follow the steps below exactly. Where a step names an input you "
            "do not have, say so and stop rather than guessing, and complete "
            "the verification step before reporting success.",
            "",
            "---",
            "",
        ]
        return "\n".join(header) + SKILL_PROCEDURE
