"""Focused contracts for canonical, generated blog content."""

from __future__ import annotations

import importlib.util
import json
import re
import subprocess
import sys
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PIPELINE = ROOT / "scripts" / "blog_pipeline.py"
SUBMISSIONS = ROOT / "submissions" / "blog"


def load_pipeline():
    spec = importlib.util.spec_from_file_location("blog_pipeline", PIPELINE)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


class BlogPipelineTests(unittest.TestCase):
    def test_canonical_submissions_validate(self):
        pipeline = load_pipeline()
        submissions, errors = pipeline.validate_all(SUBMISSIONS)
        self.assertEqual([], errors)
        self.assertGreaterEqual(len(submissions), 3)

    def test_generated_blog_has_no_drift(self):
        result = subprocess.run(
            [sys.executable, str(PIPELINE), "check"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
        self.assertEqual(0, result.returncode, result.stdout + result.stderr)
        blog = (ROOT / "blog.html").read_text(encoding="utf-8")
        self.assertIn("<!-- blog-posts:begin -->", blog)
        self.assertIn("<!-- Generated by scripts/blog_pipeline.py; do not hand-edit. -->", blog)
        self.assertIn('href="#device-code-login-race"', blog)
        self.assertIn("Applicability", blog)
        self.assertIn("Support boundary", blog)
        self.assertNotIn("<p># How a background thread", blog)
        self.assertNotIn("<strong>Try this:</strong> </p>", blog)

    def test_renderer_changes_a_stale_generated_region(self):
        pipeline = load_pipeline()
        submissions, errors = pipeline.validate_all(SUBMISSIONS)
        self.assertEqual([], errors)
        stale = f"before\n{pipeline.BEGIN}\nstale\n{pipeline.END}\nafter\n"
        rendered = pipeline.replace_region(stale, pipeline.render_region(submissions))
        self.assertNotEqual(stale, rendered)
        self.assertIn("Generated by scripts/blog_pipeline.py", rendered)

    def test_staging_submission_schema_is_accepted(self):
        pipeline = load_pipeline()
        metadata = {
            "schema": "aibast-blog/1.0",
            "contribution_type": "blog_post",
            "slug": "staging-example",
            "title": "A reproducible staging example",
            "author": "Alex Rivera (@alex-rivera)",
            "date": "2026-08-15",
            "status": "staging",
            "publication": "generated-from-canonical-submission",
            "summary": "A sufficiently detailed concrete problem summary for the generated staging preview.",
            "audience": "Solution architects reviewing a staged contribution workflow.",
            "prerequisites": "A local checkout, GitHub access, and a reviewed generated submission.",
            "applicability": "Applies to staging contributions that need a generated public review path.",
            "support_boundary": "Schema validation only; it does not grant production support or publish content.",
            "limitations": "This example validates a schema only and does not prove production publishing or tenant compatibility.",
            "tags": ["staging", "governance"],
            "evidence": [{"label": "Evidence", "url": "https://example.com/evidence"}],
            "links": [{"label": "Source", "url": "https://example.com/source"}],
        }
        post = "\n\n".join([
            "## Concrete problem",
            " ".join(["problem"] * 55),
            "## Technical approach",
            " ".join(["approach"] * 55),
            "## Reproduce",
            " ".join(["reproduce"] * 55),
            "## Evidence",
            " ".join(["evidence"] * 55),
            "## Limitations",
            " ".join(["limitations"] * 55),
            "## Action",
            " ".join(["action"] * 55),
        ])
        submission = pipeline.Submission(Path("submissions/blog/staging-example"), metadata, post)
        self.assertEqual([], pipeline.validate_submission(submission))

    def test_future_date_anonymous_author_h1_and_empty_action_fail(self):
        pipeline = load_pipeline()
        metadata = {
            "schema": "aibast-blog/1.0",
            "contribution_type": "blog_post",
            "slug": "invalid-example",
            "title": "Invalid example for mutation coverage",
            "author": "Anonymous",
            "date": "2999-01-01",
            "status": "staging",
            "publication": "generated-from-canonical-submission",
            "summary": "A sufficiently detailed summary for validating rejected mutations.",
            "audience": "Readers validating canonical source quality rules.",
            "prerequisites": "A local checkout and the canonical blog validator.",
            "applicability": "Applies to generated blog content that has a metadata title.",
            "support_boundary": "Validation only; this does not grant publishing or support.",
            "limitations": "This mutation fixture is intentionally invalid and cannot be published.",
            "tags": ["staging", "mutation"],
            "evidence": [{"label": "Evidence", "url": "https://example.com/evidence"}],
            "links": [{"label": "Source", "url": "https://example.com/source"}],
        }
        post = "\n\n".join([
            "# Illegal duplicate title",
            "## Concrete problem",
            " ".join(["problem"] * 55),
            "## Technical approach",
            " ".join(["approach"] * 55),
            "## Reproduce",
            " ".join(["reproduce"] * 55),
            "## Evidence",
            " ".join(["evidence"] * 55),
            "## Limitations",
            " ".join(["limitations"] * 55),
            "## Action",
        ])
        submission = pipeline.Submission(Path("submissions/blog/invalid-example"), metadata, post)
        errors = pipeline.validate_submission(submission)
        self.assertTrue(any("future" in error for error in errors))
        self.assertTrue(any("named individual" in error for error in errors))
        self.assertTrue(any("must not include H1" in error for error in errors))
        self.assertTrue(any("Action section" in error for error in errors))

    def test_issue_handoff_uses_raw_marker_not_form_autofill(self):
        library = (ROOT / "library.html").read_text(encoding="utf-8")
        self.assertIn("<!-- aibast-blog-submission:v1 -->", library)
        self.assertNotIn('url.searchParams.set("template", "blog-submission.yml")', library)
        self.assertFalse((ROOT / ".github" / "workflows" / "blog-submission.yml").exists())

    def test_contribution_handoff_uses_real_newlines_and_distribution_owner(self):
        library = (ROOT / "library.html").read_text(encoding="utf-8")
        literal_backslash_join = re.compile(r"""\.join\(\s*["']\\\\n["']\s*\)""")
        self.assertIsNone(literal_backslash_join.search(library))
        self.assertIn('].join("\\n"));', library)
        self.assertIn("const DISTRIBUTION_OWNER = location.hostname.endsWith", library)
        self.assertIn("https://github.com/${DISTRIBUTION_OWNER}/${REPO}/issues/new", library)
        self.assertIn("https://github.com/${DISTRIBUTION_OWNER}/${REPO}/discussions/new", library)
        self.assertNotIn("https://github.com/${OWNER}/${REPO}/issues/new", library)
        self.assertNotIn("https://github.com/${OWNER}/${REPO}/discussions/new", library)

    def test_generic_author_placeholders_are_rejected(self):
        pipeline = load_pipeline()
        metadata = {
            "schema": "aibast-blog/1.0",
            "contribution_type": "blog_post",
            "slug": "author-mutation",
            "title": "Author mutation coverage example",
            "author": "Alex Rivera (@alex-rivera)",
            "date": "2026-08-15",
            "status": "staging",
            "publication": "generated-from-canonical-submission",
            "summary": "A sufficiently detailed concrete problem summary for the generated staging preview.",
            "audience": "Solution architects reviewing a staged contribution workflow.",
            "prerequisites": "A local checkout, GitHub access, and a reviewed generated submission.",
            "applicability": "Applies to staging contributions that need a generated public review path.",
            "support_boundary": "Schema validation only; it does not grant production support or publish content.",
            "limitations": "This mutation fixture validates author rules and does not prove production publishing or tenant compatibility.",
            "tags": ["staging", "governance"],
            "evidence": [{"label": "Evidence", "url": "https://example.com/evidence"}],
            "links": [{"label": "Source", "url": "https://example.com/source"}],
        }
        post = "\n\n".join([
            "## Concrete problem", " ".join(["problem"] * 55),
            "## Technical approach", " ".join(["approach"] * 55),
            "## Reproduce", " ".join(["reproduce"] * 55),
            "## Evidence", " ".join(["evidence"] * 55),
            "## Limitations", " ".join(["limitations"] * 55),
            "## Action", " ".join(["action"] * 55),
        ])
        for author in ("AIBAST", "AIBAST Engineering", "Team", "RAPP", "Anonymous", "Unknown", "N/A"):
            with self.subTest(author=author):
                metadata["author"] = author
                submission = pipeline.Submission(Path("submissions/blog/author-mutation"), metadata.copy(), post)
                errors = pipeline.validate_submission(submission)
                self.assertTrue(any("named individual" in error for error in errors), errors)

    def test_renderer_escapes_url_ampersands_once_and_renders_nested_headings_safely(self):
        pipeline = load_pipeline()
        linked = pipeline.inline_markdown("[Reference](https://example.com/path?a=1&b=2)")
        self.assertIn('href="https://example.com/path?a=1&amp;b=2"', linked)
        self.assertNotIn("&amp;amp;", linked)
        rendered = pipeline.render_markdown(
            "## Technical approach\n\n"
            "A safe section.\n\n"
            "### Detail <script>alert(1)</script>\n\n"
            "A safe subsection."
        )
        self.assertIn("<h3>Technical approach</h3>", rendered)
        self.assertIn("<h4>Detail &lt;script&gt;alert(1)&lt;/script&gt;</h4>", rendered)
        self.assertNotIn("<p>###", rendered)

    def test_arbitrary_legacy_html_is_rejected_and_not_raw_rendered(self):
        pipeline = load_pipeline()
        metadata = {
            "schema": "aibast-blog/1.0",
            "contribution_type": "blog_post",
            "slug": "untrusted-legacy-html",
            "title": "Untrusted legacy HTML mutation",
            "author": "Alex Rivera (@alex-rivera)",
            "date": "2026-08-15",
            "status": "published",
            "publication": "generated-from-canonical-submission",
            "legacy_html": True,
            "summary": "A sufficiently detailed concrete problem summary for the generated staging preview.",
            "audience": "Solution architects reviewing a staged contribution workflow.",
            "prerequisites": "A local checkout, GitHub access, and a reviewed generated submission.",
            "applicability": "Applies to staging contributions that need a generated public review path.",
            "support_boundary": "Schema validation only; it does not grant production support or publish content.",
            "limitations": "This mutation fixture validates raw HTML restrictions and does not prove production publishing or tenant compatibility.",
            "tags": ["staging", "security"],
            "evidence": [{"label": "Evidence", "url": "https://example.com/evidence"}],
            "links": [{"label": "Source", "url": "https://example.com/source"}],
        }
        post = "<img src=x onerror=alert(1)> " + " ".join(["history"] * 260)
        submission = pipeline.Submission(Path("submissions/blog/untrusted-legacy-html"), metadata, post)
        errors = pipeline.validate_submission(submission)
        self.assertTrue(any("restricted to migrated historical" in error for error in errors), errors)
        self.assertTrue(any("active content" in error for error in errors), errors)
        rendered = pipeline.render_submission(submission)
        self.assertIn("&lt;img", rendered)
        self.assertNotIn("<img src=x", rendered)

    def test_contribution_ui_is_no_secret_handoff(self):
        library = (ROOT / "library.html").read_text(encoding="utf-8")
        for field in (
            "contribution-author",
            "contribution-date",
            "contribution-audience",
            "contribution-prerequisites",
            "contribution-problem",
            "contribution-approach",
            "contribution-reproduce",
            "contribution-evidence",
            "contribution-limitations",
            "contribution-applicability",
            "contribution-support-boundary",
            "contribution-action",
            "contribution-tags",
            "contribution-links",
            "contribution-article",
        ):
            self.assertIn(field, library)
        self.assertIn("generated_public_content_only", library)
        self.assertIn("GitHub Pages has no safe server-side identity", library)
        self.assertIn('schema: "aibast-blog/1.0"', library)
        self.assertIn('publication: "generated-from-canonical-submission"', library)
        self.assertNotIn("api.github.com", library)

    def test_current_release_is_structurally_distinct_from_history(self):
        notes = (ROOT / "release-notes.html").read_text(encoding="utf-8")
        self.assertIn('id="v0-6-16"', notes)
        self.assertIn("v0.6.16", notes)
        self.assertIn("Current</span>", notes)
        self.assertIn("Historical</span>", notes)
        self.assertNotIn(">Latest</span>", notes)
        self.assertIn('href="blog.html">Engineering Notes</a>', (ROOT / "index.html").read_text(encoding="utf-8"))

    def test_remote_agent_note_has_dated_nonpromise_status(self):
        metadata = json.loads((SUBMISSIONS / "local-agent-boundaries" / "metadata.json").read_text(encoding="utf-8"))
        self.assertIn("2026-08-15", metadata["status_note"])
        self.assertIn("no remote-agent return is scheduled or committed", metadata["status_note"])


if __name__ == "__main__":
    unittest.main()
