"""Read-only contract checks and permanent mutations of in-memory source copies."""
import copy
import importlib.util
import json
import re
import subprocess
import sys
from pathlib import Path, PurePosixPath

import pytest


ROOT = Path(__file__).resolve().parent.parent
PILOTS = ("ask-hr", "building-permit-processing")
ARTIFACTS = (
    "0.Resources/README.md", "1.Overview.md", "2.Architecture.md",
    "3.Runbook.md", "4.Sample-prompts.md",
)
OPTIONAL = ("5.Acceptance-Evidence.md",)
SECTIONS = {
    "0.Resources/README.md": ("Package Resources", "Workshop Pages", "Evidence and Exports", "Sources"),
    "1.Overview.md": (
        "Scenario Overview", "Problem Statement", "Solution Summary", "Business Outcomes",
        "Target Users", "In Scope / Out of Scope", "Qualification Checklist",
        "What Actually Goes Wrong", "Related Patterns", "Sources", "Next",
    ),
    "2.Architecture.md": (
        "Solution Architecture", "Component Responsibilities", "Required Connections",
        "Copilot Studio Components", "Data and Evidence Boundary",
        "Production Replacement Seams", "Design Decisions", "Sources", "Next",
    ),
    "3.Runbook.md": (
        "Prerequisites", "Phase 1 — Easy Mode with GitHub Copilot",
        "Phase 2 — Optional Brainstem Track", "Phase 3 — Manual Build in Copilot Studio",
        "Phase 4 — Acceptance", "Phase 5 — Production Hardening", "Failure Recovery",
        "Deliverables Checklist", "Sources", "Next",
    ),
    "4.Sample-prompts.md": (
        "Suggested Agent Instructions", "Demo Prompts", "Promise-to-Prompt Map",
        "Expected Results", "Routing and Boundary Cases", "What This Agent Should Never Do",
        "Sources", "Next",
    ),
    "5.Acceptance-Evidence.md": (
        "Evidence Summary", "Release Gate Status", "Visual Evidence", "Sources", "Next",
    ),
}
MARKER = "<!-- Generated by tools/build_solution_runbooks.py. Do not edit; change the sources and regenerate. -->"
TAXONOMY_BEGIN = "<!-- BEGIN GENERATED: solution-taxonomy (tools/build_solution_runbooks.py) -->"
TAXONOMY_END = "<!-- END GENERATED: solution-taxonomy -->"
OWNED = ("00-overview/", "01-solutions/", "02-patterns/", "03-references/", "build_solution_runbooks.py")
TOUCHED = ("README.md", "CLAUDE.md", "solutions/README.md", ".github/copilot-instructions.md", "CONTRIBUTING.md")
PREFIXES = ("00-overview/", "01-solutions/", "02-patterns/", "03-references/")
DEFAULT_PATTERNS = (
    "aibast:evidence-first-release-gate", "aibast:synthetic-snapshot-demo-agent",
    "runbooks:Human-in-the-Loop-Review-and-Approval",
    "runbooks:Agent-Publishing-and-Channel-Deployment",
)
RUNBOOKS_URL = "https://github.com/microsoft/ai-agent-runbooks/blob/main/"
REFERENCE_URLS = {
    RUNBOOKS_URL + "03-references/Agent-Delivery-Reference-Library.md",
    RUNBOOKS_URL + "03-references/Known-Limitations-and-Workarounds.md",
}
LEAK = re.compile(r"\b(?:None|null|nan|TODO|TBD|FIXME|undefined)\b|\{\}|\[\]|Lorem ipsum|<no value>")
HEADING = re.compile(r"^ {0,3}(#{1,6})[ \t]+(.*?)(?:[ \t]+#+)?[ \t]*$")


def load_module(name, filename):
    spec = importlib.util.spec_from_file_location(name, ROOT / "tools" / filename)
    assert spec is not None and spec.loader is not None, f"Cannot load tools/{filename}"
    module = importlib.util.module_from_spec(spec)
    old = sys.dont_write_bytecode
    sys.dont_write_bytecode = True
    try:
        spec.loader.exec_module(module)
    finally:
        sys.dont_write_bytecode = old
    return module


def read_json(relative):
    return json.loads((ROOT / relative).read_text(encoding="utf-8"))


def assert_clean(problems, context):
    assert not problems, f"{context}:\n" + "\n".join(str(problem) for problem in problems)


def validate_identity(catalog, packages, aliases, drafts):
    assert catalog, "Identity join cannot measure an empty catalogue"
    resolved = {}
    for key in sorted(catalog):
        assert key.startswith("@aibast-agents-library/"), f"Noncanonical catalogue key: {key}"
        name = key.split("/")[-1]
        matches = sorted(slug for slug, identity in packages.items() if identity == key)
        assert len(matches) == 1, f"{key}: expected exactly one deployment.json name match, found {matches}"
        slug = matches[0]
        expected = aliases.get(name, name)
        assert slug == expected, f"{key}: package slug {slug!r} != canonical/aliased {expected!r}"
        resolved[key] = slug
    orphans = set(packages) - set(resolved.values()) - set(drafts)
    assert not orphans, f"Orphan package directories: {sorted(orphans)}"
    for name, slug in aliases.items():
        key = "@aibast-agents-library/" + name
        assert key in catalog and name != slug and resolved.get(key) == slug, (
            f"Stale alias: {name!r} -> {slug!r}"
        )
    for slug, reason in drafts.items():
        assert slug in packages and slug not in resolved.values(), f"Stale draft allowlist entry: {slug}"
        assert isinstance(reason, str) and reason.strip(), f"{slug}: draft allowlist needs a reason"
    return resolved


def validate_patterns(data, readme, defaults):
    assert data.get("schema") == "aibast-pattern-index/1.0", "patterns.json: unsupported schema"
    assert isinstance(data.get("source"), str) and data["source"].strip(), "patterns.json: source must be text"
    ids = []
    for group, prefix, count in (("aibast_patterns", "aibast:", 8), ("runbooks_patterns", "runbooks:", 17)):
        entries = data.get(group)
        assert isinstance(entries, list), f"patterns.json: {group} must be a list"
        for entry in entries:
            assert isinstance(entry, dict), f"{group}: entry must be an object"
            identity = entry.get("id")
            assert isinstance(identity, str) and identity.startswith(prefix) and len(identity) > len(prefix), (
                f"{group}: invalid id {identity!r}"
            )
            assert identity not in ids, f"Duplicate pattern id: {identity}"
            ids.append(identity)
            for field in ("title", "folder") if prefix == "aibast:" else ("title", "url", "runbook_url"):
                assert isinstance(entry.get(field), str) and entry[field].strip(), f"{identity}: {field} must be text"
            assert entry["title"] in readme, f"02-patterns/README.md missing title: {entry['title']}"
            if prefix == "aibast:":
                assert entry.get("status") == "Planned", f"{identity}: native pattern must be Planned"
            else:
                for field in ("url", "runbook_url"):
                    assert re.fullmatch(
                        r"https://github\.com/microsoft/ai-agent-runbooks/blob/main/02-patterns/[^?#]+\.md",
                        entry[field],
                    ), f"{identity}: invalid {field}: {entry[field]!r}"
        assert len(entries) == count, f"{group}: expected {count} patterns, found {len(entries)}"
    assert set(defaults) <= set(ids), f"Unknown default pattern ids: {sorted(set(defaults) - set(ids))}"
    return set(ids)


def validate_notes(data, catalog, pattern_ids, files):
    assert data.get("schema") == "aibast-solution-runbook-notes/1.0", "runbook-notes.json: unsupported schema"
    assert isinstance(data.get("source"), str) and data["source"].strip(), "runbook-notes.json: source must be text"
    notes = data.get("solutions")
    assert isinstance(notes, dict), "runbook-notes.json: solutions must be an object"
    assert set(notes) <= set(catalog), f"Unknown notes catalogue keys: {sorted(set(notes) - set(catalog))}"
    string_lists = {"scope_in", "scope_out", "qualification_checklist", "related_patterns", "sources"}
    object_lists = {"target_users": {"role", "need"}, "what_goes_wrong": {"issue", "response"}}
    allowed = string_lists | set(object_lists)
    for key, entry in notes.items():
        assert isinstance(entry, dict), f"{key}: notes must be an object"
        assert not set(entry) - allowed, f"{key}: unknown notes fields {sorted(set(entry) - allowed)}"
        if set(entry) - {"sources"}:
            assert entry.get("sources"), f"{key}: sources required when another notes field is present"
        for field, values in entry.items():
            assert isinstance(values, list), f"{key}.{field}: expected list"
            for value in values:
                if field in string_lists:
                    assert isinstance(value, str) and value.strip(), f"{key}.{field}: expected nonempty strings"
                else:
                    assert isinstance(value, dict) and set(value) == object_lists[field], (
                        f"{key}.{field}: expected objects with {sorted(object_lists[field])}"
                    )
                    assert all(isinstance(text, str) and text.strip() for text in value.values()), (
                        f"{key}.{field}: object values must be nonempty strings"
                    )
        for source in entry.get("sources", []):
            assert not PurePosixPath(source).is_absolute() and ".." not in PurePosixPath(source).parts, (
                f"{key}: notes source must be repository-relative: {source}"
            )
            assert source in files, f"{key}: missing notes source: {source}"
        for identity in entry.get("related_patterns", []):
            assert identity in pattern_ids, f"{key}: unknown pattern id: {identity}"


def validate_journeys(catalog, stages, normalize):
    assert isinstance(stages, tuple) and stages, "JOURNEY_STAGES must be a nonempty tuple"
    assert stages == tuple(sorted(set(stages))), "JOURNEY_STAGES must be sorted and unique"
    primaries = set()
    for key, entry in catalog.items():
        value = entry.get("journey_stage")
        assert isinstance(value, str) and value.strip(), f"{key}: journey_stage must be nonempty text"
        pieces = value.split(" and ", 1)
        expected = tuple(piece.strip()[:1].upper() + piece.strip()[1:] for piece in pieces)
        primary, secondary = expected[0], expected[1] if len(expected) == 2 else None
        assert primary in stages, f"{key}: unknown journey stage: {primary}"
        assert normalize(value) == (primary, secondary), f"{key}: incorrect normalization of {value!r}"
        primaries.add(primary)
    assert set(stages) == primaries, f"Stale journey stages: {sorted(set(stages) - primaries)}"


def validate_projection(expected, actual):
    assert expected and "01-solutions/README.md" in expected, "Cannot measure an empty generated projection"
    expected_files = {path for path in expected if path.startswith("01-solutions/")}
    actual_files = {path for path in actual if path.startswith("01-solutions/")}
    assert not actual_files - expected_files, f"Extra generated files: {sorted(actual_files - expected_files)}"
    assert not expected_files - actual_files, f"Missing generated files: {sorted(expected_files - actual_files)}"
    for path in sorted(expected_files):
        assert actual[path] == expected[path], f"Changed generated content: {path}"
    assert actual.get("00-overview/README.md") == expected.get("00-overview/README.md"), "Taxonomy content drift"


def validate_generated_document(path, text, links):
    assert text.startswith(MARKER + "\n"), f"{path}: generated marker must be the first line"
    assert "\r" not in text and text.endswith("\n") and not text.endswith("\n\n"), (
        f"{path}: require LF endings and exactly one trailing newline"
    )
    visible = links.strip_code(text, inline=False).splitlines()
    headings = [(index, match[1], match[2]) for index, line in enumerate(visible) if (match := HEADING.match(line))]
    artifact = path.split("/", 2)[2] if path.count("/") >= 2 else None
    if artifact in SECTIONS:
        actual = tuple(title for _, level, title in headings if level == "##")
        assert actual == SECTIONS[artifact], f"{path}: H2 order/titles {actual!r} != {SECTIONS[artifact]!r}"
    content_lines = links.strip_code(text, inline=False, fence_fill="\x00code").splitlines()
    for index, level, title in headings:
        stop = next((i for i, other, _ in headings if i > index and len(other) <= len(level)), len(content_lines))
        body = "\n".join(content_lines[index + 1:stop])
        body = re.sub(r"(?m)^\s*(?:[-*_]{3,}|`{3,}|~{3,})\s*$", "", body)
        assert body.strip(), f"{path}: empty section {title!r}"
    for number, line in enumerate(links.strip_code(text).splitlines(), 1):
        match = LEAK.search(line)
        assert match is None, f"{path}:{number}: placeholder/value leak {match[0]!r}" if match else ""


def validate_owned_surfaces(documents):
    for path in ("CLAUDE.md", ".github/copilot-instructions.md"):
        assert path in documents, f"Missing owned-surface document: {path}"
        for token in OWNED:
            assert token in documents[path], f"{path}: missing owned-surface declaration {token!r}"


def validate_taxonomy(catalog, overview, index):
    assert overview.count(TAXONOMY_BEGIN) == 1, "Taxonomy begin marker must occur exactly once"
    assert overview.count(TAXONOMY_END) == 1, "Taxonomy end marker must occur exactly once"
    assert overview.index(TAXONOMY_BEGIN) < overview.index(TAXONOMY_END), "Taxonomy markers are reversed"
    block = overview.split(TAXONOMY_BEGIN)[1].split(TAXONOMY_END)[0]
    for key, entry in catalog.items():
        name = entry["display_name"]
        assert name and name in block, f"Taxonomy missing {key}: {name}"
        assert name in index, f"Runbook index missing {key}: {name}"
    for slug in PILOTS:
        assert re.search(r"\((?:\./)?" + re.escape(slug) + r"/1\.Overview\.md\)", index), (
            f"Runbook index missing pilot link: {slug}"
        )
    assert "grid-outage-response" in index, "Runbook index must explain the allowlisted draft"


@pytest.fixture(scope="module")
def generator():
    return load_module("solution_runbooks_under_test", "build_solution_runbooks.py")


@pytest.fixture(scope="module")
def links():
    return load_module("markdown_links_under_test", "markdown_links.py")


@pytest.fixture(scope="module")
def sources(links):
    files = links.git_file_universe(ROOT)
    catalog = read_json("solutions/catalog.json")["solutions"]
    packages = {}
    for path in sorted((ROOT / "solutions").iterdir()):
        if path.is_dir() and path.name != "_shared":
            relative = f"solutions/{path.name}/deployment.json"
            packages[path.name] = read_json(relative).get("name") if relative in files else None
    return {
        "files": files, "catalog": catalog, "packages": packages,
        "patterns": read_json("02-patterns/patterns.json"),
        "notes": read_json("solutions/runbook-notes.json"),
    }


@pytest.fixture(scope="module")
def slugs(generator, sources):
    joined = validate_identity(
        sources["catalog"], sources["packages"], generator.PACKAGE_ALIASES, generator.DRAFT_PACKAGES,
    )
    return tuple(sorted(joined.values()))


@pytest.fixture(scope="module")
def library(generator):
    return generator.load_library(ROOT)


@pytest.fixture(scope="module")
def all_outputs(generator, slugs):
    return generator.build_outputs(ROOT, solutions=slugs)


@pytest.fixture(scope="module")
def pilot_outputs(generator):
    return generator.build_outputs(ROOT)


@pytest.fixture(scope="module")
def disk_docs(sources):
    return {
        path: (ROOT / path).read_bytes().decode("utf-8")
        for path in sources["files"]
        if path.endswith(".md") and (path.startswith(PREFIXES) or path in TOUCHED)
    }


def pattern_ids(sources):
    return {
        pattern["id"]
        for group in ("aibast_patterns", "runbooks_patterns")
        for pattern in sources["patterns"][group]
    }


def allowed_runbooks(sources):
    return REFERENCE_URLS | {
        entry[field] for entry in sources["patterns"]["runbooks_patterns"]
        for field in ("url", "runbook_url")
    }


def expected_artifacts(slug, files):
    evidence = any(
        PurePosixPath(path).match(f"solutions/{slug}/evals/*evidence*.json")
        or path == f"solutions/{slug}/evals/visual-checkpoints.json"
        for path in files
    )
    return set(ARTIFACTS) | (set(OPTIONAL) if evidence else set())


def test_generator_public_contract(generator):
    assert generator.RUNBOOK_SOLUTIONS == PILOTS, "Phase 1 must write exactly both pilots"
    assert generator.ARTIFACTS == ARTIFACTS, "Required artifact names drifted"
    assert generator.OPTIONAL_ARTIFACTS == OPTIONAL, "Optional artifact names drifted"
    assert generator.REQUIRED_SECTIONS == SECTIONS, "Required H2 contract drifted"
    assert generator.GENERATED_MARKER == MARKER, "Generated marker drifted"
    assert generator.TAXONOMY_BEGIN == TAXONOMY_BEGIN and generator.TAXONOMY_END == TAXONOMY_END
    assert generator.PACKAGE_ALIASES == {"production-line-optimization": "product-line-optimization"}
    assert set(generator.DRAFT_PACKAGES) == {"grid-outage-response"}
    assert generator.DEFAULT_RELATED_PATTERNS == DEFAULT_PATTERNS


def test_catalogue_identity_join_has_no_orphans_or_stale_exceptions(generator, sources):
    joined = validate_identity(
        sources["catalog"], sources["packages"], generator.PACKAGE_ALIASES, generator.DRAFT_PACKAGES,
    )
    assert len(joined) == 51, f"Expected all 51 catalogue identities, found {len(joined)}"


def test_joined_library_loads_with_registry_architecture_and_demo_sources(library, sources, slugs):
    assert library is not None, "load_library() returned no joined library"
    agents = read_json("registry.json")["agents"]
    for key in sources["catalog"]:
        matches = [agent for agent in agents if agent["name"] == key]
        assert len(matches) == 1 and isinstance(matches[0].get("_solution"), dict), f"{key}: registry join failed"
        name = key.split("/")[-1]
        assert f"state/architecture_level2_sources/{name}.json" in sources["files"], f"{key}: missing Level-2 source"
    for slug in slugs:
        assert f"tests/demo_cases/{slug}.json" in sources["files"], f"{slug}: missing demo cases"


def test_projection_on_disk_is_in_sync(generator, pilot_outputs):
    assert_clean(generator.check(ROOT), "Generator check() reports source/projection drift")
    actual = {
        path.relative_to(ROOT).as_posix(): path.read_bytes().decode("utf-8")
        for path in (ROOT / "01-solutions").rglob("*") if path.is_file()
    }
    actual["00-overview/README.md"] = (ROOT / "00-overview/README.md").read_bytes().decode("utf-8")
    validate_projection(pilot_outputs, actual)


def test_only_case_exact_pilot_artifacts_are_on_disk(generator, sources):
    actual = {
        path.relative_to(ROOT).as_posix()
        for path in (ROOT / "01-solutions").rglob("*") if path.is_file()
    }
    expected = {"01-solutions/README.md"} | {
        f"01-solutions/{slug}/{artifact}"
        for slug in generator.RUNBOOK_SOLUTIONS
        for artifact in expected_artifacts(slug, sources["files"])
    }
    assert actual == expected, f"Pilot file set: extra={sorted(actual - expected)}, missing={sorted(expected - actual)}"


def test_all_51_solutions_render_every_artifact(generator, library, slugs, sources, all_outputs):
    assert len(slugs) == 51, f"All-solution render must measure 51 packages, got {len(slugs)}"
    expected = {"01-solutions/README.md", "00-overview/README.md"}
    for slug in slugs:
        rendered = generator.render_solution(library, slug)
        artifacts = expected_artifacts(slug, sources["files"])
        assert set(rendered) == artifacts, f"{slug}: rendered artifacts {sorted(rendered)} != {sorted(artifacts)}"
        for artifact, text in rendered.items():
            path = f"01-solutions/{slug}/{artifact}"
            expected.add(path)
            assert all_outputs.get(path) == text, f"{path}: render_solution/build_outputs disagree"
    assert set(all_outputs) == expected, "build_outputs must include every artifact, index and full overview"


def test_generated_documents_have_exact_sections_and_no_leaks(all_outputs, links):
    generated = {path: text for path, text in all_outputs.items() if path.startswith("01-solutions/")}
    assert len(generated) >= 256, "Generated-document validation did not receive all 51 solutions"
    for path, text in generated.items():
        validate_generated_document(path, text, links)


def test_rendering_is_deterministic(generator, slugs, all_outputs):
    assert generator.build_outputs(ROOT, solutions=slugs) == all_outputs, "Two all-solution renders differ"


def test_disk_links_images_and_anchors_resolve(links, sources, disk_docs):
    for path in TOUCHED[:4]:
        assert path in disk_docs, f"Link audit did not measure touched document {path}"
    for prefix in PREFIXES:
        assert any(path.startswith(prefix) for path in disk_docs), f"Link audit did not measure {prefix}"
    assert_clean(
        links.check_links(ROOT, disk_docs, files=sources["files"], allowed_runbooks_urls=allowed_runbooks(sources)),
        "On-disk links/images/anchors",
    )


def test_all_51_in_memory_links_resolve_at_projected_locations(links, sources, disk_docs, all_outputs, slugs):
    documents = {**disk_docs, **all_outputs}
    assert all(f"01-solutions/{slug}/1.Overview.md" in documents for slug in slugs), "Missing in-memory overview"
    assert_clean(
        links.check_links(ROOT, documents, files=sources["files"], allowed_runbooks_urls=allowed_runbooks(sources)),
        "All-solution in-memory links/images/anchors",
    )


def test_pattern_schema_ids_titles_urls_and_defaults(generator, sources, disk_docs):
    ids = validate_patterns(sources["patterns"], disk_docs["02-patterns/README.md"], generator.DEFAULT_RELATED_PATTERNS)
    assert len(ids) == 25, f"Expected 25 unique pattern ids, found {len(ids)}"


def test_notes_schema_keys_types_sources_and_patterns(sources):
    validate_notes(sources["notes"], sources["catalog"], pattern_ids(sources), sources["files"])


def test_pilot_notes_are_complete_and_visible_in_rendered_overviews(sources, pilot_outputs):
    for slug in PILOTS:
        key = "@aibast-agents-library/" + slug
        entry = sources["notes"]["solutions"].get(key)
        assert entry, f"{slug}: pilot delivery notes are missing"
        for field in ("target_users", "scope_in", "scope_out", "qualification_checklist", "what_goes_wrong", "related_patterns", "sources"):
            assert entry.get(field), f"{slug}: pilot notes field {field} is empty"
        overview = re.sub(r"\s+", " ", pilot_outputs[f"01-solutions/{slug}/1.Overview.md"])
        for item in entry["qualification_checklist"] + [row["issue"] for row in entry["what_goes_wrong"]]:
            probe = re.sub(r"\s+", " ", item)
            assert probe in overview, f"{slug}: authored note is not visible in 1.Overview.md: {item!r}"


def test_controlled_journey_stages_are_sorted_exhaustive_and_in_use(generator, sources):
    assert len(generator.JOURNEY_STAGES) == 20, "Controlled journey vocabulary must have 20 primaries"
    validate_journeys(sources["catalog"], generator.JOURNEY_STAGES, generator.normalize_journey_stage)


@pytest.mark.parametrize("value, expected", [("Serve and coordinate", ("Serve", "Coordinate")), ("Optimize", ("Optimize", None))])
def test_normalize_journey_stage(generator, value, expected):
    assert generator.normalize_journey_stage(value) == expected, f"Incorrect normalization of {value!r}"


def test_owned_surface_declarations_are_complete(disk_docs):
    validate_owned_surfaces(disk_docs)


def test_taxonomy_and_index_cover_every_display_name_and_both_pilots(sources, disk_docs):
    validate_taxonomy(sources["catalog"], disk_docs["00-overview/README.md"], disk_docs["01-solutions/README.md"])


def test_negative_unknown_pattern_id(sources):
    notes = copy.deepcopy(sources["notes"])
    entry = next(iter(notes["solutions"].values()))
    entry.setdefault("related_patterns", []).append("aibast:missing-test-pattern")
    with pytest.raises(AssertionError, match="unknown pattern id: aibast:missing-test-pattern"):
        validate_notes(notes, sources["catalog"], pattern_ids(sources), sources["files"])


def test_negative_missing_notes_source(sources):
    notes = copy.deepcopy(sources["notes"])
    entry = next(iter(notes["solutions"].values()))
    missing = "solutions/missing-test-source.md"
    assert missing not in sources["files"], "Negative-test source unexpectedly exists"
    entry.setdefault("sources", []).append(missing)
    with pytest.raises(AssertionError, match="missing notes source: solutions/missing-test-source.md"):
        validate_notes(notes, sources["catalog"], pattern_ids(sources), sources["files"])


def test_negative_notes_require_sources(sources):
    notes = copy.deepcopy(sources["notes"])
    entry = next(iter(notes["solutions"].values()))
    entry.pop("sources", None)
    entry["scope_in"] = ["Synthetic test scope"]
    with pytest.raises(AssertionError, match="sources required"):
        validate_notes(notes, sources["catalog"], pattern_ids(sources), sources["files"])


def test_negative_duplicate_pattern_id(sources, disk_docs):
    patterns = copy.deepcopy(sources["patterns"])
    patterns["aibast_patterns"].append(dict(patterns["aibast_patterns"][0]))
    with pytest.raises(AssertionError, match="Duplicate pattern id"):
        validate_patterns(patterns, disk_docs["02-patterns/README.md"], DEFAULT_PATTERNS)


def test_negative_unknown_journey_stage(generator, sources):
    catalog = copy.deepcopy(sources["catalog"])
    catalog[sorted(catalog)[0]]["journey_stage"] = "Zzztest and qqq"
    with pytest.raises(AssertionError, match="unknown journey stage: Zzztest"):
        validate_journeys(catalog, generator.JOURNEY_STAGES, generator.normalize_journey_stage)


def test_negative_orphan_package_directory(generator, sources):
    packages = {**sources["packages"], "zz-test-orphan": None}
    with pytest.raises(AssertionError, match="Orphan package directories.*zz-test-orphan"):
        validate_identity(sources["catalog"], packages, generator.PACKAGE_ALIASES, generator.DRAFT_PACKAGES)


def test_negative_stale_alias(generator, sources):
    aliases = {**generator.PACKAGE_ALIASES, "zz-stale-alias": "zz-stale-package"}
    with pytest.raises(AssertionError, match="Stale alias: 'zz-stale-alias'"):
        validate_identity(sources["catalog"], sources["packages"], aliases, generator.DRAFT_PACKAGES)


def test_negative_stale_draft_allowlist(generator, sources):
    drafts = {**generator.DRAFT_PACKAGES, "zz-stale-draft": "Synthetic missing draft."}
    with pytest.raises(AssertionError, match="Stale draft allowlist entry: zz-stale-draft"):
        validate_identity(sources["catalog"], sources["packages"], generator.PACKAGE_ALIASES, drafts)


def mutated_projection(outputs, mutation):
    actual = dict(outputs)
    prefix = "01-solutions/ask-hr/"
    if mutation == "extra":
        actual[prefix + "6.Extra.md"] = "Stale generated output.\n"
    elif mutation == "edit":
        actual[prefix + "2.Architecture.md"] += "\nHand-edited content.\n"
    elif mutation == "delete":
        del actual[prefix + "3.Runbook.md"]
    elif mutation == "case":
        actual[prefix + "4.Sample-Prompts.md"] = actual.pop(prefix + "4.Sample-prompts.md")
    else:
        actual["00-overview/README.md"] = actual["00-overview/README.md"].replace(
            TAXONOMY_BEGIN, TAXONOMY_BEGIN + "\nHand-edited taxonomy row.",
        )
    assert actual != outputs, f"Projection mutation {mutation} made no change"
    return actual


@pytest.mark.parametrize(
    "mutation, expected_error",
    [
        ("extra", "Extra generated files.*6.Extra.md"),
        ("edit", "Changed generated content.*2.Architecture.md"),
        ("delete", "Missing generated files.*3.Runbook.md"),
        ("case", "Extra generated files.*4.Sample-Prompts.md"),
        ("taxonomy", "Taxonomy content drift"),
    ],
)
def test_negative_projection_drift(pilot_outputs, mutation, expected_error):
    validate_projection(pilot_outputs, dict(pilot_outputs))
    actual = mutated_projection(pilot_outputs, mutation)
    with pytest.raises(AssertionError, match=expected_error):
        validate_projection(pilot_outputs, actual)
    validate_projection(pilot_outputs, dict(pilot_outputs))


@pytest.mark.parametrize(
    "mutation, message",
    [
        ("extra", "stale extra file: 01-solutions/ask-hr/6.Extra.md"),
        ("edit", "changed: 01-solutions/ask-hr/2.Architecture.md"),
        ("delete", "missing: 01-solutions/ask-hr/3.Runbook.md"),
        ("case", "missing: 01-solutions/ask-hr/4.Sample-prompts.md"),
        ("taxonomy", "changed: taxonomy block in 00-overview/README.md"),
    ],
)
def test_negative_generator_check_on_memory_filesystem(generator, pilot_outputs, monkeypatch, mutation, message):
    virtual_root = ROOT / "virtual-runbook-test"
    actual = dict(pilot_outputs)
    original_is_file, original_read_bytes = Path.is_file, Path.read_bytes

    def relative(path):
        return path.relative_to(virtual_root).as_posix() if path.is_relative_to(virtual_root) else None

    def is_file(path):
        name = relative(path)
        return name in actual if name is not None else original_is_file(path)

    def read_bytes(path):
        name = relative(path)
        return actual[name].encode("utf-8") if name is not None else original_read_bytes(path)

    def refuse_write(*args, **kwargs):
        raise AssertionError("check() attempted a filesystem write")

    monkeypatch.setattr(generator, "build_outputs", lambda root: dict(pilot_outputs))
    monkeypatch.setattr(generator, "_file_universe", lambda root: frozenset(actual))
    monkeypatch.setattr(Path, "is_file", is_file)
    monkeypatch.setattr(Path, "read_bytes", read_bytes)
    for method in ("write_bytes", "write_text", "mkdir", "unlink", "rename"):
        monkeypatch.setattr(Path, method, refuse_write)
    assert generator.check(virtual_root) == [], "Unmutated in-memory control must pass check()"
    actual.clear()
    actual.update(mutated_projection(pilot_outputs, mutation))
    problems = generator.check(virtual_root)
    assert message in problems, f"{mutation}: check() failed to detect drift: {problems}"
    actual.clear()
    actual.update(pilot_outputs)
    assert generator.check(virtual_root) == [], f"{mutation}: in-memory revert must restore check() to green"


def test_negative_owned_surface_declaration(disk_docs):
    changed = dict(disk_docs)
    changed["CLAUDE.md"] = changed["CLAUDE.md"].replace("01-solutions/", "01-solutionz/")
    with pytest.raises(AssertionError, match="CLAUDE.md: missing owned-surface declaration '01-solutions/'"):
        validate_owned_surfaces(changed)


def test_negative_duplicate_taxonomy_marker(sources, disk_docs):
    overview = disk_docs["00-overview/README.md"] + TAXONOMY_BEGIN
    with pytest.raises(AssertionError, match="Taxonomy begin marker must occur exactly once"):
        validate_taxonomy(sources["catalog"], overview, disk_docs["01-solutions/README.md"])


@pytest.mark.parametrize(
    "target, kind",
    [
        ("does-not-exist.md", "missing target"), ("target.md", "case mismatch"),
        ("Target.md#missing", "missing anchor"), ("../../escape.md", "escapes repository"),
    ],
)
def test_negative_link_target_and_anchor(links, target, kind):
    documents = {"README.md": f"[test]({target})\n", "Target.md": "# Present\n"}
    problems = links.check_links(ROOT, documents, files=set(), allowed_runbooks_urls=set())
    assert len(problems) == 1, f"Expected exactly one {kind}, found {problems}"
    assert problems[0].kind == kind, str(problems[0])
    with pytest.raises(AssertionError, match=re.escape(kind)):
        assert_clean(problems, "Mutation must fail the positive link validator")


def test_link_extraction_ignores_code_but_preserves_destinations_and_line_numbers(links):
    text = (
        "[inline](Target.md)\n![image](asset.png)\n[ref]: <Target.md> \"title\"\n"
        "<a href='Target.md'>link</a><img src=asset.png>\n"
        "`[ignored](missing.md)` and ``code ` [ignored](missing.md)``\n"
        "````text\n```\n[ignored](missing.md)\n````\n"
        "~~~text\n<img src='missing.png'>\n~~~\n"
        "[parentheses](file(1).md)\n[escaped](file\\(1\\).md)\n[space](<file name.md>)\n"
        "<!-- [ignored](missing.md) -->\n"
    )
    assert links.extract_links(text) == [
        (1, "Target.md"), (2, "asset.png"), (3, "Target.md"),
        (4, "Target.md"), (4, "asset.png"), (13, "file(1).md"),
        (14, "file(1).md"), (15, "file name.md"),
    ], "Link extraction lost destinations, included code, or shifted line numbers"


def test_github_slugs_keep_inline_code_combining_marks_and_duplicate_suffixes(links):
    text = (
        "# Phase 1: Deploy the `DynPerfAgent` X++ Model to F&O\n"
        "## Phase 2: Import the `DyPerfTopXQuery` Dataverse Solution\n"
        "## 🏗️ Reference Composition\n## Repeat\n## Repeat\n## Repeat-1\n## Repeat\n"
        "## Café — *plan* [details](README.md)\n"
        "<a id='explicit-id'></a><a name='legacy-name'></a>\n"
        "```\n## Hidden\n<a id='hidden-id'></a>\n```\n"
    )
    expected = {
        "phase-1-deploy-the-dynperfagent-x-model-to-fo",
        "phase-2-import-the-dyperftopxquery-dataverse-solution",
        "\ufe0f-reference-composition", "repeat", "repeat-1", "repeat-1-1", "repeat-2",
        "café--plan-details", "explicit-id", "legacy-name",
    }
    assert links.anchors_of(text) == expected, "GitHub heading/explicit-anchor semantics drifted"


def test_relative_root_directory_and_in_memory_destinations_resolve(links):
    documents = {
        "docs/Guide.md": (
            "[root](/README.md#home)\n[relative](../README.md#home)\n"
            "[directory](../docs/#guide)\n[generated](../01-solutions/example/1.Overview.md#generated)\n"
            "![image](../assets/image.png)\n"
        ),
        "README.md": "# Home\n", "docs/README.md": "# Guide\n",
        "01-solutions/example/1.Overview.md": "# Generated\n",
    }
    assert_clean(links.check_links(ROOT, documents, files={"assets/image.png"}), "Relative/root/directory overlay links")


def test_pages_github_and_allowlisted_runbooks_urls_resolve_offline(links):
    reference = sorted(REFERENCE_URLS)[0]
    documents = {
        "README.md": (
            "[page](https://microsoft.github.io/aibast-agents-library/docs/)\n"
            "[blob](https://github.com/microsoft/aibast-agents-library/blob/main/docs/Target.md#hello)\n"
            "[tree](https://github.com/microsoft/aibast-agents-library/tree/main/docs)\n"
            f"[runbooks]({reference})\n"
        ),
        "docs/Target.md": "# Hello\n", "docs/index.html": "<h1 id='hello'>Hello</h1>\n",
    }
    assert_clean(
        links.check_links(ROOT, documents, files=set(), allowed_runbooks_urls={reference}),
        "Offline Pages/GitHub/runbooks mapping",
    )


@pytest.mark.parametrize(
    "target, kind",
    [
        ("https://microsoft.github.io/aibast-agents-library/Missing.html", "missing target"),
        ("https://github.com/microsoft/aibast-agents-library/blob/main/missing.md", "missing target"),
        ("https://github.com/microsoft/aibast-agents-library/tree/main/missing", "missing target"),
        (RUNBOOKS_URL + "02-patterns/unlisted.md", "unlisted runbooks URL"),
        ("file:///home/example/README.md", "forbidden link"),
        ("/home/example/README.md", "forbidden link"),
        ("C:\\work\\README.md", "forbidden link"),
        ("https://github.com/" + "-".join(("kody", "w")) + "/example", "forbidden link"),
    ],
)
def test_negative_external_mapping_and_forbidden_destinations(links, target, kind):
    problems = links.check_links(ROOT, {"README.md": f"[test](<{target}>)\n"}, files=set(), allowed_runbooks_urls=set())
    assert len(problems) == 1 and problems[0].kind == kind, f"{target}: expected {kind}, got {problems}"


def test_git_universe_includes_untracked_and_overlay_but_not_deleted_files(links, monkeypatch):
    root = Path("virtual-repository")
    calls = []

    def git_run(command, **kwargs):
        calls.append((command, kwargs))
        return subprocess.CompletedProcess(command, 0, "Tracked.md\0Untracked.md\0Deleted.md\0", "")

    monkeypatch.setattr(links.subprocess, "run", git_run)
    monkeypatch.setattr(Path, "is_file", lambda path: path.name in {"Tracked.md", "Untracked.md"})
    files = links.git_file_universe(root, {"Generated.md": "# Generated\n"})
    assert files == {"Tracked.md", "Untracked.md", "Generated.md"}, f"Wrong Git universe: {files}"
    assert calls[0][0] == ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard"]
    assert calls[0][1]["cwd"] == root and calls[0][1]["check"] is True, "Git failure/root handling changed"


@pytest.mark.parametrize("text, status", [("# Home\n", 0), ("[broken](missing.md)\n", 1)])
def test_link_checker_cli_exit_status_without_writes(links, monkeypatch, capsys, text, status):
    monkeypatch.setattr(links, "git_file_universe", lambda root: {"README.md"})
    monkeypatch.setattr(Path, "read_text", lambda path, **kwargs: text)
    assert links.main(["--root", str(ROOT), str(ROOT / "README.md")]) == status
    output = capsys.readouterr().out
    assert f"{status} problems" in output, f"CLI did not report measured problems: {output}"


@pytest.mark.parametrize("leak", ["None", "null", "nan", "{}", "[]", "TODO"])
def test_negative_generated_value_leaks(links, leak):
    path = "01-solutions/example/1.Overview.md"
    text = MARKER + "\n# Example\n\n" + "".join(
        f"## {section}\n\nSource-backed content.\n\n" for section in SECTIONS["1.Overview.md"]
    ).rstrip() + "\n"
    validate_generated_document(path, text, links)
    changed = text.replace("Source-backed content.", leak, 1)
    with pytest.raises(AssertionError, match="placeholder/value leak"):
        validate_generated_document(path, changed, links)


@pytest.mark.parametrize(
    "mutation, message",
    [
        ("marker", "generated marker must be the first line"),
        ("sections", "H2 order/titles"),
        ("empty", "empty section 'Scenario Overview'"),
        ("crlf", "require LF endings"),
        ("newline", "exactly one trailing newline"),
    ],
)
def test_negative_generated_document_structure(links, mutation, message):
    path = "01-solutions/example/1.Overview.md"
    text = MARKER + "\n# Example\n\n" + "".join(
        f"## {section}\n\nSource-backed content.\n\n" for section in SECTIONS["1.Overview.md"]
    ).rstrip() + "\n"
    validate_generated_document(path, text, links)
    if mutation == "marker":
        text = text.replace(MARKER, "", 1)
    elif mutation == "sections":
        text = text.replace("## Scenario Overview", "## Incorrect Heading", 1)
    elif mutation == "empty":
        text = text.replace("Source-backed content.", "", 1)
    elif mutation == "crlf":
        text = text.replace("Source-backed content.\n", "Source-backed content.\r\n", 1)
    else:
        text += "\n"
    with pytest.raises(AssertionError, match=message):
        validate_generated_document(path, text, links)


def test_link_existence_never_falls_back_to_case_insensitive_filesystem(links, monkeypatch):
    def unexpected_stat(path):
        raise AssertionError(f"Link existence must not stat the filesystem: {path}")

    monkeypatch.setattr(Path, "exists", unexpected_stat)
    monkeypatch.setattr(Path, "is_file", unexpected_stat)
    documents = {"README.md": "[case](readme.md)\n"}
    problems = links.check_links(ROOT, documents, files=set(), allowed_runbooks_urls=set())
    assert len(problems) == 1 and problems[0].kind == "case mismatch", problems


def test_fence_info_text_does_not_close_a_code_block(links):
    text = "```\n``` not a closing fence\n[hidden](missing.md)\n```\n[visible](Target.md)\n"
    assert links.extract_links(text) == [(5, "Target.md")], "A fence info string prematurely closed the code block"


def test_inline_code_can_span_lines_without_hiding_following_links(links):
    text = "`example\n[hidden](missing.md)`\n[visible](Target.md)\n"
    assert links.extract_links(text) == [(3, "Target.md")], "Multiline code span changed link extraction"


@pytest.mark.parametrize(
    "text, line",
    [
        ("> ```\n> [hidden](missing.md)\n> ```\n[visible](Target.md)\n", 4),
        ("> > ~~~\n> > [hidden](missing.md)\n[visible](Target.md)\n", 3),
    ],
)
def test_quoted_fences_ignore_code_without_hiding_the_following_document(links, text, line):
    assert links.extract_links(text) == [(line, "Target.md")], "Quoted code was counted as a live link"


@pytest.mark.parametrize(
    "body",
    [
        "```\npython tools/build_solution_runbooks.py --check\n```\n",
        "```\n<!-- This is displayed code, not a hidden comment. -->\n```\n",
        "```\n## This heading is code, not a document section\n```\n",
    ],
)
def test_code_only_sections_are_not_empty_and_fenced_headings_are_not_sections(links, body):
    text = MARKER + "\n# Example\n\n" + "".join(
        f"## {section}\n\n{body}\n" for section in SECTIONS["1.Overview.md"]
    ).rstrip() + "\n"
    validate_generated_document("01-solutions/example/1.Overview.md", text, links)


def test_heading_only_section_is_empty_even_when_later_sections_have_code(links):
    sections = SECTIONS["1.Overview.md"]
    text = MARKER + "\n# Example\n\n## " + sections[0] + "\n\n" + "".join(
        f"## {section}\n\n```\nSource-backed content.\n```\n\n" for section in sections[1:]
    ).rstrip() + "\n"
    with pytest.raises(AssertionError, match="empty section 'Scenario Overview'"):
        validate_generated_document("01-solutions/example/1.Overview.md", text, links)
