#!/usr/bin/env python3
"""Build api/v1/ — the static API surface of the AIBAST Agents Library.

Conforms to rapp-static-api/1.0 (index-without-content-store variant):
one build step, schema-tagged generated documents, versioned endpoints under
api/v1/, stable-write (a re-run with no upstream change produces
byte-identical output — the `generated` timestamp is preserved when nothing
else changed), served CORS-open over GitHub Pages and raw.githubusercontent.

Inputs (all generated by earlier build steps, never hand-edited here):
  registry.json                    — built by build_registry.py
  state/metrics.json               — built by build_metrics.py
  state/aggregated.json            — built by crawl_skills.py
  state/discussion_ratings.json    — built by discussion_ratings.py

Endpoints:
  api/v1/index.json                — API root: endpoint directory + base URLs
  api/v1/agents.json               — every agent, slim, with raw + page URLs
  api/v1/agents/<publisher>/<slug>.json — one document per agent (full manifest)
  api/v1/categories.json           — industries with their agent refs
  api/v1/publishers.json           — publisher directory
  api/v1/metrics.json              — latest metrics snapshot (mirror of state/)
  api/v1/aggregated.json           — aggregated outside skills (mirror of state/)
  api/v1/certified.json            — the RAPP Certified roster (public)
  api/v1/certified/<username>.json — real-time verification for one GitHub user
  api/v1/certified/<username>/badge.json — shields.io badge for that user
  api/v1/status.json               — aibast-api-status/1.0 heartbeat
  api/v1/badge.json                — shields.io endpoint format

Usage:  python scripts/build_api.py
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
API = REPO_ROOT / "api" / "v1"

REPO = "microsoft/aibast-agents-library"
RAW_BASE = f"https://raw.githubusercontent.com/{REPO}/main"
PAGES_BASE = f"https://microsoft.github.io/aibast-agents-library"

SCHEMA = "aibast-api/1.0"


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def load(path: str, default):
    try:
        return json.loads((REPO_ROOT / path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return default


def stable_write(path: Path, doc: dict) -> bool:
    """Write doc; if the only difference from the existing file is the
    `generated` timestamp, keep the old timestamp so git sees no diff."""
    if path.exists():
        try:
            old = json.loads(path.read_text(encoding="utf-8"))
            a = {k: v for k, v in old.items() if k != "generated"}
            b = {k: v for k, v in doc.items() if k != "generated"}
            if a == b and "generated" in old:
                doc = dict(doc, generated=old["generated"])
        except (OSError, json.JSONDecodeError):
            pass
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(doc, indent=2, sort_keys=False) + "\n"
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True


def slim_agent(a: dict, ratings: dict) -> dict:
    name = a.get("name", "")
    pub, _, slug = name.partition("/")
    r = ratings.get(name, {})
    return {
        "name": name,
        "display_name": a.get("display_name"),
        "version": a.get("version"),
        "description": a.get("description"),
        "author": a.get("author"),
        "category": a.get("category"),
        "tags": a.get("tags", []),
        "quality_tier": a.get("quality_tier", "community"),
        "requires_env": a.get("requires_env", []),
        "file": a.get("_file"),
        "size_kb": a.get("_size_kb"),
        "lines": a.get("_lines"),
        "raw_url": f"{RAW_BASE}/{a.get('_file', '')}",
        "pages_url": f"{PAGES_BASE}/{a.get('_file', '')}",
        "github_url": f"https://github.com/{REPO}/blob/main/{a.get('_file', '')}",
        "detail_url": f"{PAGES_BASE}/api/v1/agents/{pub.lstrip('@')}/{slug}.json",
        "engagement": {
            "upvotes": r.get("upvotes", 0),
            "downloads": r.get("downloads", 0),
            "comments": r.get("comments", 0),
            "discussion_url": r.get("url", ""),
        } if r else None,
    }


def main() -> int:
    registry = load("registry.json", {"agents": [], "stats": {}})
    metrics = load("state/metrics.json", None)
    aggregated = load("state/aggregated.json", None)
    ratings_doc = load("state/discussion_ratings.json", {})
    ratings = ratings_doc.get("agents", {}) if isinstance(ratings_doc, dict) else {}

    agents = registry.get("agents", [])
    stats = registry.get("stats", {})
    gen = now_iso()
    changed = 0

    slim = [slim_agent(a, ratings) for a in agents]

    # Per-agent detail documents
    kept_paths = set()
    for a, s in zip(agents, slim):
        pub, _, slug = a["name"].partition("/")
        p = API / "agents" / pub.lstrip("@") / f"{slug}.json"
        kept_paths.add(p)
        doc = {
            "schema": "aibast-api-agent/1.0",
            "generated": gen,
            "manifest": {k: v for k, v in a.items() if not k.startswith("_")},
            **{k: s[k] for k in ("file", "size_kb", "lines", "raw_url",
                                 "pages_url", "github_url", "engagement")},
        }
        changed += stable_write(p, doc)

    # Prune per-agent docs for agents no longer in the registry
    agents_dir = API / "agents"
    if agents_dir.exists():
        for p in agents_dir.rglob("*.json"):
            if p not in kept_paths:
                p.unlink()
                changed += 1

    changed += stable_write(API / "agents.json", {
        "schema": "aibast-api-agents/1.0", "generated": gen,
        "count": len(slim), "agents": slim,
    })

    cats: dict[str, list] = {}
    for s in slim:
        cats.setdefault(s["category"] or "uncategorized", []).append(
            {"name": s["name"], "display_name": s["display_name"],
             "detail_url": s["detail_url"]})
    changed += stable_write(API / "categories.json", {
        "schema": "aibast-api-categories/1.0", "generated": gen,
        "count": len(cats),
        "categories": [{"id": c, "agents": len(v), "items": v}
                       for c, v in sorted(cats.items())],
    })

    pubs: dict[str, int] = {}
    for s in slim:
        pubs[s["name"].split("/")[0]] = pubs.get(s["name"].split("/")[0], 0) + 1
    changed += stable_write(API / "publishers.json", {
        "schema": "aibast-api-publishers/1.0", "generated": gen,
        "count": len(pubs),
        "publishers": [
            {"name": p, "agents": n,
             "tree_url": f"https://github.com/{REPO}/tree/main/agents/{p}"}
            for p, n in sorted(pubs.items())],
    })

    if metrics is not None:
        changed += stable_write(API / "metrics.json", dict(metrics))
    if aggregated is not None:
        changed += stable_write(API / "aggregated.json", dict(aggregated))

    # ── Awards: badge catalog + roster -> verification endpoints ───────────
    # A username lookup must answer instantly and truthfully, including "no".
    # Every roster entry keeps a stable URL after revocation, so a badge already
    # embedded in someone's README flips to "not certified" rather than 404-ing
    # (a 404 cannot be told apart from an outage).
    catalog = load("badges.json", {"badges": []})
    badge_by_id = {b["id"]: b for b in catalog.get("badges", [])}
    roster = load("certified.json", {"members": [], "levels": {}})

    members = []
    for m in roster.get("members", []):
        user = str(m.get("username", "")).strip().lower()
        if not user:
            continue
        active = m.get("status", "active") == "active"
        awards = []
        for a in m.get("badges", []):
            meta = badge_by_id.get(a.get("id"))
            if not meta:
                continue          # an award naming an unknown badge is ignored, not guessed
            awards.append({
                "id": meta["id"], "name": meta["name"], "tier": meta.get("tier"),
                "points": meta.get("points", 0), "color": meta.get("color", "0078d4"),
                "awarded_on": a.get("awarded_on"), "discussion": a.get("discussion"),
                "note": a.get("note"),
                "badge_url": f"{PAGES_BASE}/api/v1/certified/{user}/{meta['id']}/badge.json",
            })
        members.append({
            "username": user,
            "level": m.get("level", "certified"),
            "certified": active and bool(awards),
            "status": m.get("status", "active"),
            "certified_on": m.get("certified_on"),
            "revoked_on": m.get("revoked_on"),
            "reason": m.get("reason"),
            "note": m.get("note"),
            "badges": awards if active else [],
            "points": sum(a["points"] for a in awards) if active else 0,
            "profile_url": f"https://github.com/{user}",
            "verify_url": f"{PAGES_BASE}/api/v1/certified/{user}.json",
            "badge_url": f"{PAGES_BASE}/api/v1/certified/{user}/badge.json",
            "agents": sorted(
                a["name"] for a in agents
                if a.get("name", "").split("/")[0].lstrip("@").lower() == user
            ),
        })

    certified_dir = API / "certified"
    kept_certified = set()

    def shields(label, message, color):
        return {"schemaVersion": 1, "label": label, "message": message, "color": color}

    for m in members:
        doc = {"schema": "aibast-certified/1.0", "generated": gen, **m}
        p_user = certified_dir / f"{m['username']}.json"
        kept_certified.add(p_user)
        changed += stable_write(p_user, doc)

        # Overall badge: green when the account holds at least one live award.
        summary = (f"certified · {len(m['badges'])} badge"
                   f"{'' if len(m['badges']) == 1 else 's'}") if m["certified"] else "not certified"
        p_badge = certified_dir / m["username"] / "badge.json"
        kept_certified.add(p_badge)
        changed += stable_write(p_badge, shields(
            "RAPP", summary, "brightgreen" if m["certified"] else "lightgrey"))

        # One shields endpoint per badge the user holds, so they can display
        # exactly the achievement they mean.
        for a in m["badges"]:
            p_one = certified_dir / m["username"] / a["id"] / "badge.json"
            kept_certified.add(p_one)
            changed += stable_write(p_one, shields("RAPP", a["name"], a["color"]))

    if certified_dir.exists():
        for p_old in certified_dir.rglob("*.json"):
            if p_old not in kept_certified:
                p_old.unlink()
                changed += 1

    holders_by_badge = {}
    for m in members:
        for a in m["badges"]:
            holders_by_badge.setdefault(a["id"], []).append(
                {"username": m["username"], "awarded_on": a["awarded_on"],
                 "discussion": a["discussion"]})

    badges_dir = API / "badges"
    kept_badges = set()
    for b in catalog.get("badges", []):
        holders = sorted(holders_by_badge.get(b["id"], []),
                         key=lambda h: (h["awarded_on"] or "", h["username"]))
        p_b = badges_dir / f"{b['id']}.json"
        kept_badges.add(p_b)
        changed += stable_write(p_b, {
            "schema": "aibast-badge/1.0", "generated": gen, **b,
            "holders": holders, "holder_count": len(holders),
        })
    if badges_dir.exists():
        for p_old in badges_dir.glob("*.json"):
            if p_old not in kept_badges:
                p_old.unlink()
                changed += 1

    changed += stable_write(API / "badges.json", {
        "schema": "aibast-badge-catalog/1.0", "generated": gen,
        "count": len(catalog.get("badges", [])),
        "lookup": f"{PAGES_BASE}/api/v1/badges/{{badge_id}}.json",
        "badges": [{**b, "holder_count": len(holders_by_badge.get(b["id"], []))}
                   for b in catalog.get("badges", [])],
    })

    # Wall of Fame: ranked, public, and derived — never hand-edited.
    wall = sorted((m for m in members if m["certified"]),
                  key=lambda m: (-m["points"], -len(m["badges"]), m["username"]))
    changed += stable_write(API / "wall.json", {
        "schema": "aibast-wall/1.0", "generated": gen,
        "count": len(wall),
        "page": f"{PAGES_BASE}/wall.html",
        "members": [{k: m[k] for k in
                     ("username", "level", "points", "badges", "profile_url",
                      "verify_url", "badge_url", "agents")} for m in wall],
    })

    changed += stable_write(API / "certified.json", {
        "schema": "aibast-certified-roster/1.0", "generated": gen,
        "levels": roster.get("levels", {}),
        "count": sum(1 for m in members if m["certified"]),
        "lookup": f"{PAGES_BASE}/api/v1/certified/{{username}}.json",
        "note": ("Query any GitHub username. A username absent from this roster is "
                 "not certified; an entry with certified=false was revoked."),
        "members": members,
    })

    changed += stable_write(API / "status.json", {
        "schema": "aibast-api-status/1.0", "generated": gen,
        "ok": True,
        "agents": stats.get("total_agents", len(agents)),
        "publishers": stats.get("publishers", len(pubs)),
        "categories": stats.get("categories", len(cats)),
        "aggregated_skills": ((aggregated or {}).get("stats") or {}).get("total", 0),
        "certified_publishers": sum(1 for m in members if m["certified"]),
        "badges": len(catalog.get("badges", [])),
    })

    changed += stable_write(API / "badge.json", {
        "schemaVersion": 1, "label": "aibast agents",
        "message": str(stats.get("total_agents", len(agents))),
        "color": "blue",
    })

    changed += stable_write(API / "index.json", {
        "schema": SCHEMA, "generated": gen,
        "name": "AIBAST Agents Library API",
        "spec": "rapp-static-api/1.0",
        "base_urls": {"pages": f"{PAGES_BASE}/api/v1",
                      "raw": f"{RAW_BASE}/api/v1"},
        "docs": f"https://github.com/{REPO}/blob/main/docs/API.md",
        "endpoints": {
            "agents": "agents.json",
            "agent_detail": "agents/{publisher}/{slug}.json",
            "categories": "categories.json",
            "publishers": "publishers.json",
            "metrics": "metrics.json",
            "aggregated": "aggregated.json",
            "certified_roster": "certified.json",
            "certified_lookup": "certified/{username}.json",
            "certified_badge": "certified/{username}/badge.json",
            "certified_badge_one": "certified/{username}/{badge_id}/badge.json",
            "badge_catalog": "badges.json",
            "badge_holders": "badges/{badge_id}.json",
            "wall_of_fame": "wall.json",
            "status": "status.json",
            "badge": "badge.json",
            "registry": "../../registry.json",
        },
    })

    print(f"[build-api] {len(slim)} agents → api/v1/ ({changed} file(s) changed)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
