#!/usr/bin/env python3
"""Build api/v1/ — the static API surface of the AIBAST Agents Library.

Conforms to rapp-static-api/1.0 (index-without-content-store variant):
one build step, schema-tagged generated documents, versioned endpoints under
api/v1/, stable-write (a re-run with no upstream change produces
byte-identical output — the `generated` timestamp is preserved when nothing
else changed), served CORS-open over GitHub Pages and raw.githubusercontent.

Inputs (all generated by earlier build steps, never hand-edited here):
  registry.json                    — built by build_registry.py
  state/metrics.json               — built by build_metrics.py
  state/aggregated.json            — built by crawl_skills.py
  state/discussion_ratings.json    — built by discussion_ratings.py

Endpoints:
  api/v1/index.json                — API root: endpoint directory + base URLs
  api/v1/agents.json               — every agent, slim, with raw + page URLs
  api/v1/agents/<publisher>/<slug>.json — one document per agent (full manifest)
  api/v1/categories.json           — industries with their agent refs
  api/v1/publishers.json           — publisher directory
  api/v1/metrics.json              — latest metrics snapshot (mirror of state/)
  api/v1/aggregated.json           — aggregated outside skills (mirror of state/)
  api/v1/<extension namespaces>    — contributed by whatever is installed under
                                     rapp/ext/ (discovered, never named here;
                                     see rapp/ext/PATTERN.md)
  api/v1/status.json               — aibast-api-status/1.0 heartbeat
  api/v1/badge.json                — shields.io endpoint format

Usage:  python scripts/build_api.py
"""
from __future__ import annotations

import importlib.util
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
API = REPO_ROOT / "api" / "v1"

REPO = "microsoft/aibast-agents-library"
RAW_BASE = f"https://raw.githubusercontent.com/{REPO}/main"
PAGES_BASE = f"https://microsoft.github.io/aibast-agents-library"

SCHEMA = "aibast-api/1.0"

# Extensions are DISCOVERED here, never named. Adding or removing one is a
# directory under rapp/ext/ plus nothing else — the pattern is specified in
# rapp/ext/PATTERN.md, and it is what keeps kernel syncs from ever colliding
# with distribution-originated work.
EXT_ROOT = REPO_ROOT / "rapp" / "ext"


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def load(path: str, default):
    try:
        return json.loads((REPO_ROOT / path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return default


def stable_write(path: Path, doc: dict) -> bool:
    """Write doc; if the only difference from the existing file is the
    `generated` timestamp, keep the old timestamp so git sees no diff."""
    if path.exists():
        try:
            old = json.loads(path.read_text(encoding="utf-8"))
            a = {k: v for k, v in old.items() if k != "generated"}
            b = {k: v for k, v in doc.items() if k != "generated"}
            if a == b and "generated" in old:
                doc = dict(doc, generated=old["generated"])
        except (OSError, json.JSONDecodeError):
            pass
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(doc, indent=2, sort_keys=False) + "\n"
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True



class _ExtContext:
    """What an extension may touch. Deliberately small: it can read repo files,
    write inside its declared namespaces, and prune its own directory. It
    cannot reach core endpoints, and a failure in it cannot fail the core."""

    def __init__(self, api_root, agents, generated, pages_base, namespaces):
        self._api = api_root
        self._ns = tuple(namespaces)
        self.agents = agents
        self.generated = generated
        self.pages_base = pages_base
        self.changed = 0
        self._written = []

    @staticmethod
    def load(path, default):
        return load(path, default)

    def _check(self, rel):
        if rel.startswith("/") or ".." in Path(rel).parts:
            raise ValueError(f"extension path escapes the API root: {rel!r}")
        if not any(rel == n or rel.startswith(n) for n in self._ns):
            raise ValueError(
                f"extension wrote {rel!r} outside its declared namespaces {self._ns}")
        return (self._api / rel).resolve()

    def write(self, rel, doc):
        p = self._check(rel)
        self.changed += stable_write(p, doc)
        self._written.append(p)
        return p

    def prune(self, rel_dir, keep):
        d = self._check(rel_dir if rel_dir.endswith("/") else rel_dir + "/")
        if not d.exists():
            return
        for p in d.rglob("*.json"):
            if p not in keep:
                p.unlink()
                self.changed += 1


def run_extensions(api_root, agents, generated, pages_base):
    """Discover rapp/ext/*/build.py and run each. An extension that is absent,
    broken, or misbehaving is reported and skipped — the core API still builds.
    That is the whole point: kernel and core work never depend on an extension."""
    found = {}
    total_changed = 0
    if not EXT_ROOT.is_dir():
        return found, total_changed
    for build_py in sorted(EXT_ROOT.glob("*/build.py")):
        name = build_py.parent.name
        try:
            spec = importlib.util.spec_from_file_location(f"rapp_ext_{name}", build_py)
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            protocol = getattr(mod, "PROTOCOL")
            ctx = _ExtContext(api_root, agents, generated, pages_base,
                              getattr(mod, "NAMESPACES", ()))
            entry = mod.build(ctx)
            total_changed += ctx.changed
            entry["namespaces"] = list(getattr(mod, "NAMESPACES", ()))
            found[protocol] = entry
            print(f"[build-api] extension {protocol} ({name}): {ctx.changed} file(s) changed")
        except Exception as exc:
            print(f"[build-api] extension {name} SKIPPED ({exc}) — core API unaffected", file=sys.stderr)
    return found, total_changed


def stable_write_text(path: Path, text: str) -> bool:
    """Same stable-write discipline as the JSON writer, for generated text."""
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def slim_agent(a: dict, ratings: dict) -> dict:
    name = a.get("name", "")
    pub, _, slug = name.partition("/")
    r = ratings.get(name, {})
    return {
        "name": name,
        "display_name": a.get("display_name"),
        "version": a.get("version"),
        "description": a.get("description"),
        "author": a.get("author"),
        "category": a.get("category"),
        "tags": a.get("tags", []),
        "quality_tier": a.get("quality_tier", "community"),
        "requires_env": a.get("requires_env", []),
        "file": a.get("_file"),
        "size_kb": a.get("_size_kb"),
        "lines": a.get("_lines"),
        "raw_url": f"{RAW_BASE}/{a.get('_file', '')}",
        "pages_url": f"{PAGES_BASE}/{a.get('_file', '')}",
        "github_url": f"https://github.com/{REPO}/blob/main/{a.get('_file', '')}",
        "detail_url": f"{PAGES_BASE}/api/v1/agents/{pub.lstrip('@')}/{slug}.json",
        "onepager_url": f"{PAGES_BASE}/onepager.html?agent={name}",
        "engagement": {
            "upvotes": r.get("upvotes", 0),
            "downloads": r.get("downloads", 0),
            "comments": r.get("comments", 0),
            "discussion_url": r.get("url", ""),
        } if r else None,
    }


def main() -> int:
    registry = load("registry.json", {"agents": [], "stats": {}})
    metrics = load("state/metrics.json", None)
    aggregated = load("state/aggregated.json", None)
    ratings_doc = load("state/discussion_ratings.json", {})
    ratings = ratings_doc.get("agents", {}) if isinstance(ratings_doc, dict) else {}

    reviews_doc = load("state/agent_reviews.json", {}) or {}
    machine_reviews = {r["file"]: r for r in reviews_doc.get("reviews", [])}

    agents = registry.get("agents", [])
    stats = registry.get("stats", {})
    gen = now_iso()
    changed = 0

    slim = [slim_agent(a, ratings) for a in agents]

    # Per-agent detail documents
    kept_paths = set()
    for a, s in zip(agents, slim):
        pub, _, slug = a["name"].partition("/")
        p = API / "agents" / pub.lstrip("@") / f"{slug}.json"
        kept_paths.add(p)
        doc = {
            "schema": "aibast-api-agent/1.0",
            "generated": gen,
            "manifest": {k: v for k, v in a.items() if not k.startswith("_")},
            **{k: s[k] for k in ("file", "size_kb", "lines", "raw_url",
                                 "pages_url", "github_url", "onepager_url",
                                 "engagement")},
        }
        review = (machine_reviews or {}).get(a.get("_file"))
        if review:
            # Machine review rides along under its own key with its own type
            # marker. A consumer that wants a community rating reads
            # `engagement`; the two never share a field.
            doc["machine_review"] = {
                "review_type": "machine",
                "verdict": review.get("verdict"),
                "overall": review.get("overall"),
                "scores": review.get("scores"),
                "rubric_version": review.get("rubric_version"),
                "open_findings": [
                    {k: c[k] for k in ("id", "principle", "level", "title", "detail", "teachable")}
                    for c in review.get("checks", []) if not c.get("passed")
                ],
                "not_an_endorsement": (
                    "Static analysis against published principles. Never combined "
                    "with community ratings."
                ),
            }
        changed += stable_write(p, doc)

    # Prune per-agent docs for agents no longer in the registry
    agents_dir = API / "agents"
    if agents_dir.exists():
        for p in agents_dir.rglob("*.json"):
            if p not in kept_paths:
                p.unlink()
                changed += 1

    changed += stable_write(API / "agents.json", {
        "schema": "aibast-api-agents/1.0", "generated": gen,
        "count": len(slim), "agents": slim,
    })

    cats: dict[str, list] = {}
    for s in slim:
        cats.setdefault(s["category"] or "uncategorized", []).append(
            {"name": s["name"], "display_name": s["display_name"],
             "detail_url": s["detail_url"]})
    changed += stable_write(API / "categories.json", {
        "schema": "aibast-api-categories/1.0", "generated": gen,
        "count": len(cats),
        "categories": [{"id": c, "agents": len(v), "items": v}
                       for c, v in sorted(cats.items())],
    })

    pubs: dict[str, int] = {}
    for s in slim:
        pubs[s["name"].split("/")[0]] = pubs.get(s["name"].split("/")[0], 0) + 1
    changed += stable_write(API / "publishers.json", {
        "schema": "aibast-api-publishers/1.0", "generated": gen,
        "count": len(pubs),
        "publishers": [
            {"name": p, "agents": n,
             "tree_url": f"https://github.com/{REPO}/tree/main/agents/{p}"}
            for p, n in sorted(pubs.items())],
    })

    if metrics is not None:
        changed += stable_write(API / "metrics.json", dict(metrics))
    if aggregated is not None:
        # Publish BOTH projections of each converted skill. A consumer that
        # wants instructions takes the .md; one that wants a registrable tool
        # takes the .py. They are derived from each other, so neither is the
        # "real" one — see docs/MIRRORING.md.
        agg_doc = dict(aggregated)
        for sk in agg_doc.get("skills", []):
            rapp = sk.get("rapp_skill")
            if not rapp or not rapp.get("path"):
                continue
            mirror = Path(rapp["path"]).with_suffix(".py")
            if (REPO_ROOT / mirror).is_file():
                sk["rapp_agent"] = {
                    "path": mirror.as_posix(),
                    "download_url": f"{PAGES_BASE}/{mirror.as_posix()}",
                    "raw_url": f"{RAW_BASE}/{mirror.as_posix()}",
                    "bytes": (REPO_ROOT / mirror).stat().st_size,
                    "format": "agent.py",
                    "derived_from": rapp["path"],
                    "derivable_in_browser": True,
                }
        changed += stable_write(API / "aggregated.json", agg_doc)

    # Solution one-pagers: the business framing, its demo, and its engagement.
    onepagers = load("data/onepagers.json", None)
    if onepagers is not None:
        changed += stable_write(API / "onepagers.json", dict(onepagers))
        kept_op = set()
        for sol in onepagers.get("onepagers", []):
            p = API / "onepagers" / f"{sol['slug']}.json"
            kept_op.add(p)
            changed += stable_write(p, {
                "schema": "aibast-api-onepager/1.0", "generated": gen,
                "onepager": sol,
                "page_url": f"{PAGES_BASE}/onepager.html?solution={sol['slug']}",
            })
        op_dir = API / "onepagers"
        if op_dir.exists():
            for p in op_dir.glob("*.json"):
                if p not in kept_op:
                    p.unlink(); changed += 1

    # Machine review. Published on its own endpoint and under its own schema so
    # a consumer cannot accidentally read it as a community rating — the two
    # answer different questions and are never combined.
    reviews = load("state/agent_reviews.json", None)
    if reviews is not None:
        changed += stable_write(API / "reviews.json", dict(reviews))

    # Aggregated skills get the same review treatment as agents we wrote —
    # that is the value of aggregating into the library instead of linking out.
    skill_reviews = load("state/skill_reviews.json", None)
    if skill_reviews is not None:
        changed += stable_write(API / "reviews-skills.json", dict(skill_reviews))
        kept_sr = set()
        for r in skill_reviews.get("reviews", []):
            slug = r["ref"].split("/")[-1]
            p_out = API / "reviews" / "skills" / f"{slug}.json"
            kept_sr.add(p_out)
            changed += stable_write(p_out, {
                "schema": "aibast-api-skill-review/1.0", "generated": gen,
                "review": r,
                "page_url": f"{PAGES_BASE}/onepager.html?skill={r['ref']}",
                "not_an_endorsement": (
                    "Machine review of a redistributed skill. It judges this "
                    "converted file against our published principles — never the "
                    "upstream author's wider work, and never combined with a "
                    "community rating."
                ),
            })
        sr_dir = API / "reviews" / "skills"
        if sr_dir.exists():
            for p_old in sr_dir.glob("*.json"):
                if p_old not in kept_sr:
                    p_old.unlink(); changed += 1

    architectures = load("data/architectures.json", None)
    if architectures is not None:
        changed += stable_write(API / "architectures.json", dict(architectures))

    # RAPPVision storyboards: every entry, authored or aggregated, in the house
    # demo format. Published so the storyboard can be reviewed before anything
    # is filmed.
    wt_dir = REPO_ROOT / "media" / "walkthroughs"
    if wt_dir.is_dir():
        index = []
        for wt in sorted(wt_dir.glob("*.json")):
            doc = json.loads(wt.read_text(encoding="utf-8"))
            subj = doc["subject"]
            index.append({
                "slug": subj["slug"], "kind": subj["kind"], "ref": subj.get("ref"),
                "display_name": subj["display_name"],
                "runtime_seconds": doc["runtime_seconds"], "status": doc["status"],
                "storyboard_url": f"{PAGES_BASE}/media/walkthroughs/{wt.name}",
            })
        changed += stable_write(API / "walkthroughs.json", {
            "schema": "aibast-api-walkthroughs/1.0", "generated": gen,
            "format": "rappvision-walkthrough/1.0",
            "format_doc": f"{PAGES_BASE}/media/RAPPVISION.md",
            "note": ("Storyboards, not footage. Generated deterministically from each "
                     "entry's manifest; every figure a human must supply is marked "
                     "rather than invented. Aggregated skills get the same treatment "
                     "as authored agents — that is the point of aggregating here."),
            "count": len(index), "walkthroughs": index,
        })

    # Sentinel as a service anyone can drive against their OWN skills. The
    # rubric is published as data and the runtime is the caller's own — which
    # is the same portability the neighborhood already has, exposed over HTTP.
    hood = load("sentinel/NEIGHBORHOOD.json", None)
    if hood is not None:
        try:
            sys.path.insert(0, str(REPO_ROOT / "scripts"))
            import review_skills as _rs
            rubric_checks = _rs.PRINCIPLES
            rubric_version = _rs.RUBRIC_VERSION
        except Exception:
            rubric_checks, rubric_version = {}, "unknown"

        changed += stable_write(API / "sentinel" / "service.json", {
            "schema": "rapp-sentinel-service/1.0", "generated": gen,
            "summary": (
                "Run this library's review rubric against your own skills. The "
                "rubric is data and the runtime is yours: nothing here holds a "
                "credential, and no content you scan is sent to us."
            ),
            "scan_page": f"{PAGES_BASE}/scan.html",
            "neighborhood_url": f"{PAGES_BASE}/sentinel/NEIGHBORHOOD.json",
            "rubric": {"version": rubric_version, "principles": rubric_checks,
                       "reference_implementation":
                           f"https://github.com/{REPO}/blob/main/scripts/review_skills.py",
                       "browser_implementation": f"{PAGES_BASE}/sentinel.js"},
            "mirror": {
                "summary": ("skill.md and agent.py are two projections of one "
                            "contract; either can be derived from the other."),
                "browser_implementation": f"{PAGES_BASE}/mirror.js",
                "reference_implementation":
                    f"https://github.com/{REPO}/blob/main/scripts/export_agent.py",
            },
            "how_to_run": {
                "in_a_browser": (f"Load {PAGES_BASE}/sentinel.js and call "
                                 "RAPPSentinel.review(text) — deterministic residents only."),
                "locally": ("git clone the repository and run "
                            "`python3 scripts/sentinel.py run` — no token, no service."),
                "with_your_own_model": (
                    "A run with no model attached is DORMANT and yields no verdicts. "
                    "Point scripts/wake_sentinel.py at any OpenAI-compatible endpoint "
                    "(SENTINEL_ENDPOINT + SENTINEL_MODEL) to wake the interpretive "
                    "residents; the answer is recorded with your model attached."
                ),
            },
            "limits": (
                "Deterministic checks are exact and reproducible. Interpretive "
                "residents depend on whichever model you attach, so their findings "
                "carry that attribution and are not expected to reproduce byte for "
                "byte. Nothing here certifies a skill for use in your tenant."
            ),
        })

    sentinel_latest = load("sentinel/latest.json", None)
    if sentinel_latest is not None:
        changed += stable_write(API / "sentinel.json", {
            **sentinel_latest,
            "neighborhood_url": f"{PAGES_BASE}/sentinel/NEIGHBORHOOD.json",
            "how_to_run": (
                "Pull sentinel/NEIGHBORHOOD.json and run "
                "`python3 scripts/sentinel.py run` locally. The deterministic "
                "residents need no model; the interpretive ones emit packets any "
                "model can execute."
            ),
        })

    # An UNINSTALLED extension must stop serving. The previous index records
    # which namespaces each extension claimed, so removing its directory is
    # enough — the next build sweeps the endpoints it used to own.
    previous_ext = (load("api/v1/index.json", {}) or {}).get("extensions", {})
    extensions, ext_changed = run_extensions(API, agents, gen, PAGES_BASE)
    changed += ext_changed
    for proto, meta in previous_ext.items():
        if proto in extensions:
            continue
        for ns in meta.get("namespaces", []):
            target = (API / ns).resolve()
            if not target.is_relative_to(API.resolve()):
                continue
            if ns.endswith("/") and target.is_dir():
                for stale in sorted(target.rglob("*.json"), reverse=True):
                    stale.unlink(); changed += 1
            elif target.is_file():
                target.unlink(); changed += 1
        print(f"[build-api] extension {proto} uninstalled — its endpoints were removed",
              file=sys.stderr)

    changed += stable_write(API / "status.json", {
        "schema": "aibast-api-status/1.0", "generated": gen,
        "ok": True,
        "agents": stats.get("total_agents", len(agents)),
        "publishers": stats.get("publishers", len(pubs)),
        "categories": stats.get("categories", len(cats)),
        "aggregated_skills": ((aggregated or {}).get("stats") or {}).get("total", 0),
    })

    changed += stable_write(API / "badge.json", {
        "schemaVersion": 1, "label": "aibast agents",
        "message": str(stats.get("total_agents", len(agents))),
        "color": "blue",
    })

    changed += stable_write(API / "index.json", {
        "schema": SCHEMA, "generated": gen,
        "name": "AIBAST Agents Library API",
        "spec": "rapp-static-api/1.0",
        "base_urls": {"pages": f"{PAGES_BASE}/api/v1",
                      "raw": f"{RAW_BASE}/api/v1"},
        "docs": f"https://github.com/{REPO}/blob/main/docs/API.md",
        "endpoints": {
            "agents": "agents.json",
            "agent_detail": "agents/{publisher}/{slug}.json",
            "categories": "categories.json",
            "publishers": "publishers.json",
            "metrics": "metrics.json",
            "aggregated": "aggregated.json",
            "status": "status.json",
            "badge": "badge.json",
            "registry": "../../registry.json",
        },
        "extensions": extensions,
    })

    # ── Agent-first entry points ───────────────────────────────────────────
    # An autonomous reader should be able to answer "what is this and how do I
    # use it" from one fetch, then follow links — without scraping HTML. The
    # extension list is consumed generically, so a new extension appears here
    # with no edit (rapp/ext/PATTERN.md).
    ext_lines = []
    for proto, meta in sorted(extensions.items()):
        for line in meta.get("llms_lines", []):
            ext_lines.append(line.replace("{PAGES}", PAGES_BASE))
        ext_lines.append(f"- [{proto} specification]({PAGES_BASE}/{meta.get('spec','')}): "
                         f"originated by this distribution.")

    changed += stable_write(API / "agent.json", {
        "schema": "aibast-agent-entry/1.0", "generated": gen,
        "name": "AIBAST Agents Library (ms-rapp)",
        "what": ("A catalog of single-file AI agents for the Microsoft AI stack, plus the "
                 "runtime that executes them. Every surface is a static JSON file: no key, "
                 "no quota, CORS-open, safe to poll."),
        "read_this_first": f"{PAGES_BASE}/llms.txt",
        "full_text": f"{PAGES_BASE}/llms-full.txt",
        "api_root": f"{PAGES_BASE}/api/v1/index.json",
        "conventions": {
            "static_api": "rapp-static-api/1.0 — the repository is the API; pin a commit SHA in a raw URL for an immutable response.",
            "agent_format": "One file per agent. A __manifest__ dict carries name, version, description, tags, category, requires_env.",
            "naming": "@publisher/slug — the publisher is a GitHub username.",
        },
        # Core recipes, plus whatever the installed extensions contribute.
        "start_here": [
            {"goal": "List every agent", "get": "agents.json",
             "then": "Filter on .category or .tags; each entry carries raw_url."},
            {"goal": "Read one agent's source", "get": "agents/{publisher}/{slug}.json",
             "then": "Fetch .raw_url — it is plain Python, meant to be read before it is run."},
            {"goal": "Find agents for a use case", "get": "categories.json",
             "then": "Pick a category id, then filter agents.json by it."},
            {"goal": "Check adoption", "get": "metrics.json",
             "then": "Read .totals; methodology and caveats are documented on the metrics page."},
        ] + [r for m in extensions.values() for r in m.get("agent_recipes", [])],
        "rules_for_agents": [
            "Read an agent file before executing it. Single-file design exists so this is cheap.",
            "Never send secrets to this API; it is a public read-only catalog.",
            "Configuration for an agent comes from the environment via requires_env, never from the file.",
            "Treat unknown fields as ignorable — documents gain fields without a major version.",
            "Poll no more than the daily build cadence; nothing here changes faster.",
        ],
        "extensions": {p: {"spec": m.get("spec")} for p, m in sorted(extensions.items())},
        "human_ui": dict({"library": f"{PAGES_BASE}/agents.html",
                          "api_explorer": f"{PAGES_BASE}/api.html",
                          "metrics": f"{PAGES_BASE}/metrics.html"},
                         **{k: v for m in extensions.values()
                            for k, v in (m.get("human_ui") or {}).items()}),
        "license": "MIT (© Microsoft Corporation). Mirrored corpus under rapp/ carries upstream licenses.",
        "disclaimer": f"{PAGES_BASE}/DISCLAIMER.md",
    })

    cats = sorted({s["category"] for s in slim if s.get("category")})
    llms = f"""# AIBAST Agents Library (ms-rapp)

> Single-file AI agents for the Microsoft AI stack, the runtime that executes them, and the
> pinned protocol corpus they implement. Every machine-readable surface is a static JSON
> file — no key, no quota, CORS-open. {stats.get('total_agents', len(agents))} agents across
> {len(cats)} industries.

Agents: start at [agent.json]({PAGES_BASE}/api/v1/agent.json) — one fetch gives you what this
is, the endpoint map, and task recipes. Everything below is a plain fetch away.

## Start here
- [Agent entry point]({PAGES_BASE}/api/v1/agent.json): what this is, how to use it, task recipes.
- [API root]({PAGES_BASE}/api/v1/index.json): every endpoint, with base URLs for Pages and raw.
- [Full text]({PAGES_BASE}/llms-full.txt): this file plus the complete documentation vault inline.

## Catalog
- [All agents]({PAGES_BASE}/api/v1/agents.json): manifest, size, raw URL and engagement per agent.
- [Categories]({PAGES_BASE}/api/v1/categories.json): the {len(cats)} industries ({', '.join(cats[:6])}…).
- [Publishers]({PAGES_BASE}/api/v1/publishers.json): who publishes what.
- [Registry]({PAGES_BASE}/registry.json): the raw registry the installers read.

## Documentation
- [Publishing guide]({PAGES_BASE}/docs/PUBLISHING.md): how to contribute an agent.
- [Static API guide]({PAGES_BASE}/docs/API.md): endpoint reference.

## Protocol and governance
- [RAPP/1 specification]({PAGES_BASE}/rapp/spec/RAPP1-SPEC.md): the protocol this implements, pinned.
- [Corpus manifest]({PAGES_BASE}/rapp/MIRROR-MANIFEST.json): provenance and hash for every mirrored document.
- [Extension pattern]({PAGES_BASE}/rapp/ext/PATTERN.md): how this distribution adds capability.

## Optional
- [Adoption metrics]({PAGES_BASE}/api/v1/metrics.json): downloads, installs and engagement.
{chr(10).join(ext_lines)}

## Rules of the road
- Read an agent before running it. The single-file design exists to make that cheap.
- This API is read-only and public. Never send it a secret.
- Unknown fields are ignorable; documents gain fields without a major version bump.
- Nothing changes faster than the daily build — polling harder gains nothing.
"""
    changed += stable_write_text(REPO_ROOT / "llms.txt", llms)

    # llms-full.txt: the same map with the documentation inlined, for a reader
    # that would rather pay one fetch than forty.
    parts = [llms, "\n\n---\n\n# Documentation (full text)\n"]
    vault = REPO_ROOT / "brain"
    if vault.is_dir():
        for note in sorted(vault.rglob("*.md")):
            parts.append(f"\n\n## {note.relative_to(vault).as_posix()[:-3]}\n\n"
                         + note.read_text(encoding="utf-8"))
    changed += stable_write_text(REPO_ROOT / "llms-full.txt", "".join(parts))

    print(f"[build-api] {len(slim)} agents → api/v1/ ({changed} file(s) changed)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
