#!/usr/bin/env python3
"""Project canonical solution packages into deterministic delivery runbooks.

The package, catalog, registry, and evidence remain the sources of truth. This
module writes only 01-solutions/ and the marked taxonomy in 00-overview/README.md.
It deliberately does not execute package commands or infer deployment verdicts.
"""
from __future__ import annotations

import argparse
from collections import Counter
import fnmatch
import json
import math
from pathlib import Path, PurePosixPath
import posixpath
import re
import subprocess
import sys
import unicodedata
from urllib.parse import quote, unquote, urlsplit


ROOT = Path(__file__).resolve().parent.parent
RUNBOOK_SOLUTIONS = ("ask-hr", "building-permit-processing")
PACKAGE_ALIASES = {"production-line-optimization": "product-line-optimization"}
DRAFT_PACKAGES = {
    "grid-outage-response": (
        "Draft package with a flow and transcript corpus, but no catalog entry "
        "or deployment recipe; it is excluded from runbook generation."
    ),
}
JOURNEY_STAGES = (
    "Activate", "Create", "Decide", "Discover", "Empower", "Engage", "Expand",
    "Govern", "Innovate", "Learn", "Operate", "Optimize", "Plan", "Prioritize",
    "Protect", "Recover", "Resolve", "Retain", "Serve", "Understand",
)
ARTIFACTS = (
    "0.Resources/README.md", "1.Overview.md", "2.Architecture.md",
    "3.Runbook.md", "4.Sample-prompts.md",
)
OPTIONAL_ARTIFACTS = ("5.Acceptance-Evidence.md",)
REQUIRED_SECTIONS = {
    "0.Resources/README.md": (
        "Package Resources", "Workshop Pages", "Evidence and Exports", "Sources",
    ),
    "1.Overview.md": (
        "Scenario Overview", "Problem Statement", "Solution Summary",
        "Business Outcomes", "Target Users", "In Scope / Out of Scope",
        "Qualification Checklist", "What Actually Goes Wrong",
        "Related Patterns", "Sources", "Next",
    ),
    "2.Architecture.md": (
        "Solution Architecture", "Component Responsibilities", "Required Connections",
        "Copilot Studio Components", "Data and Evidence Boundary",
        "Production Replacement Seams", "Design Decisions", "Sources", "Next",
    ),
    "3.Runbook.md": (
        "Prerequisites", "Phase 1 — Easy Mode with GitHub Copilot",
        "Phase 2 — Optional Brainstem Track", "Phase 3 — Manual Build in Copilot Studio",
        "Phase 4 — Acceptance", "Phase 5 — Production Hardening",
        "Failure Recovery", "Deliverables Checklist", "Sources", "Next",
    ),
    "4.Sample-prompts.md": (
        "Suggested Agent Instructions", "Demo Prompts", "Promise-to-Prompt Map",
        "Expected Results", "Routing and Boundary Cases",
        "What This Agent Should Never Do", "Sources", "Next",
    ),
    "5.Acceptance-Evidence.md": (
        "Evidence Summary", "Release Gate Status", "Visual Evidence", "Sources", "Next",
    ),
}
DEFAULT_RELATED_PATTERNS = (
    "aibast:evidence-first-release-gate", "aibast:synthetic-snapshot-demo-agent",
    "runbooks:Human-in-the-Loop-Review-and-Approval",
    "runbooks:Agent-Publishing-and-Channel-Deployment",
)
GENERATED_MARKER = (
    "<!-- Generated by tools/build_solution_runbooks.py. Do not edit; change the sources and regenerate. -->"
)
TAXONOMY_BEGIN = "<!-- BEGIN GENERATED: solution-taxonomy (tools/build_solution_runbooks.py) -->"
TAXONOMY_END = "<!-- END GENERATED: solution-taxonomy -->"

PAGES = "https://microsoft.github.io/aibast-agents-library/"
CATALOG = "solutions/catalog.json"
REGISTRY = "registry.json"
NOTES = "solutions/runbook-notes.json"
PATTERNS = "02-patterns/patterns.json"
OVERVIEW = "00-overview/README.md"
INDEX = "01-solutions/README.md"
VERTICAL_NAMES = {
    "b2b_sales": "B2B Sales",
    "b2c_sales": "B2C Sales",
    "energy": "Energy",
    "financial_services": "Financial Services",
    "general": "Cross-Industry",
    "healthcare": "Healthcare",
    "human_resources": "Human Resources",
    "manufacturing": "Manufacturing",
    "professional_services": "Professional Services",
    "retail_cpg": "Retail & Consumer Goods",
    "slg_government": "State & Local Government",
    "software_digital_products": "Software & Digital Products",
}
_HEADING = re.compile(r"^ {0,3}(#{1,6})[ \t]+(.+?)[ \t]*#*[ \t]*$")
_SCHEME = re.compile(r"^[a-z][a-z0-9+.-]*:", re.I)
_SLUG = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*\Z")
_IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".avif"}


class RunbookSourceError(Exception):
    """A canonical identity or source contract cannot be resolved safely."""


def normalize_journey_stage(value: str) -> tuple[str, str | None]:
    if not isinstance(value, str) or not value.strip():
        raise RunbookSourceError("journey_stage must be a non-empty string")
    primary, _, secondary = value.strip().partition(" and ")
    primary, secondary = primary.strip(), secondary.strip()
    if not primary:
        raise RunbookSourceError("journey_stage has no primary stage")
    return (
        primary[:1].upper() + primary[1:],
        secondary[:1].upper() + secondary[1:] if secondary else None,
    )


def _file_universe(root: Path) -> frozenset[str]:
    result = subprocess.run(
        ["git", "-C", str(root), "ls-files", "-z", "--cached", "--others", "--exclude-standard"],
        capture_output=True, check=False,
    )
    if result.returncode:
        raise RunbookSourceError(
            "Cannot enumerate repository files with git ls-files: "
            + result.stderr.decode("utf-8", errors="replace").strip()
        )
    return frozenset(
        name for name in result.stdout.decode("utf-8").split("\0")
        if name and (root / name).is_file()
    )


def _json(root: Path, relative: str, files: frozenset[str], required: bool = False) -> dict:
    if relative not in files:
        if required:
            raise RunbookSourceError(f"Missing required source: {relative}")
        return {}
    try:
        value = json.loads((root / relative).read_text(encoding="utf-8"))
    except (OSError, UnicodeError, ValueError) as exc:
        raise RunbookSourceError(f"Cannot read JSON source {relative}: {exc}") from exc
    if not isinstance(value, dict):
        raise RunbookSourceError(f"{relative}: expected a JSON object")
    return value


class Solution:
    def __init__(self, name: str, slug: str, copy: dict, agent: dict, deployment: dict):
        self.name = name
        self.slug = slug
        self.copy = copy
        self.agent = agent
        self.deployment = deployment
        self.package = f"solutions/{slug}"
        self.architecture_source = f"state/architecture_level2_sources/{name.rsplit('/', 1)[-1]}.json"
        self.demo_source = f"tests/demo_cases/{slug}.json"
        self.stage, self.secondary_stage = normalize_journey_stage(copy.get("journey_stage"))

    @property
    def display_name(self) -> str:
        return _text(self.copy.get("display_name"), self.slug)

    @property
    def vertical(self) -> str:
        return VERTICAL_NAMES[self.agent["category"]]

    def path(self, relative: str) -> str:
        return f"{self.package}/{relative}"


class Library:
    def __init__(
        self, root: Path, files: frozenset[str], catalog: dict,
        solutions: dict[str, Solution], patterns: dict[str, dict], notes: dict,
    ):
        self.root = root
        self.files = files
        self.catalog = catalog
        self.solutions = solutions
        self.by_name = {solution.name: solution for solution in solutions.values()}
        self.patterns = patterns
        self.notes = notes
        self.directories = frozenset(
            str(parent) for name in files for parent in PurePosixPath(name).parents
            if str(parent) != "."
        )

    def exists(self, relative: str) -> bool:
        relative = relative.rstrip("/")
        return relative in self.files or relative in self.directories

    def json(self, relative: str, required: bool = False) -> dict:
        return _json(self.root, relative, self.files, required)

    def matching(self, pattern: str) -> list[str]:
        return sorted(name for name in self.files if fnmatch.fnmatchcase(name, pattern))


def load_library(root: Path = ROOT) -> Library:
    root = Path(root).resolve()
    files = _file_universe(root)
    catalog = _json(root, CATALOG, files, required=True).get("solutions")
    agents = _json(root, REGISTRY, files, required=True).get("agents")
    if not isinstance(catalog, dict) or not catalog:
        raise RunbookSourceError(f"{CATALOG}: solutions must be a non-empty object")
    if not isinstance(agents, list):
        raise RunbookSourceError(f"{REGISTRY}: agents must be an array")

    canonical_names = set()
    for name, copy in catalog.items():
        if (
            not name.startswith("@aibast-agents-library/")
            or not _SLUG.fullmatch(name.removeprefix("@aibast-agents-library/"))
            or not isinstance(copy, dict)
        ):
            raise RunbookSourceError(f"{CATALOG}: invalid canonical solution {name!r}")
        canonical_names.add(name.rsplit("/", 1)[-1])
    for name, slug in PACKAGE_ALIASES.items():
        if name not in canonical_names or name == slug or not _SLUG.fullmatch(slug):
            raise RunbookSourceError(f"Stale or invalid package alias: {name} -> {slug}")
    if len(set(PACKAGE_ALIASES.values())) != len(PACKAGE_ALIASES):
        raise RunbookSourceError("Package aliases must have distinct target folders")

    package_dirs = {
        name.split("/")[1] for name in files
        if name.startswith("solutions/") and name.count("/") >= 2
        and name.split("/")[1] != "_shared"
    }
    package_dirs.update(
        path.name for path in (root / "solutions").iterdir()
        if path.is_dir() and path.name != "_shared"
    )
    for slug, reason in DRAFT_PACKAGES.items():
        if not isinstance(reason, str) or not reason.strip():
            raise RunbookSourceError(f"Draft package {slug} needs a non-empty reason")
        if slug not in package_dirs:
            raise RunbookSourceError(f"Stale draft allowlist entry: {slug} has no package")
        if slug in canonical_names or slug in PACKAGE_ALIASES.values():
            raise RunbookSourceError(f"Stale draft allowlist entry: {slug} is a catalog package")

    packages: dict[str, tuple[str, dict]] = {}
    for slug in sorted(package_dirs - DRAFT_PACKAGES.keys()):
        path = f"solutions/{slug}/deployment.json"
        if path not in files:
            raise RunbookSourceError(f"Orphan package solutions/{slug}: missing deployment.json")
        deployment = _json(root, path, files, required=True)
        name = deployment.get("name")
        if not isinstance(name, str) or name not in catalog:
            raise RunbookSourceError(f"Orphan package {path}: name {name!r} is not in {CATALOG}")
        if name in packages:
            raise RunbookSourceError(
                f"Duplicate package identity {name}: solutions/{packages[name][0]} and solutions/{slug}"
            )
        canonical = name.rsplit("/", 1)[-1]
        expected_slug = PACKAGE_ALIASES.get(canonical, canonical)
        if slug != expected_slug:
            raise RunbookSourceError(
                f"{path}: {name} must use package folder {expected_slug}; "
                "declare a necessary alias in PACKAGE_ALIASES"
            )
        packages[name] = (slug, deployment)

    solutions = {}
    for name, copy in sorted(catalog.items()):
        if name not in packages:
            expected = PACKAGE_ALIASES.get(name.rsplit("/", 1)[-1], name.rsplit("/", 1)[-1])
            raise RunbookSourceError(f"Missing package for {name}: solutions/{expected}/deployment.json")
        matches = [agent for agent in agents if isinstance(agent, dict) and agent.get("name") == name]
        if len(matches) != 1:
            raise RunbookSourceError(
                f"{REGISTRY}: expected exactly one agent named {name}; found {len(matches)}"
            )
        agent = matches[0]
        if not isinstance(agent.get("_solution"), dict):
            raise RunbookSourceError(f"{REGISTRY}: {name} has no _solution object")
        if agent.get("category") not in VERTICAL_NAMES:
            raise RunbookSourceError(f"{REGISTRY}: {name} has unknown category {agent.get('category')!r}")
        slug, deployment = packages[name]
        solution = Solution(name, slug, copy, agent, deployment)
        if solution.stage not in JOURNEY_STAGES:
            raise RunbookSourceError(
                f"{CATALOG}: {name} has unknown journey stage {solution.stage!r}"
            )
        solutions[slug] = solution
    for name, slug in PACKAGE_ALIASES.items():
        if slug not in solutions or solutions[slug].name != f"@aibast-agents-library/{name}":
            raise RunbookSourceError(f"Stale package alias: {name} -> {slug}")

    pattern_data = _json(root, PATTERNS, files, required=True)
    patterns = {}
    for group in ("aibast_patterns", "runbooks_patterns"):
        rows = pattern_data.get(group)
        if not isinstance(rows, list):
            raise RunbookSourceError(f"{PATTERNS}: {group} must be an array")
        for row in rows:
            if not isinstance(row, dict) or not isinstance(row.get("id"), str):
                raise RunbookSourceError(f"{PATTERNS}: every pattern needs a string id")
            identifier = row["id"]
            if identifier in patterns:
                raise RunbookSourceError(f"{PATTERNS}: duplicate pattern id {identifier}")
            if not row.get("title"):
                raise RunbookSourceError(f"{PATTERNS}: {identifier} has no title")
            if identifier.startswith("runbooks:") and not row.get("url"):
                raise RunbookSourceError(f"{PATTERNS}: {identifier} has no url")
            patterns[identifier] = row
    for identifier in DEFAULT_RELATED_PATTERNS:
        if identifier not in patterns:
            raise RunbookSourceError(f"{PATTERNS}: missing default related pattern {identifier}")

    note_data = _json(root, NOTES, files)
    notes = note_data.get("solutions", {})
    if not isinstance(notes, dict):
        raise RunbookSourceError(f"{NOTES}: solutions must be an object")
    for name, entry in notes.items():
        if name not in catalog or not isinstance(entry, dict):
            raise RunbookSourceError(f"{NOTES}: invalid solution notes for {name}")
        sources = entry.get("sources", [])
        if not isinstance(sources, list) or (set(entry) - {"sources"} and not sources):
            raise RunbookSourceError(f"{NOTES}: {name} requires a non-empty sources array")
        for source in sources:
            if not isinstance(source, str) or source not in files:
                raise RunbookSourceError(f"{NOTES}: {name} has missing source {source!r}")
        for field in (
            "target_users", "scope_in", "scope_out", "qualification_checklist",
            "what_goes_wrong", "related_patterns",
        ):
            if field in entry and not isinstance(entry[field], list):
                raise RunbookSourceError(f"{NOTES}: {name}.{field} must be an array")
        for identifier in entry.get("related_patterns", []):
            if not isinstance(identifier, str) or identifier not in patterns:
                raise RunbookSourceError(f"{NOTES}: {name} has unknown related pattern {identifier!r}")
    return Library(root, files, catalog, solutions, patterns, notes)


def _present(value) -> bool:
    if value is None:
        return False
    if isinstance(value, float) and not math.isfinite(value):
        return False
    if isinstance(value, (str, list, tuple, dict)):
        return bool(value) and (not isinstance(value, str) or bool(value.strip()))
    return True


def _text(value, fallback: str = "Not recorded") -> str:
    if not _present(value):
        return fallback
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, dict):
        parts = [f"{_label(key)}: {_text(item)}" for key, item in value.items() if _present(item)]
        return "; ".join(parts) or fallback
    if isinstance(value, (list, tuple)):
        return "; ".join(_text(item) for item in value if _present(item)) or fallback
    text = str(value).strip()
    return fallback if text in {"None", "null", "nan", "{}", "[]"} else text


def _items(value) -> list:
    if not _present(value):
        return []
    return list(value) if isinstance(value, (list, tuple)) else [value]


def _object(value) -> dict:
    return value if isinstance(value, dict) else {}


def _label(value) -> str:
    text = str(value).replace("_", " ").strip()
    return text[:1].upper() + text[1:]


def _cell(value) -> str:
    text = _text(value)
    text = re.sub(r"(?<!\\)\|", r"\\|", text)
    return re.sub(r"\s*\n\s*", "<br>", text.replace("\r\n", "\n").replace("\r", "\n"))


def _table(headers, rows, missing: str) -> str:
    rows = list(rows)
    if not rows:
        return missing
    lines = [
        "| " + " | ".join(_cell(header) for header in headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    lines.extend("| " + " | ".join(_cell(value) for value in row) + " |" for row in rows)
    return "\n".join(lines)


def _bullets(value, missing: str, checklist: bool = False) -> str:
    items = [item for item in _items(value) if _present(item)]
    prefix = "- [ ] " if checklist else "- "
    return "\n".join(prefix + _text(item).replace("\n", "\n  ") for item in items) or missing


def _code(value, language: str = "text") -> str:
    body = _text(value)
    longest = max((len(m.group()) for m in re.finditer(r"`+", body)), default=0)
    fence = "`" * max(3, longest + 1)
    return f"{fence}{language}\n{body}\n{fence}"


def _finish(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n").rstrip() + "\n"


def _slug_heading(text: str) -> str:
    text = re.sub(r"!?\[([^\]]*)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"<[^>]+>", "", text.replace("`", "")).strip().lower()
    return "".join(
        character for character in text
        if unicodedata.category(character)[0] in "LN"
        or unicodedata.category(character) == "Mn" or character in " -_"
    ).replace(" ", "-")


def _visible_lines(text: str):
    fence = None
    for line in text.splitlines():
        marker = re.match(r"^\s{0,3}(`{3,}|~{3,})", line)
        if fence:
            yield line, False
            if marker and marker[1][0] == fence[0] and len(marker[1]) >= len(fence):
                fence = None
        elif marker:
            fence = marker[1]
            yield line, False
        else:
            yield line, True


def _section(text: str, title: str) -> str | None:
    lines = list(_visible_lines(text))
    for index, (line, visible) in enumerate(lines):
        match = _HEADING.match(line) if visible else None
        if match and match[2].casefold() == title.casefold():
            end = index + 1
            while end < len(lines):
                next_line, next_visible = lines[end]
                next_heading = _HEADING.match(next_line) if next_visible else None
                if next_heading and len(next_heading[1]) <= len(match[1]):
                    break
                end += 1
            return "\n".join(item[0] for item in lines[index + 1:end]).strip()
    return None


def _relative_url(library: Library, source: str, target: str, destination: str) -> str:
    if not target or target.startswith("//") or _SCHEME.match(target):
        return target
    split = urlsplit(target)
    decoded = unquote(split.path)
    resolved = (
        source if not decoded else
        posixpath.normpath(decoded.lstrip("/")) if decoded.startswith("/") else
        posixpath.normpath(posixpath.join(posixpath.dirname(source), decoded))
    )
    if resolved == ".." or resolved.startswith("../"):
        raise RunbookSourceError(f"{source}: copied link escapes repository: {target}")
    if resolved.endswith(".html"):
        if resolved not in library.files:
            raise RunbookSourceError(f"{source}: missing Pages target {resolved}")
        path = PAGES + quote(resolved, safe="/@-._~")
    else:
        path = quote(posixpath.relpath(resolved, posixpath.dirname(destination)), safe="/@-._~")
        if decoded.endswith("/") and not path.endswith("/"):
            path += "/"
    return path + ("?" + split.query if split.query else "") + ("#" + split.fragment if split.fragment else "")


def _rebase_inline(line: str, transform) -> str:
    # A balanced scan keeps URLs with parentheses and optional link titles intact.
    output, cursor = [], 0
    while True:
        start = line.find("](", cursor)
        if start < 0:
            output.append(line[cursor:])
            break
        target_start = start + 2
        while target_start < len(line) and line[target_start].isspace():
            target_start += 1
        target_end = target_start
        if target_start < len(line) and line[target_start] == "<":
            target_start += 1
            target_end = line.find(">", target_start)
            if target_end < 0:
                output.append(line[cursor:])
                break
        else:
            depth = 0
            while target_end < len(line):
                character = line[target_end]
                if character == "\\":
                    target_end += 2
                    continue
                if character == "(":
                    depth += 1
                elif character == ")":
                    if depth == 0:
                        break
                    depth -= 1
                elif character.isspace() and depth == 0:
                    break
                target_end += 1
        if target_end <= target_start:
            output.append(line[cursor:start + 2])
            cursor = start + 2
            continue
        output.append(line[cursor:target_start])
        output.append(transform(line[target_start:target_end]))
        cursor = target_end
    return "".join(output)


def _mark_missing_links(library: Library, line: str, destination: str) -> str:
    def replace(match):
        target = match[2].strip("<>")
        if _SCHEME.match(target) or target.startswith("//"):
            return match[0]
        path = unquote(urlsplit(target).path)
        resolved = (
            destination if not path
            else posixpath.normpath(posixpath.join(posixpath.dirname(destination), path))
        )
        if library.exists(resolved):
            return match[0]
        return f"{match[1]} (missing source: `{resolved}`)"

    return re.sub(
        r"!?\[([^\]]+)\]\(\s*(<[^>]+>|[^\s)]+)(?:\s+(?:\"[^\"]*\"|'[^']*'))?\s*\)",
        replace, line,
    )


def _copy_markdown(library: Library, text: str, source: str, destination: str) -> str:
    text = re.sub(r"<!--.*?-->", "", text, flags=re.S)
    out = []
    for line, visible in _visible_lines(text):
        if not visible:
            out.append(line)
            continue
        match = _HEADING.match(line)
        if match:
            if len(match[1]) == 1:
                continue
            line = "#" * min(6, len(match[1]) + 1) + " " + match[2]
        transform = lambda target: _relative_url(library, source, target, destination)
        # Inline code is source text, not a Markdown link destination.
        segments = re.split(r"(`+[^`]*`+)", line)
        for index in range(0, len(segments), 2):
            segment = _rebase_inline(segments[index], transform)
            segment = re.sub(
                r"^(\s{0,3}\[[^\]]+\]:\s*)(<[^>]+>|\S+)",
                lambda m: m[1] + (
                    "<" + transform(m[2][1:-1]) + ">" if m[2].startswith("<") else transform(m[2])
                ), segment,
            )
            segment = re.sub(
                r"(\b(?:href|src)\s*=\s*)([\"'])(.*?)(\2)",
                lambda m: m[1] + m[2] + transform(m[3]) + m[4], segment, flags=re.I,
            )
            segments[index] = _mark_missing_links(library, segment, destination)
        out.append("".join(segments))
    return re.sub(r"\n{3,}", "\n\n", "\n".join(out)).strip()


class Document:
    def __init__(self, library: Library, solution: Solution, artifact: str):
        self.library = library
        self.solution = solution
        self.artifact = artifact
        self.path = f"01-solutions/{solution.slug}/{artifact}"
        self.sources = {CATALOG}
        self.sections: dict[str, str] = {}

    def source(self, relative: str) -> None:
        if relative in self.library.files:
            self.sources.add(relative)

    def data(self, relative: str) -> dict:
        self.source(relative)
        return self.library.json(relative)

    def link(self, relative: str, label: str | None = None, fragment: str = "") -> str:
        relative = relative.rstrip("/")
        if not self.library.exists(relative):
            return f"{label or relative} — missing source `{relative}`"
        if relative.endswith(".html"):
            target = PAGES + quote(relative, safe="/@-._~")
        else:
            target = quote(
                posixpath.relpath(relative, posixpath.dirname(self.path)), safe="/@-._~",
            )
        if fragment:
            target += "#" + fragment
        return f"[{label or relative}]({target})"

    def missing(self, source: str, field: str | None = None) -> str:
        if field:
            return f"Not provided — `{field}` is absent from {self.link(source)}."
        return f"Not available — source `{source}` is missing."

    def copy(self, relative: str, title: str | None = None, alternatives: tuple[str, ...] = ()) -> str:
        if relative not in self.library.files:
            return self.missing(relative)
        self.source(relative)
        text = (self.library.root / relative).read_text(encoding="utf-8")
        prefix = ""
        if title is not None:
            body = _section(text, title)
            if not body:
                prefix = f"Source section “{title}” is not present in {self.link(relative)}."
                for alternative in alternatives:
                    body = _section(text, alternative)
                    if body:
                        title = alternative
                        break
                if not body:
                    return prefix
            text = body
        content = _copy_markdown(self.library, text, relative, self.path)
        if not content:
            return f"No content is provided in {self.link(relative)}" + (f" for “{title}”." if title else ".")
        source_link = self.link(
            relative, PurePosixPath(relative).name + (f" — {title}" if title else ""),
            _slug_heading(title) if title else "",
        )
        attribution = f"From {source_link}:"
        return "\n\n".join(part for part in (prefix, attribution, content) if part)

    def inventory(self, pattern: str, description: str) -> str:
        paths = self.library.matching(pattern)
        return _table(
            ("File", "Role"),
            ((self.link(path, path.removeprefix(self.solution.package + "/")), description) for path in paths),
            f"No files matching `{pattern}` are present in the package.",
        )

    def add(self, title: str, content: str) -> None:
        if not content.strip():
            raise RunbookSourceError(f"{self.path}: empty generated section {title}")
        self.sections[title] = content.strip()

    def render(self, title: str, next_line: str) -> str:
        self.sections["Sources"] = "\n".join(
            "- " + self.link(path) for path in sorted(self.sources)
        )
        if "Next" in REQUIRED_SECTIONS[self.artifact]:
            self.sections["Next"] = next_line
        else:
            self.sections["Sources"] += "\n\n" + next_line
        if set(self.sections) != set(REQUIRED_SECTIONS[self.artifact]):
            raise RunbookSourceError(f"{self.path}: renderer does not implement its H2 section contract")
        chunks = [GENERATED_MARKER, "", f"# {self.solution.display_name} — {title}"]
        for heading in REQUIRED_SECTIONS[self.artifact]:
            chunks += ["", f"## {heading}", "", self.sections[heading]]
        return _finish("\n".join(chunks))


def _nav(next_file: str, next_title: str) -> str:
    return f"→ [{next_title}]({next_file}) | [Solution index](../README.md)"


def _overview(library: Library, solution: Solution) -> str:
    doc = Document(library, solution, "1.Overview.md")
    copy = solution.copy
    agent = solution.agent
    metadata = _object(agent.get("_solution"))
    architecture = _object(copy.get("architecture"))
    notes = _object(library.notes.get(solution.name))
    doc.source(REGISTRY)
    if notes:
        doc.source(NOTES)
        doc.sources.update(notes.get("sources", []))
    properties = [
        ("Vertical", solution.vertical),
        ("Industries", _text(metadata.get("industries"), "Not recorded in registry _solution.industries")),
        ("Journey stage — primary", solution.stage),
        ("Journey stage — secondary", solution.secondary_stage or "No secondary stage recorded"),
        ("Personas", _text(metadata.get("personas"), "Not recorded in registry _solution.personas")),
        ("Microsoft platforms", _text(
            _items(metadata.get("agent_requirements")) + _items(metadata.get("featured_tools")),
            "Not recorded in registry _solution",
        )),
        ("Quality tier", _text(agent.get("quality_tier"), "Not recorded in registry quality_tier")),
        ("Search terms", _text(copy.get("search_terms"), "Not recorded in catalog search_terms")),
        ("Agent file", doc.link(_text(agent.get("_file"), "missing-agent-source"))),
        ("Workshop", doc.link(solution.path("quest.html"), "Open the guided workshop")),
        ("Runbook status", "Generated delivery projection; not a deployment or production-readiness verdict"),
    ]
    scenario = _table(("Property", "Value"), properties, doc.missing(REGISTRY))
    scenario += "\n\n" + _text(copy.get("sales_headline"), doc.missing(CATALOG, "sales_headline"))
    scenario += "\n\n" + _text(copy.get("card_pitch"), doc.missing(CATALOG, "card_pitch"))
    scenario += "\n\n**Why try it:** " + _text(copy.get("why_try"), doc.missing(CATALOG, "why_try"))
    doc.add("Scenario Overview", scenario)
    doc.add("Problem Statement", _text(copy.get("customer_challenge"), doc.missing(CATALOG, "customer_challenge")))
    capabilities = _items(architecture.get("capabilities"))
    capability_list = [
        "**" + _text(_object(item).get("name"), "Capability") + "** — "
        + _text(_object(item).get("purpose"), "Purpose not provided in catalog architecture.capabilities")
        if isinstance(item, dict) else _text(item) for item in capabilities
    ]
    doc.add("Solution Summary", "\n\n".join((
        _text(copy.get("microsoft_ai_story"), doc.missing(CATALOG, "microsoft_ai_story")),
        "**Blueprint role:** " + _text(copy.get("blueprint_role"), doc.missing(CATALOG, "blueprint_role")),
        _bullets(capability_list, doc.missing(CATALOG, "architecture.capabilities")),
        "The blueprint describes integration targets, not live connections in the packaged synthetic demo; "
        "see the " + doc.link(solution.path("FIELD-GUIDE.md"), "evidence boundary", "evidence-boundary") + ".",
    )))
    doc.source(solution.path("FIELD-GUIDE.md"))
    doc.source("solutions/README.md")
    doc.add("Business Outcomes", _bullets(copy.get("business_value"), doc.missing(CATALOG, "business_value"))
            + "\n\nClaims are qualitative; synthetic demo figures are not customer results or performance commitments. "
            + "See the " + doc.link("solutions/README.md", "claims policy", "claims-policy") + ".")
    if notes.get("target_users"):
        target_rows = [
            (_object(item).get("role"), _object(item).get("need"))
            for item in notes["target_users"]
        ]
    else:
        target_rows = [
            (_text(persona), "Registry persona; a delivery-specific need is not yet authored in runbook-notes.json")
            for persona in _items(metadata.get("personas"))
        ]
    doc.add("Target Users", _table(("Role", "Need"), target_rows, doc.missing(REGISTRY, "_solution.personas")))
    scope_in = (
        _bullets(notes["scope_in"], doc.missing(NOTES, "scope_in"))
        if notes.get("scope_in") else doc.copy(solution.path("README.md"), "Scope")
    )
    scope_out = (
        _bullets(notes["scope_out"], doc.missing(NOTES, "scope_out"))
        if notes.get("scope_out") else doc.copy(solution.path("README.md"), "Approval boundary")
    )
    doc.add("In Scope / Out of Scope", f"### In scope\n\n{scope_in}\n\n### Out of scope / approval boundary\n\n{scope_out}")
    doc.add("Qualification Checklist", _bullets(
        notes.get("qualification_checklist"),
        "Not yet authored — add `qualification_checklist` to `solutions/runbook-notes.json`.",
        checklist=True,
    ))
    if notes.get("what_goes_wrong"):
        failures = _table(
            ("Issue", "Response"),
            ((_object(item).get("issue"), _object(item).get("response")) for item in notes["what_goes_wrong"]),
            doc.missing(NOTES, "what_goes_wrong"),
        )
    else:
        failures = doc.copy(solution.path("FIELD-GUIDE.md"), "Failure recovery")
    doc.add("What Actually Goes Wrong", failures)
    doc.source(PATTERNS)
    links = []
    for identifier in notes.get("related_patterns") or DEFAULT_RELATED_PATTERNS:
        pattern = library.patterns[identifier]
        if identifier.startswith("aibast:") and pattern.get("status") == "Planned":
            links.append(doc.link("02-patterns/README.md", pattern["title"] + " (planned)"))
        elif identifier.startswith("runbooks:"):
            links.append(f"[{pattern['title']}]({pattern['url']})")
        else:
            folder = pattern.get("folder")
            links.append(doc.link(f"02-patterns/{folder}/{folder}.md", pattern["title"]))
    doc.add("Related Patterns", _bullets(links, doc.missing(PATTERNS)))
    return doc.render("Overview", _nav("2.Architecture.md", "Architecture"))


def _named_rows(value):
    for item in _items(value):
        if isinstance(item, dict):
            yield item.get("name") or item.get("title"), item.get("detail") or item.get("purpose") or item.get("description")
        else:
            yield _text(item), "No additional detail recorded"


def _architecture(library: Library, solution: Solution) -> str:
    doc = Document(library, solution, "2.Architecture.md")
    architecture = _object(solution.copy.get("architecture"))
    deployment = doc.data(solution.path("deployment.json"))
    level2 = doc.data(solution.architecture_source)
    global_instructions = solution.path("manual/GLOBAL-INSTRUCTIONS.md")
    field_guide = solution.path("FIELD-GUIDE.md")
    flow = _items(architecture.get("business_flow"))
    if flow:
        lines = ["flowchart LR"]
        for index, item in enumerate(flow):
            label = _text(item).replace('"', "#quot;").replace("\n", "<br/>")
            lines.append(f'    n{index}["{label}"]')
        lines += [f"    n{index} --> n{index + 1}" for index in range(len(flow) - 1)]
        diagram = _code("\n".join(lines), "mermaid")
    else:
        diagram = doc.missing(CATALOG, "architecture.business_flow")
    doc.add("Solution Architecture", diagram + "\n\n"
            + doc.link(solution.path("FLOW.md"), "Package case-flow diagram")
            + "\n\nThis catalog flow includes production integration targets; it is not proof of live connectivity. "
            + "Use the data and evidence boundary below when demonstrating the package.")
    doc.source(solution.path("FLOW.md"))
    doc.source(REGISTRY)
    components = _table(
        ("Operation", "Capability", "Purpose"),
        ((_object(item).get("operation"), _object(item).get("name"), _object(item).get("purpose"))
         for item in _items(architecture.get("capabilities"))),
        doc.missing(CATALOG, "architecture.capabilities"),
    )
    components += "\n\n" + _table(("Runtime reference", "Recorded value"), (
        ("Agent file", doc.link(_text(solution.agent.get("_file"), "missing-agent-source"))),
        ("Expected tool", _text(deployment.get("expected_tool"), "Not recorded in deployment.json expected_tool")),
        ("Source SHA-256 (short)", _text(solution.agent.get("_sha256"), "Not recorded in registry _sha256")[:12]
         if solution.agent.get("_sha256") else "Not recorded in registry _sha256"),
    ), doc.missing(REGISTRY))
    doc.add("Component Responsibilities", components)
    connections = _bullets(architecture.get("required_connections"), doc.missing(CATALOG, "architecture.required_connections"))
    domain_rows = []
    domains = level2.get("domains")
    if isinstance(domains, dict):
        for name, values in sorted(domains.items()):
            domain_rows.extend((_label(name), component, detail) for component, detail in _named_rows(values))
    elif domains:
        domain_rows.extend(("Domain", component, detail) for component, detail in _named_rows(domains))
    doc.add("Required Connections", "\n\n".join((
        "### Connection requirements from the blueprint",
        connections,
        "These are integration requirements, not evidence that a connection is configured; "
        "apply the package's production replacement and approval gates.",
        "### Level-2 domains",
        _table(("Domain", "Component", "Responsibility"), domain_rows, doc.missing(solution.architecture_source, "domains")),
        "### Level-2 tools",
        _table(("Tool", "Responsibility"), _named_rows(level2.get("tools")), doc.missing(solution.architecture_source, "tools")),
        "### Supporting features",
        _table(("Feature", "Responsibility"), _named_rows(level2.get("supporting_features")),
               doc.missing(solution.architecture_source, "supporting_features")),
    )))
    doc.add("Copilot Studio Components", "\n\n".join((
        "### Source-controlled behaviors",
        doc.inventory(solution.path("copilot-studio/behaviors/*.mcs.yml"), "Copilot Studio behavior definition"),
        "### Source-controlled knowledge",
        doc.inventory(solution.path("copilot-studio/capabilities/knowledge/files/*"), "Knowledge content or its component metadata"),
        "### Manual upload skills",
        doc.inventory(solution.path("manual/skills/*/SKILL.md"), "Reviewed skill for the literal browser build"),
    )))
    doc.add("Data and Evidence Boundary", doc.copy(
        global_instructions, "Fixed synthetic snapshot",
        ("Pilot data boundary", "Fixed evidence policy", "Boundaries", "Grounding"),
    ) + "\n\n" + doc.copy(field_guide, "Evidence boundary"))
    doc.add("Production Replacement Seams", doc.copy(field_guide, "Production replacement seams"))
    doc.source(global_instructions)
    doc.source(field_guide)
    doc.source(solution.path("evals/transcripts.json"))
    decisions = (
        ("Keep demo evidence separate from production results",
         "The field guide limits packaged records and outcomes to synthetic workflow evidence.",
         doc.link(field_guide, "Evidence boundary", "evidence-boundary")),
        ("Preserve the package's instruction boundary",
         "Use the reviewed global instructions rather than treating a blueprint platform as a live tool.",
         doc.link(global_instructions, "Global instructions")),
        ("Keep Easy and Manual construction distinct",
         "The manual lane uses the browser and reviewed uploads, not CLI or YAML import.",
         doc.link(field_guide, "Manual mode", "manual-mode--literal-browser-construction")),
        ("Replay the recorded corpus before release",
         "Compare exact case prompts and expected entities; file presence alone is not a new runtime pass.",
         doc.link(solution.path("evals/transcripts.json"), "Canonical transcripts")),
        ("Stop the workshop at Draft",
         "Publication is a separate approval gate, not a generated-runbook deliverable.",
         doc.link(field_guide, "Evidence gates", "evidence-gates")),
    )
    doc.add("Design Decisions", _table(("Decision", "Reason / boundary", "Source"), decisions, doc.missing(field_guide)))
    return doc.render("Architecture", _nav("3.Runbook.md", "Delivery runbook"))


def _release_checklist(doc: Document) -> str:
    relative = "solutions/README.md"
    if relative not in doc.library.files:
        return doc.missing(relative)
    doc.source(relative)
    source = (doc.library.root / relative).read_text(encoding="utf-8")
    body = _section(source, "Release gate")
    if not body:
        return f"Source section “Release gate” is not present in {doc.link(relative)}."
    items = []
    active = False
    for line, visible in _visible_lines(body):
        if not visible:
            active = False
            continue
        match = re.match(r"^\d+[.)]\s+(.+)", line)
        if match:
            items.append(match[1])
            active = True
        elif active and line.startswith((" ", "\t")) and line.strip():
            items[-1] += " " + line.strip()
        else:
            active = False
    content = _bullets(items, f"No numbered release checks are present in {doc.link(relative, 'Release gate', 'release-gate')}.", checklist=True)
    return _copy_markdown(doc.library, content, relative, doc.path)


def _runbook(library: Library, solution: Solution) -> str:
    doc = Document(library, solution, "3.Runbook.md")
    architecture = _object(solution.copy.get("architecture"))
    deployment = doc.data(solution.path("deployment.json"))
    studio = _object(deployment.get("copilot_studio"))
    guide = solution.path("FIELD-GUIDE.md")
    doc.source(guide)
    prerequisites = _table(("Recipe prerequisite", "Recorded requirement"), (
        ("Copilot Studio plugin", _text(studio.get("plugin"), "Not provided in deployment.json copilot_studio.plugin")),
        ("Minimum PAC CLI version", _text(studio.get("minimum_pac_version"), "Not provided in deployment.json copilot_studio.minimum_pac_version")),
        ("Authoring mode", _text(studio.get("authoring_mode"), "Not provided in deployment.json copilot_studio.authoring_mode")),
        ("Portable tool to verify", _text(deployment.get("expected_tool"), "Not provided in deployment.json expected_tool")),
    ), doc.missing(solution.path("deployment.json")))
    doc.add("Prerequisites", "\n\n".join((
        prerequisites,
        "### Catalog preparation checklist",
        "The catalog includes production connection work. Apply those steps only after the package's "
        + doc.link(guide, "approval and evidence gates", "evidence-gates")
        + "; the workshop remains a synthetic, unpublished Draft.",
        _bullets(architecture.get("easy_mode"), doc.missing(CATALOG, "architecture.easy_mode"), checklist=True),
        "### Connections to qualify, not assumed live",
        _bullets(architecture.get("required_connections"), doc.missing(CATALOG, "architecture.required_connections")),
    )))
    phase1 = doc.copy(solution.path("EASY-MODE-COPILOT-CHAT.md"))
    prompt = architecture.get("copilot_studio_prompt")
    phase1 += "\n\n### Recipe-specific authoring prompt\n\n"
    phase1 += (
        "Catalog reference for the source-controlled lane; retain the Draft-only completion boundary above.\n\n" + _code(prompt)
        if _present(prompt) else doc.missing(CATALOG, "architecture.copilot_studio_prompt")
    )
    doc.add("Phase 1 — Easy Mode with GitHub Copilot", phase1)
    phase2 = doc.copy(solution.path("EASY-MODE-PERSONLESS.md"))
    brainstem = _object(deployment.get("brainstem"))
    phase2 += "\n\n### Optional runtime endpoints\n\n" + _table(
        ("Recipe field", "Value"),
        ((key, f"`{_text(brainstem[key])}`") for key in ("health_url", "chat_url", "ui_url") if _present(brainstem.get(key))),
        doc.missing(solution.path("deployment.json"), "brainstem endpoints"),
    )
    install_prompt = architecture.get("local_install_prompt")
    phase2 += "\n\n### Recipe-specific local installation prompt\n\n" + (
        "Catalog reference for the optional local lane:\n\n" + _code(install_prompt)
        if _present(install_prompt) else doc.missing(CATALOG, "architecture.local_install_prompt")
    )
    doc.add("Phase 2 — Optional Brainstem Track", phase2)
    manual = doc.copy(guide, "Manual mode — literal browser construction")
    manual += "\n\n" + doc.link(solution.path("manual-tutorial.html"), "Open the step-by-step manual tutorial") + "."
    instructions = solution.path("manual/GLOBAL-INSTRUCTIONS.md")
    doc.source(instructions)
    manual += "\n\n### Instructions and upload inventory\n\n"
    manual += "- " + doc.link(instructions, "Copy the reviewed global instructions") + "\n\n"
    knowledge = _manual_knowledge(doc)
    if not library.exists(solution.path("manual/knowledge")):
        manual += (
            "The package has no `manual/knowledge/` directory. "
            "Use the manual knowledge uploads explicitly declared by its export manifest below.\n\n"
        )
    manual += _table(
        ("File", "Role"),
        ((doc.link(path, path.removeprefix(solution.package + "/")), role) for path, role in knowledge),
        doc.missing(solution.path("export-manifest.json"), "manual knowledge uploads"),
    )
    manual += "\n\n" + doc.inventory(solution.path("manual/skills/*/SKILL.md"), "Upload the reviewed SKILL.md unchanged")
    commands = [_text(command) for command in _items(architecture.get("manual_commands"))]
    routine = [command for command in commands if not re.search(r"\bpublish\b", command, re.I)]
    publication = [command for command in commands if re.search(r"\bpublish\b", command, re.I)]
    manual += "\n\n### CLI reference — not the manual browser lane\n\n"
    manual += (
        "The catalog also records these commands for source-controlled delivery. "
        "Do not run them as substitutes for the literal browser steps above.\n\n"
        + _code("\n".join(routine))
        if routine else doc.missing(CATALOG, "architecture.manual_commands")
    )
    if publication:
        manual += "\n\n### Publication reference — outside this workshop\n\n"
        manual += "These catalog commands require separate human approval; they are not build or acceptance steps.\n\n"
        manual += _code("\n".join(publication))
    doc.add("Phase 3 — Manual Build in Copilot Studio", manual)
    smoke = _object(deployment.get("smoke_test"))
    smoke_rows = [
        ("Prompt", _text(smoke.get("prompt"), "Not provided in deployment.json smoke_test.prompt")),
        ("Must call", _text(smoke.get("must_call"), "Not provided in deployment.json smoke_test.must_call")),
        ("Must include", _text(smoke.get("must_include"), "Not provided in deployment.json smoke_test.must_include")),
    ]
    if smoke.get("arguments"):
        smoke_rows.append(("Arguments", _text(smoke["arguments"])))
    doc.add("Phase 4 — Acceptance", "\n\n".join((
        "**Synthetic demo acceptance:** expected names, identifiers, and figures below are fictional test evidence, not customer results.",
        _bullets(architecture.get("acceptance_checks"), doc.missing(CATALOG, "architecture.acceptance_checks"), checklist=True),
        "### Deployment smoke test",
        _table(("Check", "Expected value"), smoke_rows, doc.missing(solution.path("deployment.json"), "smoke_test")),
        "### Package evidence gates",
        doc.copy(guide, "Evidence gates"),
    )))
    doc.add("Phase 5 — Production Hardening", _bullets(
        architecture.get("hard_mode"), doc.missing(CATALOG, "architecture.hard_mode"), checklist=True,
    ) + "\n\nReview the [production replacement seams](2.Architecture.md#production-replacement-seams) "
            "and the package's customer gate before changing data sources or enabling writes; "
            "this generated checklist does not establish production readiness.")
    doc.add("Failure Recovery", doc.copy(guide, "Failure recovery"))
    doc.add("Deliverables Checklist", _release_checklist(doc) + "\n\nSource: "
            + doc.link("solutions/README.md", "seven-step release gate", "release-gate")
            + ". Record fresh evidence against each check; this list is not a claim that the checks passed.")
    return doc.render("Delivery Runbook", _nav("4.Sample-prompts.md", "Sample prompts and boundary cases"))


def _case_id(record: dict) -> str:
    return _text(record.get("id") or record.get("case_id"), "Case identifier not recorded")


def _sample_prompts(library: Library, solution: Solution) -> str:
    doc = Document(library, solution, "4.Sample-prompts.md")
    instructions = solution.path("manual/GLOBAL-INSTRUCTIONS.md")
    cases = doc.data(solution.demo_source)
    transcripts = doc.data(solution.path("evals/transcripts.json"))
    promise_map = doc.data(solution.path("evals/onepager-map.json"))
    case_rows = [item for item in _items(cases.get("cases")) if isinstance(item, dict)]
    transcript_rows = [item for item in _items(transcripts.get("transcripts")) if isinstance(item, dict)]
    by_id = {_case_id(item): item for item in transcript_rows}
    by_id.update({_case_id(item): item for item in case_rows})
    doc.add("Suggested Agent Instructions",
            "Use " + doc.link(instructions, "the complete reviewed global instructions")
            + ", not the excerpts alone.\n\n" + doc.copy(
                instructions, "Skill routing map", ("Natural-language routing", "Routing", "Locked Preview routing"),
            ))
    demos = []
    for item in _items(solution.copy.get("sample_prompts")):
        item = _object(item)
        url = item.get("demo_url")
        if isinstance(url, str) and url:
            target = urlsplit(url)
            path = unquote(target.path).lstrip("/")
            if target.scheme or target.netloc:
                raise RunbookSourceError(f"{CATALOG}: {solution.name} demo_url must be repo-relative: {url}")
            if path not in library.files:
                raise RunbookSourceError(f"{CATALOG}: {solution.name} demo_url target is missing: {path}")
            link = PAGES + quote(path, safe="/@-._~")
            link += ("?" + target.query if target.query else "") + ("#" + target.fragment if target.fragment else "")
            demo = f"[Open captured demo]({link})"
        else:
            demo = "No demo_url provided in catalog sample_prompts"
        demos.append((item.get("label"), item.get("prompt"), demo))
    synthetic = (
        "**Synthetic demo evidence:** all example records, names, identifiers, and figures in these cases "
        "are fictional; prompts and recorded expectations are not customer outcomes."
    )
    doc.source(solution.path("FIELD-GUIDE.md"))
    doc.add("Demo Prompts", synthetic + "\n\n" + _table(
        ("Scenario", "Prompt", "Demo"), demos, doc.missing(CATALOG, "sample_prompts"),
    ))
    promises = []
    for item in _items(promise_map.get("promises")):
        item = _object(item)
        prompts = []
        for identifier in _items(item.get("demo_cases")):
            case = by_id.get(str(identifier), {})
            prompt = _text(case.get("prompt"), f"No prompt for {identifier} in demo cases or transcripts")
            prompts.append(f"**{identifier}:** {prompt}")
        promises.append((
            item.get("advertised_promise") or item.get("promise"),
            _text(item.get("operations"), "No operations provided in onepager-map.json"),
            "\n".join(prompts) or "No demo_cases provided in onepager-map.json",
        ))
    doc.add("Promise-to-Prompt Map",
            "Advertised promises are traced to synthetic cases below; mapping a promise does not prove a production capability.\n\n"
            + _table(("Advertised promise", "Operation", "Persona prompt"), promises,
                     doc.missing(solution.path("evals/onepager-map.json"), "promises")))
    expected = []
    for item in transcript_rows:
        recorded = (
            "passed: " + _text(item["passed"]) if "passed" in item
            else _text(item.get("status") or item.get("verdict"), "No verdict field recorded")
        )
        expected.append((
            _case_id(item), item.get("prompt"),
            item.get("expected_agent") or item.get("tool") or item.get("must_call"),
            _text(item.get("must_include"), "No must_include provided in transcript"),
            recorded,
        ))
    doc.add("Expected Results", "The following fields are recorded in "
            + doc.link(solution.path("evals/transcripts.json"), "canonical transcripts")
            + "; this generator has not replayed or revalidated them.\n\n"
            + _table(("Case", "Prompt", "Expected tool", "Must include", "Recorded result"), expected,
                     doc.missing(solution.path("evals/transcripts.json"), "transcripts")))
    routing = []
    for case in case_rows:
        arguments = _object(case.get("arguments") or case.get("kwargs"))
        operation = case.get("operation") or arguments.get("operation")
        route = _text(case.get("expects_agent"), "No expects_agent provided in demo case")
        if operation:
            route += "\nOperation: " + _text(operation)
        assertions = []
        if case.get("must_not_include"):
            assertions.append("Must not include: " + _text(case["must_not_include"]))
        if _present(case.get("min_words")):
            assertions.append("Minimum words: " + _text(case["min_words"]))
        if case.get("assertion_note"):
            assertions.append(_text(case["assertion_note"]))
        routing.append((
            _case_id(case), _text(case.get("persona")) + "\n" + _text(case.get("prompt")),
            route, "\n".join(assertions) or "No negative assertions recorded in this demo case",
        ))
    doc.add("Routing and Boundary Cases", _table(
        ("Case", "Persona / prompt", "Expected route", "Boundary assertions"), routing,
        doc.missing(solution.demo_source, "cases"),
    ))
    doc.add("What This Agent Should Never Do", doc.copy(
        instructions, "Privacy, human, and side-effect gates",
        ("Decision and safety rules", "Human and side-effect gates", "Prohibited actions",
         "Legal and authorization gates", "Boundaries", "Safety boundary"),
    ))
    next_file = "5.Acceptance-Evidence.md" if _evidence_files(library, solution) else "0.Resources/README.md"
    return doc.render("Sample Prompts", _nav(next_file, "Acceptance evidence" if next_file.startswith("5.") else "Resources"))


def _evidence_files(library: Library, solution: Solution) -> list[str]:
    return sorted({
        name for name in library.files
        if posixpath.dirname(name) == solution.path("evals")
        and (fnmatch.fnmatchcase(posixpath.basename(name), "*evidence*.json")
             or posixpath.basename(name) == "visual-checkpoints.json")
    })


def _recorded_fields(value, prefix: str = ""):
    if isinstance(value, dict):
        for key, item in sorted(value.items()):
            path = prefix + "." + key if prefix else key
            if (
                key in {"status", "verdict", "published"}
                or key.endswith("_status") or key.endswith("_verdict")
            ) and _present(item) and not isinstance(item, (dict, list)):
                yield path, _text(item)
            if isinstance(item, (dict, list)):
                yield from _recorded_fields(item, path)
    elif isinstance(value, list):
        for index, item in enumerate(value):
            yield from _recorded_fields(item, f"{prefix}[{index}]")


def _manifest_references(doc: Document) -> list[dict]:
    data = doc.data(doc.solution.path("export-manifest.json"))
    return [item for item in _items(data.get("files")) if isinstance(item, dict)]


def _manifest_path(solution: Solution, value) -> str | None:
    if not isinstance(value, str) or not value:
        return None
    if value.startswith(("solutions/", "agents/", "tests/", "state/", "skills/", "docs/")):
        return value
    if _SCHEME.match(value) or value.startswith("/"):
        return None
    return posixpath.normpath(solution.path(value))


def _manual_knowledge(doc: Document) -> list[tuple[str, str]]:
    paths = {
        path: "Upload as synthetic knowledge"
        for path in doc.library.matching(doc.solution.path("manual/knowledge/*"))
    }
    for item in _manifest_references(doc):
        if "manual knowledge upload" in _text(item.get("use"), "").casefold():
            path = _manifest_path(doc.solution, item.get("path"))
            if path:
                paths[path] = _text(item["use"])
    return sorted(paths.items())


def _evidence(library: Library, solution: Solution) -> str:
    doc = Document(library, solution, "5.Acceptance-Evidence.md")
    paths = _evidence_files(library, solution)
    references = _manifest_references(doc)
    expected = set(paths)
    expected.update(
        path for item in references
        for path in [_manifest_path(solution, item.get("path"))]
        if path and path.startswith(solution.path("evals/"))
    )
    summary_rows = []
    for path in sorted(expected):
        present = path in library.files
        summary_rows.append((
            doc.link(path, posixpath.basename(path)) if present else f"`{path}`",
            "Present" if present else "Missing; listed by export-manifest.json",
        ))
    doc.add("Evidence Summary",
            "**Recorded synthetic evidence, not a fresh validation.** Presence proves only that an artifact exists. "
            "Recorded statuses and historical publication fields below are attributed to their exact source; "
            "they do not authorize publishing or establish current tenant state.\n\n"
            + _table(("Evidence file", "Repository presence"), summary_rows, doc.missing(solution.path("evals")))
            + "\n\n" + doc.link(solution.path("evidence-report.html"), "Open the workshop evidence report") + ".")
    statuses = []
    for path in paths:
        data = doc.data(path)
        fields = list(_recorded_fields(data))
        recorded = [
            (field, value) for field, value in fields
            if not (
                path == solution.path("evals/visual-checkpoints.json")
                and re.fullmatch(r"captures\[\d+\]\.status", field)
            )
        ]
        if recorded:
            statuses.extend((doc.link(path, posixpath.basename(path)), f"`{field}`", value) for field, value in recorded)
        elif fields:
            statuses.append((doc.link(path, posixpath.basename(path)), "Capture statuses", "Listed in Visual Evidence below"))
        else:
            statuses.append((doc.link(path, posixpath.basename(path)), "Status / verdict", "No status or verdict fields recorded"))
    doc.source("solutions/README.md")
    doc.add("Release Gate Status",
            "The generator does not infer an overall pass. Compare these recorded fields with the "
            + doc.link("solutions/README.md", "release gate", "release-gate")
            + " and capture fresh evidence for the intended environment. "
            "Per-capture statuses appear once in Visual Evidence, alongside the source image and reason.\n\n"
            + _table(("Source file", "JSON field", "Recorded value"), statuses, "No status-bearing evidence files are present."))
    images = [
        name for name in library.files
        if name.startswith(solution.path("screenshots/")) and PurePosixPath(name).suffix.lower() in _IMAGE_SUFFIXES
    ]
    groups = Counter(posixpath.dirname(name).removeprefix(solution.package + "/") for name in images)
    visual = (
        f"**Repository image inventory: {len(images)} files.** Counts include annotations, GIFs, and contact sheets; "
        "they are not counts of passing or reusable checkpoints.\n\n"
        + _table(("Directory", "Image files"), (
            (doc.link(solution.path(directory), directory), count) for directory, count in sorted(groups.items())
        ), f"No image files are present under `{solution.path('screenshots')}`.")
    )
    checkpoints_path = solution.path("evals/visual-checkpoints.json")
    checkpoints = doc.data(checkpoints_path)
    summary = _object(checkpoints.get("summary"))
    visual += "\n\n### Recorded checkpoint summary\n\n" + _table(
        ("Field in visual-checkpoints.json", "Recorded value"), sorted(summary.items()),
        doc.missing(checkpoints_path, "summary"),
    )
    captures = []
    for item in _items(checkpoints.get("captures")):
        item = _object(item)
        source = _manifest_path(solution, item.get("source"))
        image_link = doc.link(source, posixpath.basename(source)) if source else "No source image recorded"
        captures.append((
            item.get("id"), item.get("mode"), item.get("status"), image_link,
            _text(item.get("reason"), "No reason recorded"),
        ))
    visual += "\n\n### Checkpoint-by-checkpoint evidence\n\n" + _table(
        ("Checkpoint", "Mode", "Recorded status", "Source image", "Recorded reason"), captures,
        doc.missing(checkpoints_path, "captures"),
    )
    doc.add("Visual Evidence", visual)
    return doc.render("Acceptance Evidence", _nav("0.Resources/README.md", "Resources and exports"))


def _resources(library: Library, solution: Solution) -> str:
    doc = Document(library, solution, "0.Resources/README.md")
    doc.source(REGISTRY)
    resources = (
        ("README.md", "Package scope and release boundary"),
        ("FIELD-GUIDE.md", "Facilitator guidance, recovery, and evidence gates"),
        ("FLOW.md", "Ordered locked-case flow"),
        ("deployment.json", "Machine-readable installation and smoke-test recipe"),
        ("export-manifest.json", "Declared downloadable resources"),
        ("EASY-MODE-COPILOT-CHAT.md", "Default GitHub Copilot lane"),
        ("EASY-MODE-PERSONLESS.md", "Optional Brainstem lane"),
        ("copilot-studio", "Source-controlled Copilot Studio project"),
        ("manual/GLOBAL-INSTRUCTIONS.md", "Reviewed manual agent policy"),
        ("manual/knowledge", "Synthetic knowledge uploads"),
        ("manual/skills", "Operation-specific skill uploads"),
    )
    rows = [(doc.link(solution.path(path), path), role) for path, role in resources]
    rows += [
        (doc.link(_text(solution.agent.get("_file"), "missing-agent-source"), "Portable agent"), "Runtime implementation"),
        (doc.link(solution.demo_source, "Demo case contract"), "Executable persona-language routing and boundary checks"),
        (doc.link(solution.architecture_source, "Level-2 architecture source"), "Domains, tools, and supporting features"),
    ]
    if not library.exists(solution.path("manual/knowledge")):
        rows += [
            (doc.link(path, path.removeprefix(solution.package + "/")), role + " (export-manifest.json)")
            for path, role in _manual_knowledge(doc)
        ]
    doc.add("Package Resources", "Assets stay in the canonical package; this folder links to them without copying binaries.\n\n"
            + _table(("Resource", "Purpose"), rows, doc.missing(solution.package)))
    pages = (
        ("quest.html", "Guided Easy / Manual workshop"),
        ("field-guide.html", "Facilitator and learner field guide"),
        ("evidence-report.html", "Recorded evidence and reuse boundaries"),
        ("manual-tutorial.html", "Literal browser construction tutorial"),
    )
    doc.add("Workshop Pages", _table(
        ("GitHub Pages view", "Purpose"),
        ((doc.link(solution.path(path), path), purpose) for path, purpose in pages),
        doc.missing(solution.package, "workshop pages"),
    ))
    refs = _manifest_references(doc)
    evidence_paths = set(library.matching(solution.path("evals/*")))
    export_paths = set(library.matching(solution.path("exports/*")))
    for item in refs:
        path = _manifest_path(solution, item.get("path"))
        if path and path.startswith(solution.path("evals/")):
            evidence_paths.add(path)
        if path and path.startswith(solution.path("exports/")):
            export_paths.add(path)
    artifact_rows = []
    for kind, paths in (("Evidence", evidence_paths), ("Export", export_paths)):
        for path in sorted(paths):
            artifact_rows.append((
                kind, doc.link(path, path.removeprefix(solution.package + "/")),
                "Present" if path in library.files else "Missing; declared in export manifest",
            ))
    for directory in ("screenshots", "screenshots/assisted", "screenshots/manual"):
        if library.exists(solution.path(directory)):
            artifact_rows.append(("Visual source", doc.link(solution.path(directory), directory), "Directory present"))
    doc.add("Evidence and Exports",
            "This is a presence inventory, not a pass verdict. Review each artifact's synthetic-data and publication boundary.\n\n"
            + _table(("Kind", "Artifact", "Presence"), artifact_rows, doc.missing(solution.path("export-manifest.json"), "evidence and exports")))
    return doc.render(
        "Resources",
        "→ [Overview](../1.Overview.md) | [Acceptance and delivery](../3.Runbook.md) | [Solution index](../../README.md)",
    )


def render_solution(library: Library, package_slug: str) -> dict[str, str]:
    if package_slug not in library.solutions:
        raise RunbookSourceError(f"Unknown catalog package slug: {package_slug}")
    solution = library.solutions[package_slug]
    artifacts = {
        "0.Resources/README.md": _resources(library, solution),
        "1.Overview.md": _overview(library, solution),
        "2.Architecture.md": _architecture(library, solution),
        "3.Runbook.md": _runbook(library, solution),
        "4.Sample-prompts.md": _sample_prompts(library, solution),
    }
    if _evidence_files(library, solution):
        artifacts["5.Acceptance-Evidence.md"] = _evidence(library, solution)
    return artifacts


def _stage(solution: Solution) -> str:
    return solution.stage + (f" / {solution.secondary_stage} (secondary)" if solution.secondary_stage else "")


def _groups(library: Library):
    verticals = sorted({solution.vertical for solution in library.solutions.values()})
    for vertical in verticals:
        yield vertical, sorted(
            (solution for solution in library.solutions.values() if solution.vertical == vertical),
            key=lambda solution: (solution.display_name.casefold(), solution.slug),
        )


def _index(library: Library, selected: set[str]) -> str:
    anatomy = (
        ("0.Resources/README.md", "Links to package assets, workshop pages, evidence, and exports"),
        ("1.Overview.md", "Scenario, qualification, scope, users, and delivery risks"),
        ("2.Architecture.md", "Flow, responsibilities, components, boundaries, and replacement seams"),
        ("3.Runbook.md", "Build lanes, acceptance, recovery, and release checklist"),
        ("4.Sample-prompts.md", "Persona prompts, expected evidence, routing, and prohibited behavior"),
        ("5.Acceptance-Evidence.md", "Optional recorded evidence and screenshot inventory; not a new verdict"),
    )
    parts = [
        GENERATED_MARKER, "", "# Solution Runbooks", "",
        "This generated delivery layer projects the catalog without moving its packages: "
        "canonical assets remain in [solutions/](../solutions/README.md). "
        f"{len(selected)} of {len(library.solutions)} catalog solutions have runbooks in this projection.",
        "",
        "Regenerate with `python tools/build_solution_runbooks.py`; verify without writing with "
        "`python tools/build_solution_runbooks.py --check`. Use `--all` for every catalog solution "
        "or repeat `--solution SLUG` for an explicit projection; use the same selection with `--check`.",
        "",
        "## Artifact Anatomy", "",
        _table(("Artifact", "Delivery question"), anatomy, "No artifact contract recorded."),
        "", "## Solutions by Vertical",
    ]
    for vertical, solutions in _groups(library):
        parts += ["", f"### {vertical}", "", _table(
            ("Solution", "Journey stage", "Runbook", "Workshop", "Package"),
            (
                (
                    solution.display_name, _stage(solution),
                    f"[Read runbook]({solution.slug}/1.Overview.md)" if solution.slug in selected else "Phase 2",
                    f"[Workshop]({PAGES}{solution.package}/quest.html)"
                    if solution.path("quest.html") in library.files else "Workshop page missing",
                    f"[Package](../{solution.package}/README.md)"
                    if solution.path("README.md") in library.files else "Package README missing",
                )
                for solution in solutions
            ), "No catalog solutions are recorded for this vertical.",
        )]
    parts += [
        "", "## Draft Packages", "",
        _table(("Package", "Reason"), (
            (f"[{slug}](../solutions/{slug}/)", reason) for slug, reason in sorted(DRAFT_PACKAGES.items())
        ), "No draft packages are allowlisted."),
        "", "## Identity Aliases", "",
        _table(("Catalog identity", "Package folder"), (
            (name, f"[{slug}](../solutions/{slug}/README.md)") for name, slug in sorted(PACKAGE_ALIASES.items())
        ), "No package aliases are declared."),
        "", "Next: [Library overview](../00-overview/README.md) | [Patterns](../02-patterns/README.md) "
        "| [References](../03-references/README.md)",
    ]
    return _finish("\n".join(parts))


def _taxonomy(library: Library, selected: set[str]) -> str:
    rows = []
    for vertical, solutions in _groups(library):
        links = []
        for solution in solutions:
            target = (
                f"../01-solutions/{solution.slug}/1.Overview.md" if solution.slug in selected
                else f"../{solution.package}/README.md"
            )
            if solution.slug not in selected and solution.path("README.md") not in library.files:
                links.append(solution.display_name + " — package README missing")
            else:
                links.append(f"[{solution.display_name}]({target})")
        rows.append((vertical, "\n".join(links), "\n".join(sorted({_stage(solution) for solution in solutions}))))
    return _table(("Vertical", "Solutions", "Journey stages"), rows, "No catalog solutions are recorded.")


def _taxonomy_bounds(text: str) -> tuple[int, int]:
    if text.count(TAXONOMY_BEGIN) != 1 or text.count(TAXONOMY_END) != 1:
        raise RunbookSourceError(f"{OVERVIEW}: taxonomy markers must each appear exactly once")
    begin = re.search(r"(?m)^" + re.escape(TAXONOMY_BEGIN) + r"$", text)
    end = re.search(r"(?m)^" + re.escape(TAXONOMY_END) + r"$", text)
    if not begin or not end or begin.end() >= end.start():
        raise RunbookSourceError(f"{OVERVIEW}: taxonomy markers must be ordered, exact standalone lines")
    return begin.end(), end.start()


def _replace_taxonomy(text: str, table: str) -> str:
    begin, end = _taxonomy_bounds(text)
    return text[:begin] + "\n\n" + table.strip() + "\n\n" + text[end:]


def _selection(library: Library, solutions) -> tuple[str, ...]:
    selected = RUNBOOK_SOLUTIONS if solutions is None else solutions
    if isinstance(selected, str):
        selected = (selected,)
    selected = tuple(sorted(set(selected)))
    unknown = set(selected) - library.solutions.keys()
    if unknown:
        raise RunbookSourceError("Unknown catalog package slug(s): " + ", ".join(sorted(unknown)))
    return selected


def build_outputs(root: Path = ROOT, solutions=None) -> dict[str, str]:
    library = load_library(root)
    selected = _selection(library, solutions)
    outputs = {}
    for slug in selected:
        for artifact, content in render_solution(library, slug).items():
            outputs[f"01-solutions/{slug}/{artifact}"] = content
    outputs[INDEX] = _index(library, set(selected))
    if OVERVIEW not in library.files:
        raise RunbookSourceError(f"Missing taxonomy host: {OVERVIEW}")
    current = (library.root / OVERVIEW).read_bytes().decode("utf-8")
    outputs[OVERVIEW] = _replace_taxonomy(current, _taxonomy(library, set(selected)))
    return dict(sorted(outputs.items()))


def _check_outputs(root: Path, outputs: dict[str, str]) -> list[str]:
    messages = []
    for relative, expected in sorted(outputs.items()):
        path = root / relative
        if not path.is_file():
            messages.append(f"missing: {relative}")
        elif path.read_bytes() != expected.encode("utf-8"):
            messages.append(
                f"changed: taxonomy block in {relative}" if relative == OVERVIEW else f"changed: {relative}"
            )
    expected_paths = {name for name in outputs if name.startswith("01-solutions/")}
    actual_paths = {name for name in _file_universe(root) if name.startswith("01-solutions/")}
    messages.extend(f"stale extra file: {name}" for name in sorted(actual_paths - expected_paths))
    return messages


def check(root: Path = ROOT) -> list[str]:
    root = Path(root).resolve()
    try:
        return _check_outputs(root, build_outputs(root))
    except (RunbookSourceError, OSError, UnicodeError) as exc:
        return [f"source error: {exc}"]


def _write_outputs(root: Path, outputs: dict[str, str]) -> int:
    changed = 0
    for relative, content in sorted(outputs.items()):
        if relative == OVERVIEW:
            continue
        path = root / relative
        encoded = content.encode("utf-8")
        if path.is_file() and path.read_bytes() == encoded:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(encoded)
        changed += 1
    expected = outputs[OVERVIEW]
    begin, end = _taxonomy_bounds(expected)
    table = expected[begin:end].strip()
    # Re-read immediately before updating: the surrounding narrative is authored
    # independently and must never be overwritten by an earlier render snapshot.
    path = root / OVERVIEW
    current = path.read_bytes().decode("utf-8")
    updated = _replace_taxonomy(current, table)
    if updated != current:
        path.write_bytes(updated.encode("utf-8"))
        changed += 1
    return changed


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Report drift without writing")
    selection = parser.add_mutually_exclusive_group()
    selection.add_argument("--all", action="store_true", help="Project every catalog solution")
    selection.add_argument("--solution", action="append", metavar="SLUG", help="Package slug to project (repeatable)")
    args = parser.parse_args(argv)
    try:
        selected = tuple(load_library(ROOT).solutions) if args.all else args.solution
        outputs = build_outputs(ROOT, solutions=selected)
        if args.check:
            messages = _check_outputs(ROOT, outputs)
            if messages:
                print("\n".join(messages))
                return 1
            print("Solution runbooks and taxonomy are in sync.")
            return 0
        count = _write_outputs(ROOT, outputs)
        print(f"Generated {len(outputs) - 1} runbook files and the taxonomy block; {count} files changed.")
        return 0
    except (RunbookSourceError, OSError, UnicodeError) as exc:
        print(f"Runbook source error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
