#!/usr/bin/env python3
"""Harvest per-asset download counts from GitHub Releases into
rar/downloads.json — real, GitHub-native numbers (an upgrade over the
upstream pattern's hand-maintained Clarity CSV). Assets map through the
catalog's collision-safe _install_filename, with the original slug-derived
release name retained for historical counts. Non-fatal; never clobbers
non-empty data with empty."""
import json
import os
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "rar" / "downloads.json"
CFG = json.loads((ROOT / "rar" / "ratings-config.json").read_text())


def build_asset_slug_map(agents):
    """Map current and legacy release filenames when they identify one agent."""
    candidates = {}
    for agent in agents:
        slug = agent["name"].split("/", maxsplit=1)[1]
        filenames = {
            agent["_install_filename"],
            f"{slug.replace('-', '_')}_agent.py",
        }
        for filename in filenames:
            candidates.setdefault(filename, set()).add(slug)
    return {
        filename: next(iter(slugs))
        for filename, slugs in candidates.items()
        if len(slugs) == 1
    }


def main():
    token = os.environ.get("GITHUB_TOKEN", "")
    counts = {}
    try:
        url = f"https://api.github.com/repos/{CFG['repo']}/releases?per_page=100"
        req = urllib.request.Request(url, headers={
            "User-Agent": "aibast-downloads",
            **({"Authorization": f"bearer {token}"} if token else {})})
        with urllib.request.urlopen(req, timeout=30) as r:
            releases = json.load(r)
        agents = json.loads(
            (ROOT / "rar" / "registry.json").read_text()
        )["agents"]
        asset_slugs = build_asset_slug_map(agents)
        by_tag = {}
        for rel in releases:
            tag = rel.get("tag_name", "untagged")
            for asset in rel.get("assets", []):
                by_tag.setdefault(tag, 0)
                by_tag[tag] += asset.get("download_count", 0)
                asset_name = asset.get("name", "")
                slug = asset_slugs.get(asset_name)
                if slug:
                    counts[slug] = counts.get(slug, 0) + asset.get("download_count", 0)
                else:
                    key = "_other:" + asset_name
                    counts[key] = counts.get(key, 0) + asset.get("download_count", 0)
    except Exception as e:  # noqa: BLE001 — non-fatal by design
        print(f"[downloads] fetch failed, file unchanged: {e}")
        return 0
    prev = json.loads(OUT.read_text()) if OUT.exists() else {}
    data_prev = {k: v for k, v in prev.items() if not k.startswith("_")}
    data_new = {k: v for k, v in counts.items() if not k.startswith("_other:")}
    if not counts and data_prev:
        print("[downloads] refusing to clobber non-empty data with empty")
        return 0
    out = {"_note": ("Generated by tools/fetch_release_downloads.py from GitHub Release asset "
                     "download counts — real, GitHub-native numbers, no client telemetry. "
                     "Zero until the first release ships agent assets.")}
    out["_by_release"] = dict(sorted(by_tag.items())) if 'by_tag' in dir() else {}
    out.update(dict(sorted(counts.items())))
    OUT.write_text(json.dumps(out, indent=1) + "\n")
    print(f"[downloads] {len(data_new)} agents with counts "
          f"({sum(data_new.values())} total downloads)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
